"""The Lean program capdagFormal (generated by lungo 1.78.3254 from Lean 4.34.1). Do not edit."""

from __future__ import annotations

import os as _os
import sys as _sys
import typing as _t
from dataclasses import dataclass as _dataclass

import lungo_py
import tagged_urn._formal as _ext_0

if lungo_py.__version__ != "1.78.3254":
    raise ImportError(f"this package needs lungo_py 1.78.3254, not {lungo_py.__version__}")


def _library() -> str:
    name = {"win32": "capdagFormal_lean.dll", "darwin": "libcapdagFormal_lean.dylib"}.get(_sys.platform, "libcapdagFormal_lean.so")
    for directory in __path__:
        path = _os.path.join(directory, name)
        if _os.path.isfile(path):
            return path
    raise ImportError(f"the compiled program {name} is in none of {list(__path__)}: install the package with pip")


_program = lungo_py.Program(_library(), "capdagFormal__types")

if _ext_0.Wf.__lungo_fingerprint__ != "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785":
    raise ImportError("TaggedUrn.Exec.Wf of tagged_urn._formal has another layout than the one this program was generated for: regenerate both from the same Lean definition")


@_dataclass(frozen=True)
class WfCap:
    """Lean's CapDAG.Exec.WfCap."""
    input: _ext_0.Wf
    output: _ext_0.Wf
    other: _ext_0.Wf
    effect: Effect


class _WfCapType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(0)

    def encode(self, w, v):
        if isinstance(v, WfCap):
            w.u32(0)
            _ext_type_3().encode(w, v.input)
            _ext_type_3().encode(w, v.output)
            _ext_type_3().encode(w, v.other)
            effect_type().encode(w, v.effect)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Exec.WfCap")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return WfCap(_ext_type_3().decode(r), _ext_type_3().decode(r), _ext_type_3().decode(r), effect_type().decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Exec.WfCap")


def wf_cap_type() -> lungo_py.Type[WfCap]:
    """Describes CapDAG.Exec.WfCap for polymorphic functions."""
    return _WfCapType()


WfCap.__lungo_fingerprint__ = "2b8d6466d218f4ae6bc98d95bba55d98f21cac4a49446ae170993773cefdb830"
WfCap.__lungo_descriptor__ = staticmethod(wf_cap_type)


class Effect:
    """Lean's CapDAG.Effect: one of EffectUnspecified, EffectDeclared, EffectNone_, EffectPatch."""

    __slots__ = ()


@_dataclass(frozen=True)
class EffectUnspecified(Effect):
    """Lean's CapDAG.Effect.unspecified."""


@_dataclass(frozen=True)
class EffectDeclared(Effect):
    """Lean's CapDAG.Effect.declared."""


@_dataclass(frozen=True)
class EffectNone_(Effect):
    """Lean's CapDAG.Effect.none."""


@_dataclass(frozen=True)
class EffectPatch(Effect):
    """Lean's CapDAG.Effect.patch."""


class _EffectType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(1)

    def encode(self, w, v):
        if isinstance(v, EffectUnspecified):
            w.u32(0)
        elif isinstance(v, EffectDeclared):
            w.u32(1)
        elif isinstance(v, EffectNone_):
            w.u32(2)
        elif isinstance(v, EffectPatch):
            w.u32(3)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Effect")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return EffectUnspecified()
        if c == 1:
            return EffectDeclared()
        if c == 2:
            return EffectNone_()
        if c == 3:
            return EffectPatch()
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Effect")


def effect_type() -> lungo_py.Type[Effect]:
    """Describes CapDAG.Effect for polymorphic functions."""
    return _EffectType()


Effect.__lungo_fingerprint__ = "38c7bd3c0527cda156713cd441c9b6b92bd5df8a39108fa101449a789abcb477"
Effect.__lungo_descriptor__ = staticmethod(effect_type)


@_dataclass(frozen=True)
class WfQuery:
    """Lean's CapDAG.Exec.WfQuery."""
    input: WfAsk
    output: WfAsk
    tags: _ext_0.Wf
    effect: Effect


class _WfQueryType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(2)

    def encode(self, w, v):
        if isinstance(v, WfQuery):
            w.u32(0)
            wf_ask_type().encode(w, v.input)
            wf_ask_type().encode(w, v.output)
            _ext_type_3().encode(w, v.tags)
            effect_type().encode(w, v.effect)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Exec.WfQuery")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return WfQuery(wf_ask_type().decode(r), wf_ask_type().decode(r), _ext_type_3().decode(r), effect_type().decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Exec.WfQuery")


def wf_query_type() -> lungo_py.Type[WfQuery]:
    """Describes CapDAG.Exec.WfQuery for polymorphic functions."""
    return _WfQueryType()


WfQuery.__lungo_fingerprint__ = "e734861d70e3177f6563c4492990bb65131f0450b8dfc62071eb61b6c5f08b8e"
WfQuery.__lungo_descriptor__ = staticmethod(wf_query_type)


class _ExtType3(lungo_py.Type):
    """Lean's TaggedUrn.Exec.Wf, provided by tagged_urn._formal."""

    def __init__(self):
        self._provided = _ext_0.Wf.__lungo_descriptor__()

    def expr(self):
        return lungo_py.inductive_expr(3)

    def encode(self, w, v):
        self._provided.encode(w, v)

    def decode(self, r):
        return self._provided.decode(r)


def _ext_type_3():
    return _ExtType3()


class Grade:
    """Lean's CapDAG.Grade: one of GradeExact, GradeGuaranteed, GradePossible, GradeNone_."""

    __slots__ = ()


@_dataclass(frozen=True)
class GradeExact(Grade):
    """Lean's CapDAG.Grade.exact."""


@_dataclass(frozen=True)
class GradeGuaranteed(Grade):
    """Lean's CapDAG.Grade.guaranteed."""


@_dataclass(frozen=True)
class GradePossible(Grade):
    """Lean's CapDAG.Grade.possible."""


@_dataclass(frozen=True)
class GradeNone_(Grade):
    """Lean's CapDAG.Grade.none."""


class _GradeType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(4)

    def encode(self, w, v):
        if isinstance(v, GradeExact):
            w.u32(0)
        elif isinstance(v, GradeGuaranteed):
            w.u32(1)
        elif isinstance(v, GradePossible):
            w.u32(2)
        elif isinstance(v, GradeNone_):
            w.u32(3)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Grade")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return GradeExact()
        if c == 1:
            return GradeGuaranteed()
        if c == 2:
            return GradePossible()
        if c == 3:
            return GradeNone_()
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Grade")


def grade_type() -> lungo_py.Type[Grade]:
    """Describes CapDAG.Grade for polymorphic functions."""
    return _GradeType()


Grade.__lungo_fingerprint__ = "0a2a20a14d9ecca6121343df2d8a7f2478b3e837710ed522ed385d35efdf46f2"
Grade.__lungo_descriptor__ = staticmethod(grade_type)


class Constraint:
    """Lean's TaggedUrn.Constraint: one of ConstraintMissing, ConstraintUnconstrained, ConstraintOptionalNot, ConstraintPresent, ConstraintPresentNot, ConstraintExact, ConstraintAbsent."""

    __slots__ = ()


@_dataclass(frozen=True)
class ConstraintMissing(Constraint):
    """Lean's TaggedUrn.Constraint.missing."""


@_dataclass(frozen=True)
class ConstraintUnconstrained(Constraint):
    """Lean's TaggedUrn.Constraint.unconstrained."""


@_dataclass(frozen=True)
class ConstraintOptionalNot(Constraint):
    """Lean's TaggedUrn.Constraint.optionalNot."""
    value: str


@_dataclass(frozen=True)
class ConstraintPresent(Constraint):
    """Lean's TaggedUrn.Constraint.present."""


@_dataclass(frozen=True)
class ConstraintPresentNot(Constraint):
    """Lean's TaggedUrn.Constraint.presentNot."""
    value: str


@_dataclass(frozen=True)
class ConstraintExact(Constraint):
    """Lean's TaggedUrn.Constraint.exact."""
    value: str


@_dataclass(frozen=True)
class ConstraintAbsent(Constraint):
    """Lean's TaggedUrn.Constraint.absent."""


class _ConstraintType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(5)

    def encode(self, w, v):
        if isinstance(v, ConstraintMissing):
            w.u32(0)
        elif isinstance(v, ConstraintUnconstrained):
            w.u32(1)
        elif isinstance(v, ConstraintOptionalNot):
            w.u32(2)
            lungo_py.STRING.encode(w, v.value)
        elif isinstance(v, ConstraintPresent):
            w.u32(3)
        elif isinstance(v, ConstraintPresentNot):
            w.u32(4)
            lungo_py.STRING.encode(w, v.value)
        elif isinstance(v, ConstraintExact):
            w.u32(5)
            lungo_py.STRING.encode(w, v.value)
        elif isinstance(v, ConstraintAbsent):
            w.u32(6)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a TaggedUrn.Constraint")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return ConstraintMissing()
        if c == 1:
            return ConstraintUnconstrained()
        if c == 2:
            return ConstraintOptionalNot(lungo_py.STRING.decode(r))
        if c == 3:
            return ConstraintPresent()
        if c == 4:
            return ConstraintPresentNot(lungo_py.STRING.decode(r))
        if c == 5:
            return ConstraintExact(lungo_py.STRING.decode(r))
        if c == 6:
            return ConstraintAbsent()
        raise lungo_py.MalformedError(f"constructor index {c} of TaggedUrn.Constraint")


def constraint_type() -> lungo_py.Type[Constraint]:
    """Describes TaggedUrn.Constraint for polymorphic functions."""
    return _ConstraintType()


Constraint.__lungo_fingerprint__ = "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7"
Constraint.__lungo_descriptor__ = staticmethod(constraint_type)


class WfAsk:
    """Lean's CapDAG.Exec.WfAsk: one of WfAskUnknown, WfAskWithin, WfAskCovers, WfAskSame."""

    __slots__ = ()


@_dataclass(frozen=True)
class WfAskUnknown(WfAsk):
    """Lean's CapDAG.Exec.WfAsk.unknown."""


@_dataclass(frozen=True)
class WfAskWithin(WfAsk):
    """Lean's CapDAG.Exec.WfAsk.within."""
    u: _ext_0.Wf


@_dataclass(frozen=True)
class WfAskCovers(WfAsk):
    """Lean's CapDAG.Exec.WfAsk.covers."""
    u: _ext_0.Wf


@_dataclass(frozen=True)
class WfAskSame(WfAsk):
    """Lean's CapDAG.Exec.WfAsk.same."""
    u: _ext_0.Wf


class _WfAskType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(6)

    def encode(self, w, v):
        if isinstance(v, WfAskUnknown):
            w.u32(0)
        elif isinstance(v, WfAskWithin):
            w.u32(1)
            _ext_type_3().encode(w, v.u)
        elif isinstance(v, WfAskCovers):
            w.u32(2)
            _ext_type_3().encode(w, v.u)
        elif isinstance(v, WfAskSame):
            w.u32(3)
            _ext_type_3().encode(w, v.u)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Exec.WfAsk")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return WfAskUnknown()
        if c == 1:
            return WfAskWithin(_ext_type_3().decode(r))
        if c == 2:
            return WfAskCovers(_ext_type_3().decode(r))
        if c == 3:
            return WfAskSame(_ext_type_3().decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Exec.WfAsk")


def wf_ask_type() -> lungo_py.Type[WfAsk]:
    """Describes CapDAG.Exec.WfAsk for polymorphic functions."""
    return _WfAskType()


WfAsk.__lungo_fingerprint__ = "d286477c7abc4e6bc6ee2d06889372b71a5bb06605b592ebabb6ad3eaf71b952"
WfAsk.__lungo_descriptor__ = staticmethod(wf_ask_type)


def accepts(pattern: WfCap, cap: WfCap) -> bool:
    """Lean's CapDAG.Exec.accepts : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_daccepts", (), ((wf_cap_type(), pattern), (wf_cap_type(), cap),), lungo_py.value(lungo_py.BOOL))


def comparable(a: WfCap, b: WfCap) -> bool:
    """Lean's CapDAG.Exec.comparable : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dcomparable", (), ((wf_cap_type(), a), (wf_cap_type(), b),), lungo_py.value(lungo_py.BOOL))


def dispatch(candidate: WfCap, request: WfCap) -> bool:
    """Lean's CapDAG.Exec.dispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_ddispatch", (), ((wf_cap_type(), candidate), (wf_cap_type(), request),), lungo_py.value(lungo_py.BOOL))


def effect_ok(candidate: Effect, request: Effect) -> bool:
    """Lean's CapDAG.Exec.effectOk : CapDAG.Effect → CapDAG.Effect → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_deffectOk", (), ((effect_type(), candidate), (effect_type(), request),), lungo_py.value(lungo_py.BOOL))


def equivalent(a: WfCap, b: WfCap) -> bool:
    """Lean's CapDAG.Exec.equivalent : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dequivalent", (), ((wf_cap_type(), a), (wf_cap_type(), b),), lungo_py.value(lungo_py.BOOL))


def flows(a: WfCap, b: WfCap) -> bool:
    """Lean's CapDAG.Exec.flows : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dflows", (), ((wf_cap_type(), a), (wf_cap_type(), b),), lungo_py.value(lungo_py.BOOL))


def may_dispatch(candidate: WfCap, request: WfCap) -> bool:
    """Lean's CapDAG.Exec.mayDispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dmayDispatch", (), ((wf_cap_type(), candidate), (wf_cap_type(), request),), lungo_py.value(lungo_py.BOOL))


def may_flow(a: WfCap, b: WfCap) -> bool:
    """Lean's CapDAG.Exec.mayFlow : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dmayFlow", (), ((wf_cap_type(), a), (wf_cap_type(), b),), lungo_py.value(lungo_py.BOOL))


def query_admits(q: WfQuery, c_: WfCap) -> bool:
    """Lean's CapDAG.Exec.queryAdmits : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryAdmits", (), ((wf_query_type(), q), (wf_cap_type(), c_),), lungo_py.value(lungo_py.BOOL))


def query_between(input: _ext_0.Wf, output: _ext_0.Wf, tags: _ext_0.Wf) -> WfQuery:
    """Lean's CapDAG.Exec.queryBetween : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryBetween", (), ((_ext_type_3(), input), (_ext_type_3(), output), (_ext_type_3(), tags),), lungo_py.value(wf_query_type()))


def query_consuming(input: _ext_0.Wf, tags: _ext_0.Wf) -> WfQuery:
    """Lean's CapDAG.Exec.queryConsuming : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryConsuming", (), ((_ext_type_3(), input), (_ext_type_3(), tags),), lungo_py.value(wf_query_type()))


def query_grade(q: WfQuery, c_: WfCap) -> Grade:
    """Lean's CapDAG.Exec.queryGrade : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → CapDAG.Grade"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryGrade", (), ((wf_query_type(), q), (wf_cap_type(), c_),), lungo_py.value(grade_type()))


def query_may_admit(q: WfQuery, c_: WfCap) -> bool:
    """Lean's CapDAG.Exec.queryMayAdmit : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryMayAdmit", (), ((wf_query_type(), q), (wf_cap_type(), c_),), lungo_py.value(lungo_py.BOOL))


def query_of_pattern(p: WfCap) -> WfQuery:
    """Lean's CapDAG.Exec.queryOfPattern : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryOfPattern", (), ((wf_cap_type(), p),), lungo_py.value(wf_query_type()))


def query_of_request(r_: WfCap) -> WfQuery:
    """Lean's CapDAG.Exec.queryOfRequest : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryOfRequest", (), ((wf_cap_type(), r_),), lungo_py.value(wf_query_type()))


def query_producing(output: _ext_0.Wf, tags: _ext_0.Wf) -> WfQuery:
    """Lean's CapDAG.Exec.queryProducing : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryProducing", (), ((_ext_type_3(), output), (_ext_type_3(), tags),), lungo_py.value(wf_query_type()))


def ranking_key(candidate: WfCap, request: WfCap) -> _t.Tuple[int, int]:
    """Lean's CapDAG.Exec.rankingKey : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Nat × Nat"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_drankingKey", (), ((wf_cap_type(), candidate), (wf_cap_type(), request),), lungo_py.value(lungo_py.pair(lungo_py.NAT, lungo_py.NAT)))


def select(candidates: _t.List[WfCap], request: WfCap) -> _t.Optional[WfCap]:
    """Lean's CapDAG.Exec.select : List CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Option CapDAG.Exec.WfCap"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dselect", (), ((lungo_py.list_of(wf_cap_type()), candidates), (wf_cap_type(), request),), lungo_py.value(lungo_py.option(wf_cap_type())))


def specificity(c_: WfCap) -> int:
    """Lean's CapDAG.Exec.specificity : CapDAG.Exec.WfCap → Nat"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dspecificity", (), ((wf_cap_type(), c_),), lungo_py.value(lungo_py.NAT))


def make(scheme: str, tags: _t.List[_t.Tuple[str, Constraint]]) -> _t.Optional[_ext_0.Wf]:
    """Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf"""
    return _program.invoke("capdagFormal__call_l_TaggedUrn_dExec_dmake", (), ((lungo_py.STRING, scheme), (lungo_py.list_of(lungo_py.pair(lungo_py.STRING, constraint_type())), tags),), lungo_py.value(lungo_py.option(_ext_type_3())))
