"""The Lean program capdagFormal (generated by lungo 1.81.24 from Lean 4.34.1). Do not edit."""

from __future__ import annotations

import os as _os
import sys as _sys
import typing as _t
from dataclasses import dataclass as _dataclass

import lungo_py
import tagged_urn._formal as _ext_0

if lungo_py.__version__ != "1.81.24":
    raise ImportError(f"this package needs lungo_py 1.81.24, not {lungo_py.__version__}")


def _library() -> str:
    name = {"win32": "capdagFormal_lean.dll", "darwin": "libcapdagFormal_lean.dylib"}.get(_sys.platform, "libcapdagFormal_lean.so")
    for directory in __path__:
        path = _os.path.join(directory, name)
        if _os.path.isfile(path):
            return path
    raise ImportError(f"the compiled program {name} is in none of {list(__path__)}: install the package with pip")


_program = lungo_py.Program(_library(), "capdagFormal__types")

if _ext_0.Wf.__lungo_fingerprint__ != "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785":
    raise ImportError("TaggedUrn.Exec.Wf of tagged_urn._formal has another layout than the one this program was generated for: regenerate both from the same Lean definition")


@_dataclass(frozen=True)
class Gate:
    """Lean's CapDAG.Bifaci.Credit.Gate."""
    available: int
    closed: _t.Optional[str]


class _GateType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(0)

    def encode(self, w, v):
        if isinstance(v, Gate):
            w.u32(0)
            lungo_py.NAT.encode(w, v.available)
            lungo_py.option(lungo_py.STRING).encode(w, v.closed)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Credit.Gate")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return Gate(lungo_py.NAT.decode(r), lungo_py.option(lungo_py.STRING).decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Credit.Gate")


def gate_type() -> lungo_py.Type[Gate]:
    """Describes CapDAG.Bifaci.Credit.Gate for polymorphic functions."""
    return _GateType()


Gate.__lungo_fingerprint__ = "b10dc9a4cff1977f4f6a2c415147f497f98740255d0158fb2b3a2a99d4d1b135"
Gate.__lungo_descriptor__ = staticmethod(gate_type)


class Acquire:
    """Lean's CapDAG.Bifaci.Credit.Acquire: one of AcquireAcquired, AcquireWait, AcquireClosed."""

    __slots__ = ()


@_dataclass(frozen=True)
class AcquireAcquired(Acquire):
    """Lean's CapDAG.Bifaci.Credit.Acquire.acquired."""
    gate: Gate


@_dataclass(frozen=True)
class AcquireWait(Acquire):
    """Lean's CapDAG.Bifaci.Credit.Acquire.wait."""


@_dataclass(frozen=True)
class AcquireClosed(Acquire):
    """Lean's CapDAG.Bifaci.Credit.Acquire.closed."""
    reason: str


class _AcquireType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(1)

    def encode(self, w, v):
        if isinstance(v, AcquireAcquired):
            w.u32(0)
            gate_type().encode(w, v.gate)
        elif isinstance(v, AcquireWait):
            w.u32(1)
        elif isinstance(v, AcquireClosed):
            w.u32(2)
            lungo_py.STRING.encode(w, v.reason)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Credit.Acquire")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return AcquireAcquired(gate_type().decode(r))
        if c == 1:
            return AcquireWait()
        if c == 2:
            return AcquireClosed(lungo_py.STRING.decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Credit.Acquire")


def acquire_type() -> lungo_py.Type[Acquire]:
    """Describes CapDAG.Bifaci.Credit.Acquire for polymorphic functions."""
    return _AcquireType()


Acquire.__lungo_fingerprint__ = "0dabbf62c4dad8c3f81811acc80f5c789d25191897bb2621de51b5f94e54a4c9"
Acquire.__lungo_descriptor__ = staticmethod(acquire_type)


@_dataclass(frozen=True)
class Window:
    """Lean's CapDAG.Bifaci.Credit.Window."""
    remaining: int
    pending: int
    batch: int


class _WindowType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(2)

    def encode(self, w, v):
        if isinstance(v, Window):
            w.u32(0)
            lungo_py.NAT.encode(w, v.remaining)
            lungo_py.NAT.encode(w, v.pending)
            lungo_py.NAT.encode(w, v.batch)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Credit.Window")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return Window(lungo_py.NAT.decode(r), lungo_py.NAT.decode(r), lungo_py.NAT.decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Credit.Window")


def window_type() -> lungo_py.Type[Window]:
    """Describes CapDAG.Bifaci.Credit.Window for polymorphic functions."""
    return _WindowType()


Window.__lungo_fingerprint__ = "28df89763b22214ef57dfd7f1a3c0da786ff78af9768fe453cd451870749b6fe"
Window.__lungo_descriptor__ = staticmethod(window_type)


class CreditArrival:
    """Lean's CapDAG.Bifaci.Credit.Arrival: one of CreditArrivalAccepted, CreditArrivalViolation."""

    __slots__ = ()


@_dataclass(frozen=True)
class CreditArrivalAccepted(CreditArrival):
    """Lean's CapDAG.Bifaci.Credit.Arrival.accepted."""
    window: Window


@_dataclass(frozen=True)
class CreditArrivalViolation(CreditArrival):
    """Lean's CapDAG.Bifaci.Credit.Arrival.violation."""


class _CreditArrivalType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(3)

    def encode(self, w, v):
        if isinstance(v, CreditArrivalAccepted):
            w.u32(0)
            window_type().encode(w, v.window)
        elif isinstance(v, CreditArrivalViolation):
            w.u32(1)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Credit.Arrival")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return CreditArrivalAccepted(window_type().decode(r))
        if c == 1:
            return CreditArrivalViolation()
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Credit.Arrival")


def credit_arrival_type() -> lungo_py.Type[CreditArrival]:
    """Describes CapDAG.Bifaci.Credit.Arrival for polymorphic functions."""
    return _CreditArrivalType()


CreditArrival.__lungo_fingerprint__ = "940f01cf50eb8b763b9f44cc84753fcdbc65fbc0f816ab279408e74208649797"
CreditArrival.__lungo_descriptor__ = staticmethod(credit_arrival_type)


@_dataclass(frozen=True)
class Granted:
    """Lean's CapDAG.Bifaci.Credit.Granted."""
    window: Window
    grant: int


class _GrantedType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(4)

    def encode(self, w, v):
        if isinstance(v, Granted):
            w.u32(0)
            window_type().encode(w, v.window)
            lungo_py.NAT.encode(w, v.grant)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Credit.Granted")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return Granted(window_type().decode(r), lungo_py.NAT.decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Credit.Granted")


def granted_type() -> lungo_py.Type[Granted]:
    """Describes CapDAG.Bifaci.Credit.Granted for polymorphic functions."""
    return _GrantedType()


Granted.__lungo_fingerprint__ = "47f8d3e63e9aaf7c4b602f781afce57fc832e3d4d645c6adabd25c461abed233"
Granted.__lungo_descriptor__ = staticmethod(granted_type)


class FrameType:
    """Lean's CapDAG.Bifaci.Flow.FrameType: one of FrameTypeHello, FrameTypeReq, FrameTypeChunk, FrameTypeFin, FrameTypeLog, FrameTypeErr, FrameTypeHeartbeat, FrameTypeStreamStart, FrameTypeStreamEnd, FrameTypeRelayNotify, FrameTypeRelayState, FrameTypeCancel, FrameTypeCredit, FrameTypeCloseStream."""

    __slots__ = ()


@_dataclass(frozen=True)
class FrameTypeHello(FrameType):
    """Lean's CapDAG.Bifaci.Flow.FrameType.hello."""


@_dataclass(frozen=True)
class FrameTypeReq(FrameType):
    """Lean's CapDAG.Bifaci.Flow.FrameType.req."""


@_dataclass(frozen=True)
class FrameTypeChunk(FrameType):
    """Lean's CapDAG.Bifaci.Flow.FrameType.chunk."""


@_dataclass(frozen=True)
class FrameTypeFin(FrameType):
    """Lean's CapDAG.Bifaci.Flow.FrameType.fin."""


@_dataclass(frozen=True)
class FrameTypeLog(FrameType):
    """Lean's CapDAG.Bifaci.Flow.FrameType.log."""


@_dataclass(frozen=True)
class FrameTypeErr(FrameType):
    """Lean's CapDAG.Bifaci.Flow.FrameType.err."""


@_dataclass(frozen=True)
class FrameTypeHeartbeat(FrameType):
    """Lean's CapDAG.Bifaci.Flow.FrameType.heartbeat."""


@_dataclass(frozen=True)
class FrameTypeStreamStart(FrameType):
    """Lean's CapDAG.Bifaci.Flow.FrameType.streamStart."""


@_dataclass(frozen=True)
class FrameTypeStreamEnd(FrameType):
    """Lean's CapDAG.Bifaci.Flow.FrameType.streamEnd."""


@_dataclass(frozen=True)
class FrameTypeRelayNotify(FrameType):
    """Lean's CapDAG.Bifaci.Flow.FrameType.relayNotify."""


@_dataclass(frozen=True)
class FrameTypeRelayState(FrameType):
    """Lean's CapDAG.Bifaci.Flow.FrameType.relayState."""


@_dataclass(frozen=True)
class FrameTypeCancel(FrameType):
    """Lean's CapDAG.Bifaci.Flow.FrameType.cancel."""


@_dataclass(frozen=True)
class FrameTypeCredit(FrameType):
    """Lean's CapDAG.Bifaci.Flow.FrameType.credit."""


@_dataclass(frozen=True)
class FrameTypeCloseStream(FrameType):
    """Lean's CapDAG.Bifaci.Flow.FrameType.closeStream."""


class _FrameTypeType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(5)

    def encode(self, w, v):
        if isinstance(v, FrameTypeHello):
            w.u32(0)
        elif isinstance(v, FrameTypeReq):
            w.u32(1)
        elif isinstance(v, FrameTypeChunk):
            w.u32(2)
        elif isinstance(v, FrameTypeFin):
            w.u32(3)
        elif isinstance(v, FrameTypeLog):
            w.u32(4)
        elif isinstance(v, FrameTypeErr):
            w.u32(5)
        elif isinstance(v, FrameTypeHeartbeat):
            w.u32(6)
        elif isinstance(v, FrameTypeStreamStart):
            w.u32(7)
        elif isinstance(v, FrameTypeStreamEnd):
            w.u32(8)
        elif isinstance(v, FrameTypeRelayNotify):
            w.u32(9)
        elif isinstance(v, FrameTypeRelayState):
            w.u32(10)
        elif isinstance(v, FrameTypeCancel):
            w.u32(11)
        elif isinstance(v, FrameTypeCredit):
            w.u32(12)
        elif isinstance(v, FrameTypeCloseStream):
            w.u32(13)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Flow.FrameType")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return FrameTypeHello()
        if c == 1:
            return FrameTypeReq()
        if c == 2:
            return FrameTypeChunk()
        if c == 3:
            return FrameTypeFin()
        if c == 4:
            return FrameTypeLog()
        if c == 5:
            return FrameTypeErr()
        if c == 6:
            return FrameTypeHeartbeat()
        if c == 7:
            return FrameTypeStreamStart()
        if c == 8:
            return FrameTypeStreamEnd()
        if c == 9:
            return FrameTypeRelayNotify()
        if c == 10:
            return FrameTypeRelayState()
        if c == 11:
            return FrameTypeCancel()
        if c == 12:
            return FrameTypeCredit()
        if c == 13:
            return FrameTypeCloseStream()
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Flow.FrameType")


def frame_type_type() -> lungo_py.Type[FrameType]:
    """Describes CapDAG.Bifaci.Flow.FrameType for polymorphic functions."""
    return _FrameTypeType()


FrameType.__lungo_fingerprint__ = "3d6742b864aeb68cf6add586acfcd1a9663a3816d718f8d8aadc3c5e3dab3e2f"
FrameType.__lungo_descriptor__ = staticmethod(frame_type_type)


@_dataclass(frozen=True)
class Reorder:
    """Lean's CapDAG.Bifaci.Flow.Reorder."""
    expected: int
    held: _t.List[int]


class _ReorderType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(6)

    def encode(self, w, v):
        if isinstance(v, Reorder):
            w.u32(0)
            lungo_py.NAT.encode(w, v.expected)
            lungo_py.list_of(lungo_py.NAT).encode(w, v.held)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Flow.Reorder")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return Reorder(lungo_py.NAT.decode(r), lungo_py.list_of(lungo_py.NAT).decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Flow.Reorder")


def reorder_type() -> lungo_py.Type[Reorder]:
    """Describes CapDAG.Bifaci.Flow.Reorder for polymorphic functions."""
    return _ReorderType()


Reorder.__lungo_fingerprint__ = "d1e8b655f24db5e8b2348d6d41084a5c454346eb0a81fcf11b671432e72291bf"
Reorder.__lungo_descriptor__ = staticmethod(reorder_type)


class Accepted:
    """Lean's CapDAG.Bifaci.Flow.Accepted: one of AcceptedDeliver, AcceptedHold, AcceptedStale, AcceptedDuplicate, AcceptedOverflow."""

    __slots__ = ()


@_dataclass(frozen=True)
class AcceptedDeliver(Accepted):
    """Lean's CapDAG.Bifaci.Flow.Accepted.deliver."""
    flow: Reorder
    seqs: _t.List[int]


@_dataclass(frozen=True)
class AcceptedHold(Accepted):
    """Lean's CapDAG.Bifaci.Flow.Accepted.hold."""
    flow: Reorder


@_dataclass(frozen=True)
class AcceptedStale(Accepted):
    """Lean's CapDAG.Bifaci.Flow.Accepted.stale."""


@_dataclass(frozen=True)
class AcceptedDuplicate(Accepted):
    """Lean's CapDAG.Bifaci.Flow.Accepted.duplicate."""


@_dataclass(frozen=True)
class AcceptedOverflow(Accepted):
    """Lean's CapDAG.Bifaci.Flow.Accepted.overflow."""


class _AcceptedType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(7)

    def encode(self, w, v):
        if isinstance(v, AcceptedDeliver):
            w.u32(0)
            reorder_type().encode(w, v.flow)
            lungo_py.list_of(lungo_py.NAT).encode(w, v.seqs)
        elif isinstance(v, AcceptedHold):
            w.u32(1)
            reorder_type().encode(w, v.flow)
        elif isinstance(v, AcceptedStale):
            w.u32(2)
        elif isinstance(v, AcceptedDuplicate):
            w.u32(3)
        elif isinstance(v, AcceptedOverflow):
            w.u32(4)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Flow.Accepted")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return AcceptedDeliver(reorder_type().decode(r), lungo_py.list_of(lungo_py.NAT).decode(r))
        if c == 1:
            return AcceptedHold(reorder_type().decode(r))
        if c == 2:
            return AcceptedStale()
        if c == 3:
            return AcceptedDuplicate()
        if c == 4:
            return AcceptedOverflow()
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Flow.Accepted")


def accepted_type() -> lungo_py.Type[Accepted]:
    """Describes CapDAG.Bifaci.Flow.Accepted for polymorphic functions."""
    return _AcceptedType()


Accepted.__lungo_fingerprint__ = "a821d7a044f52a71dfd932fff60d2f3560ce5197658283853a56fb54aa96b69b"
Accepted.__lungo_descriptor__ = staticmethod(accepted_type)


@_dataclass(frozen=True)
class State:
    """Lean's CapDAG.Bifaci.Pools.State."""
    pools: _t.List[Pool]
    queue: _t.List[Waiter]
    next: int


class _StateType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(8)

    def encode(self, w, v):
        if isinstance(v, State):
            w.u32(0)
            lungo_py.list_of(pool_type()).encode(w, v.pools)
            lungo_py.list_of(waiter_type()).encode(w, v.queue)
            lungo_py.NAT.encode(w, v.next)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Pools.State")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return State(lungo_py.list_of(pool_type()).decode(r), lungo_py.list_of(waiter_type()).decode(r), lungo_py.NAT.decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Pools.State")


def state_type() -> lungo_py.Type[State]:
    """Describes CapDAG.Bifaci.Pools.State for polymorphic functions."""
    return _StateType()


State.__lungo_fingerprint__ = "20f7299c188d09234cda39e9cc356242e2b5bc56a09cf819d12d7f50fa24989b"
State.__lungo_descriptor__ = staticmethod(state_type)


@_dataclass(frozen=True)
class Waiter:
    """Lean's CapDAG.Bifaci.Pools.Waiter."""
    ticket: int
    chain: _t.List[str]


class _WaiterType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(9)

    def encode(self, w, v):
        if isinstance(v, Waiter):
            w.u32(0)
            lungo_py.NAT.encode(w, v.ticket)
            lungo_py.list_of(lungo_py.STRING).encode(w, v.chain)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Pools.Waiter")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return Waiter(lungo_py.NAT.decode(r), lungo_py.list_of(lungo_py.STRING).decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Pools.Waiter")


def waiter_type() -> lungo_py.Type[Waiter]:
    """Describes CapDAG.Bifaci.Pools.Waiter for polymorphic functions."""
    return _WaiterType()


Waiter.__lungo_fingerprint__ = "48d81c7e41df114e88751bb5c1f4a84c16bac3ad28d8eacba141d45f92c79da0"
Waiter.__lungo_descriptor__ = staticmethod(waiter_type)


class PoolsArrival:
    """Lean's CapDAG.Bifaci.Pools.Arrival: one of PoolsArrivalAdmitted, PoolsArrivalQueued, PoolsArrivalUnknownPool."""

    __slots__ = ()


@_dataclass(frozen=True)
class PoolsArrivalAdmitted(PoolsArrival):
    """Lean's CapDAG.Bifaci.Pools.Arrival.admitted."""
    state: State


@_dataclass(frozen=True)
class PoolsArrivalQueued(PoolsArrival):
    """Lean's CapDAG.Bifaci.Pools.Arrival.queued."""
    state: State
    ticket: int
    position: int


@_dataclass(frozen=True)
class PoolsArrivalUnknownPool(PoolsArrival):
    """Lean's CapDAG.Bifaci.Pools.Arrival.unknownPool."""
    name: str


class _PoolsArrivalType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(10)

    def encode(self, w, v):
        if isinstance(v, PoolsArrivalAdmitted):
            w.u32(0)
            state_type().encode(w, v.state)
        elif isinstance(v, PoolsArrivalQueued):
            w.u32(1)
            state_type().encode(w, v.state)
            lungo_py.NAT.encode(w, v.ticket)
            lungo_py.NAT.encode(w, v.position)
        elif isinstance(v, PoolsArrivalUnknownPool):
            w.u32(2)
            lungo_py.STRING.encode(w, v.name)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Pools.Arrival")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return PoolsArrivalAdmitted(state_type().decode(r))
        if c == 1:
            return PoolsArrivalQueued(state_type().decode(r), lungo_py.NAT.decode(r), lungo_py.NAT.decode(r))
        if c == 2:
            return PoolsArrivalUnknownPool(lungo_py.STRING.decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Pools.Arrival")


def pools_arrival_type() -> lungo_py.Type[PoolsArrival]:
    """Describes CapDAG.Bifaci.Pools.Arrival for polymorphic functions."""
    return _PoolsArrivalType()


PoolsArrival.__lungo_fingerprint__ = "6bee196c56c330c4ef348f4dd5a68558b2d19105592969cc64a0e7150bd22451"
PoolsArrival.__lungo_descriptor__ = staticmethod(pools_arrival_type)


class Patience:
    """Lean's CapDAG.Bifaci.Pools.Patience: one of PatienceUnbounded, PatienceAtMost, PatienceExhausted."""

    __slots__ = ()


@_dataclass(frozen=True)
class PatienceUnbounded(Patience):
    """Lean's CapDAG.Bifaci.Pools.Patience.unbounded."""


@_dataclass(frozen=True)
class PatienceAtMost(Patience):
    """Lean's CapDAG.Bifaci.Pools.Patience.atMost."""
    remaining: int


@_dataclass(frozen=True)
class PatienceExhausted(Patience):
    """Lean's CapDAG.Bifaci.Pools.Patience.exhausted."""


class _PatienceType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(11)

    def encode(self, w, v):
        if isinstance(v, PatienceUnbounded):
            w.u32(0)
        elif isinstance(v, PatienceAtMost):
            w.u32(1)
            lungo_py.NAT.encode(w, v.remaining)
        elif isinstance(v, PatienceExhausted):
            w.u32(2)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Pools.Patience")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return PatienceUnbounded()
        if c == 1:
            return PatienceAtMost(lungo_py.NAT.decode(r))
        if c == 2:
            return PatienceExhausted()
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Pools.Patience")


def patience_type() -> lungo_py.Type[Patience]:
    """Describes CapDAG.Bifaci.Pools.Patience for polymorphic functions."""
    return _PatienceType()


Patience.__lungo_fingerprint__ = "d32e3427e590ca6002e38cface52d020c7df74603f952bf568401f7291d5648c"
Patience.__lungo_descriptor__ = staticmethod(patience_type)


class Phase:
    """Lean's CapDAG.Bifaci.Request.Phase: one of PhaseCreated, PhaseStreaming."""

    __slots__ = ()


@_dataclass(frozen=True)
class PhaseCreated(Phase):
    """Lean's CapDAG.Bifaci.Request.Phase.created."""


@_dataclass(frozen=True)
class PhaseStreaming(Phase):
    """Lean's CapDAG.Bifaci.Request.Phase.streaming."""


class _PhaseType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(12)

    def encode(self, w, v):
        if isinstance(v, PhaseCreated):
            w.u32(0)
        elif isinstance(v, PhaseStreaming):
            w.u32(1)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Request.Phase")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return PhaseCreated()
        if c == 1:
            return PhaseStreaming()
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Request.Phase")


def phase_type() -> lungo_py.Type[Phase]:
    """Describes CapDAG.Bifaci.Request.Phase for polymorphic functions."""
    return _PhaseType()


Phase.__lungo_fingerprint__ = "7407437b58ce033618bf82341b13aaa9661d29a5a9b0f1bf1547ea0bfcfd8374"
Phase.__lungo_descriptor__ = staticmethod(phase_type)


class Emitted:
    """Lean's CapDAG.Bifaci.Request.Emitted: one of EmittedStreamStart, EmittedChunk, EmittedStreamEnd, EmittedFin, EmittedErr, EmittedOther."""

    __slots__ = ()


@_dataclass(frozen=True)
class EmittedStreamStart(Emitted):
    """Lean's CapDAG.Bifaci.Request.Emitted.streamStart."""
    stream: str


@_dataclass(frozen=True)
class EmittedChunk(Emitted):
    """Lean's CapDAG.Bifaci.Request.Emitted.chunk."""
    stream: str
    index: int


@_dataclass(frozen=True)
class EmittedStreamEnd(Emitted):
    """Lean's CapDAG.Bifaci.Request.Emitted.streamEnd."""
    stream: str
    count: _t.Optional[int]


@_dataclass(frozen=True)
class EmittedFin(Emitted):
    """Lean's CapDAG.Bifaci.Request.Emitted.fin."""


@_dataclass(frozen=True)
class EmittedErr(Emitted):
    """Lean's CapDAG.Bifaci.Request.Emitted.err."""


@_dataclass(frozen=True)
class EmittedOther(Emitted):
    """Lean's CapDAG.Bifaci.Request.Emitted.other."""


class _EmittedType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(13)

    def encode(self, w, v):
        if isinstance(v, EmittedStreamStart):
            w.u32(0)
            lungo_py.STRING.encode(w, v.stream)
        elif isinstance(v, EmittedChunk):
            w.u32(1)
            lungo_py.STRING.encode(w, v.stream)
            lungo_py.NAT.encode(w, v.index)
        elif isinstance(v, EmittedStreamEnd):
            w.u32(2)
            lungo_py.STRING.encode(w, v.stream)
            lungo_py.option(lungo_py.NAT).encode(w, v.count)
        elif isinstance(v, EmittedFin):
            w.u32(3)
        elif isinstance(v, EmittedErr):
            w.u32(4)
        elif isinstance(v, EmittedOther):
            w.u32(5)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Request.Emitted")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return EmittedStreamStart(lungo_py.STRING.decode(r))
        if c == 1:
            return EmittedChunk(lungo_py.STRING.decode(r), lungo_py.NAT.decode(r))
        if c == 2:
            return EmittedStreamEnd(lungo_py.STRING.decode(r), lungo_py.option(lungo_py.NAT).decode(r))
        if c == 3:
            return EmittedFin()
        if c == 4:
            return EmittedErr()
        if c == 5:
            return EmittedOther()
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Request.Emitted")


def emitted_type() -> lungo_py.Type[Emitted]:
    """Describes CapDAG.Bifaci.Request.Emitted for polymorphic functions."""
    return _EmittedType()


Emitted.__lungo_fingerprint__ = "97a274be14c5baecf9c50243d3651da838c5de4375366d4102cbcff85fb211c8"
Emitted.__lungo_descriptor__ = staticmethod(emitted_type)


class Violation:
    """Lean's CapDAG.Bifaci.Request.Violation: one of ViolationAfterEnd, ViolationStreamRestarted, ViolationStreamNotOpen, ViolationChunkOutOfPlace, ViolationChunkCountWrong, ViolationEndWithOpenStream."""

    __slots__ = ()


@_dataclass(frozen=True)
class ViolationAfterEnd(Violation):
    """Lean's CapDAG.Bifaci.Request.Violation.afterEnd."""


@_dataclass(frozen=True)
class ViolationStreamRestarted(Violation):
    """Lean's CapDAG.Bifaci.Request.Violation.streamRestarted."""
    stream: str


@_dataclass(frozen=True)
class ViolationStreamNotOpen(Violation):
    """Lean's CapDAG.Bifaci.Request.Violation.streamNotOpen."""
    stream: str


@_dataclass(frozen=True)
class ViolationChunkOutOfPlace(Violation):
    """Lean's CapDAG.Bifaci.Request.Violation.chunkOutOfPlace."""
    stream: str
    expected: int
    got: int


@_dataclass(frozen=True)
class ViolationChunkCountWrong(Violation):
    """Lean's CapDAG.Bifaci.Request.Violation.chunkCountWrong."""
    stream: str
    sent: int
    said: int


@_dataclass(frozen=True)
class ViolationEndWithOpenStream(Violation):
    """Lean's CapDAG.Bifaci.Request.Violation.endWithOpenStream."""
    stream: str


class _ViolationType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(14)

    def encode(self, w, v):
        if isinstance(v, ViolationAfterEnd):
            w.u32(0)
        elif isinstance(v, ViolationStreamRestarted):
            w.u32(1)
            lungo_py.STRING.encode(w, v.stream)
        elif isinstance(v, ViolationStreamNotOpen):
            w.u32(2)
            lungo_py.STRING.encode(w, v.stream)
        elif isinstance(v, ViolationChunkOutOfPlace):
            w.u32(3)
            lungo_py.STRING.encode(w, v.stream)
            lungo_py.NAT.encode(w, v.expected)
            lungo_py.NAT.encode(w, v.got)
        elif isinstance(v, ViolationChunkCountWrong):
            w.u32(4)
            lungo_py.STRING.encode(w, v.stream)
            lungo_py.NAT.encode(w, v.sent)
            lungo_py.NAT.encode(w, v.said)
        elif isinstance(v, ViolationEndWithOpenStream):
            w.u32(5)
            lungo_py.STRING.encode(w, v.stream)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Request.Violation")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return ViolationAfterEnd()
        if c == 1:
            return ViolationStreamRestarted(lungo_py.STRING.decode(r))
        if c == 2:
            return ViolationStreamNotOpen(lungo_py.STRING.decode(r))
        if c == 3:
            return ViolationChunkOutOfPlace(lungo_py.STRING.decode(r), lungo_py.NAT.decode(r), lungo_py.NAT.decode(r))
        if c == 4:
            return ViolationChunkCountWrong(lungo_py.STRING.decode(r), lungo_py.NAT.decode(r), lungo_py.NAT.decode(r))
        if c == 5:
            return ViolationEndWithOpenStream(lungo_py.STRING.decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Request.Violation")


def violation_type() -> lungo_py.Type[Violation]:
    """Describes CapDAG.Bifaci.Request.Violation for polymorphic functions."""
    return _ViolationType()


Violation.__lungo_fingerprint__ = "203fb2fc4f8ff3c79b70871b4274852e742adf97c3cc4e6631439ec66d838f09"
Violation.__lungo_descriptor__ = staticmethod(violation_type)


class Disposition:
    """Lean's CapDAG.Bifaci.Request.Disposition: one of DispositionRoute, DispositionStraggler, DispositionNoRoute."""

    __slots__ = ()


@_dataclass(frozen=True)
class DispositionRoute(Disposition):
    """Lean's CapDAG.Bifaci.Request.Disposition.route."""


@_dataclass(frozen=True)
class DispositionStraggler(Disposition):
    """Lean's CapDAG.Bifaci.Request.Disposition.straggler."""


@_dataclass(frozen=True)
class DispositionNoRoute(Disposition):
    """Lean's CapDAG.Bifaci.Request.Disposition.noRoute."""


class _DispositionType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(15)

    def encode(self, w, v):
        if isinstance(v, DispositionRoute):
            w.u32(0)
        elif isinstance(v, DispositionStraggler):
            w.u32(1)
        elif isinstance(v, DispositionNoRoute):
            w.u32(2)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Request.Disposition")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return DispositionRoute()
        if c == 1:
            return DispositionStraggler()
        if c == 2:
            return DispositionNoRoute()
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Request.Disposition")


def disposition_type() -> lungo_py.Type[Disposition]:
    """Describes CapDAG.Bifaci.Request.Disposition for polymorphic functions."""
    return _DispositionType()


Disposition.__lungo_fingerprint__ = "540307dfb6e509ccde4b894c69566edd1f3f9c3223b9325e97ee91b20d0fb82f"
Disposition.__lungo_descriptor__ = staticmethod(disposition_type)


class Terminal:
    """Lean's CapDAG.Bifaci.Request.Terminal: one of TerminalFinished, TerminalFailed, TerminalCancelled, TerminalMasterDied."""

    __slots__ = ()


@_dataclass(frozen=True)
class TerminalFinished(Terminal):
    """Lean's CapDAG.Bifaci.Request.Terminal.finished."""


@_dataclass(frozen=True)
class TerminalFailed(Terminal):
    """Lean's CapDAG.Bifaci.Request.Terminal.failed."""


@_dataclass(frozen=True)
class TerminalCancelled(Terminal):
    """Lean's CapDAG.Bifaci.Request.Terminal.cancelled."""


@_dataclass(frozen=True)
class TerminalMasterDied(Terminal):
    """Lean's CapDAG.Bifaci.Request.Terminal.masterDied."""


class _TerminalType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(16)

    def encode(self, w, v):
        if isinstance(v, TerminalFinished):
            w.u32(0)
        elif isinstance(v, TerminalFailed):
            w.u32(1)
        elif isinstance(v, TerminalCancelled):
            w.u32(2)
        elif isinstance(v, TerminalMasterDied):
            w.u32(3)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Request.Terminal")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return TerminalFinished()
        if c == 1:
            return TerminalFailed()
        if c == 2:
            return TerminalCancelled()
        if c == 3:
            return TerminalMasterDied()
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Request.Terminal")


def terminal_type() -> lungo_py.Type[Terminal]:
    """Describes CapDAG.Bifaci.Request.Terminal for polymorphic functions."""
    return _TerminalType()


Terminal.__lungo_fingerprint__ = "3597c3196cef5e4468b5449eb0da09af414bb8c3aa40d92b027089f6ae81c870"
Terminal.__lungo_descriptor__ = staticmethod(terminal_type)


class Write:
    """Lean's CapDAG.Bifaci.Request.Write: one of WriteSend, WriteSuppress."""

    __slots__ = ()


@_dataclass(frozen=True)
class WriteSend(Write):
    """Lean's CapDAG.Bifaci.Request.Write.send."""
    ends: bool


@_dataclass(frozen=True)
class WriteSuppress(Write):
    """Lean's CapDAG.Bifaci.Request.Write.suppress."""


class _WriteType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(17)

    def encode(self, w, v):
        if isinstance(v, WriteSend):
            w.u32(0)
            lungo_py.BOOL.encode(w, v.ends)
        elif isinstance(v, WriteSuppress):
            w.u32(1)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Request.Write")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return WriteSend(lungo_py.BOOL.decode(r))
        if c == 1:
            return WriteSuppress()
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Request.Write")


def write_type() -> lungo_py.Type[Write]:
    """Describes CapDAG.Bifaci.Request.Write for polymorphic functions."""
    return _WriteType()


Write.__lungo_fingerprint__ = "9ae21282903c8131c25ca1cc527e51fd1fa5137aa77c9ef4f3d091e9415a109a"
Write.__lungo_descriptor__ = staticmethod(write_type)


@_dataclass(frozen=True)
class WfCap:
    """Lean's CapDAG.Exec.WfCap."""
    input: _ext_0.Wf
    output: _ext_0.Wf
    other: _ext_0.Wf
    effect: Effect


class _WfCapType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(18)

    def encode(self, w, v):
        if isinstance(v, WfCap):
            w.u32(0)
            _ext_type_21().encode(w, v.input)
            _ext_type_21().encode(w, v.output)
            _ext_type_21().encode(w, v.other)
            effect_type().encode(w, v.effect)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Exec.WfCap")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return WfCap(_ext_type_21().decode(r), _ext_type_21().decode(r), _ext_type_21().decode(r), effect_type().decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Exec.WfCap")


def wf_cap_type() -> lungo_py.Type[WfCap]:
    """Describes CapDAG.Exec.WfCap for polymorphic functions."""
    return _WfCapType()


WfCap.__lungo_fingerprint__ = "2b8d6466d218f4ae6bc98d95bba55d98f21cac4a49446ae170993773cefdb830"
WfCap.__lungo_descriptor__ = staticmethod(wf_cap_type)


class Effect:
    """Lean's CapDAG.Effect: one of EffectUnspecified, EffectDeclared, EffectNone_, EffectPatch."""

    __slots__ = ()


@_dataclass(frozen=True)
class EffectUnspecified(Effect):
    """Lean's CapDAG.Effect.unspecified."""


@_dataclass(frozen=True)
class EffectDeclared(Effect):
    """Lean's CapDAG.Effect.declared."""


@_dataclass(frozen=True)
class EffectNone_(Effect):
    """Lean's CapDAG.Effect.none."""


@_dataclass(frozen=True)
class EffectPatch(Effect):
    """Lean's CapDAG.Effect.patch."""


class _EffectType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(19)

    def encode(self, w, v):
        if isinstance(v, EffectUnspecified):
            w.u32(0)
        elif isinstance(v, EffectDeclared):
            w.u32(1)
        elif isinstance(v, EffectNone_):
            w.u32(2)
        elif isinstance(v, EffectPatch):
            w.u32(3)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Effect")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return EffectUnspecified()
        if c == 1:
            return EffectDeclared()
        if c == 2:
            return EffectNone_()
        if c == 3:
            return EffectPatch()
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Effect")


def effect_type() -> lungo_py.Type[Effect]:
    """Describes CapDAG.Effect for polymorphic functions."""
    return _EffectType()


Effect.__lungo_fingerprint__ = "38c7bd3c0527cda156713cd441c9b6b92bd5df8a39108fa101449a789abcb477"
Effect.__lungo_descriptor__ = staticmethod(effect_type)


@_dataclass(frozen=True)
class WfQuery:
    """Lean's CapDAG.Exec.WfQuery."""
    input: WfAsk
    output: WfAsk
    tags: _ext_0.Wf
    effect: Effect


class _WfQueryType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(20)

    def encode(self, w, v):
        if isinstance(v, WfQuery):
            w.u32(0)
            wf_ask_type().encode(w, v.input)
            wf_ask_type().encode(w, v.output)
            _ext_type_21().encode(w, v.tags)
            effect_type().encode(w, v.effect)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Exec.WfQuery")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return WfQuery(wf_ask_type().decode(r), wf_ask_type().decode(r), _ext_type_21().decode(r), effect_type().decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Exec.WfQuery")


def wf_query_type() -> lungo_py.Type[WfQuery]:
    """Describes CapDAG.Exec.WfQuery for polymorphic functions."""
    return _WfQueryType()


WfQuery.__lungo_fingerprint__ = "e734861d70e3177f6563c4492990bb65131f0450b8dfc62071eb61b6c5f08b8e"
WfQuery.__lungo_descriptor__ = staticmethod(wf_query_type)


class _ExtType21(lungo_py.Type):
    """Lean's TaggedUrn.Exec.Wf, provided by tagged_urn._formal."""

    def __init__(self):
        self._provided = _ext_0.Wf.__lungo_descriptor__()

    def expr(self):
        return lungo_py.inductive_expr(21)

    def encode(self, w, v):
        self._provided.encode(w, v)

    def decode(self, r):
        return self._provided.decode(r)


def _ext_type_21():
    return _ExtType21()


class Grade:
    """Lean's CapDAG.Grade: one of GradeExact, GradeGuaranteed, GradePossible, GradeNone_."""

    __slots__ = ()


@_dataclass(frozen=True)
class GradeExact(Grade):
    """Lean's CapDAG.Grade.exact."""


@_dataclass(frozen=True)
class GradeGuaranteed(Grade):
    """Lean's CapDAG.Grade.guaranteed."""


@_dataclass(frozen=True)
class GradePossible(Grade):
    """Lean's CapDAG.Grade.possible."""


@_dataclass(frozen=True)
class GradeNone_(Grade):
    """Lean's CapDAG.Grade.none."""


class _GradeType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(22)

    def encode(self, w, v):
        if isinstance(v, GradeExact):
            w.u32(0)
        elif isinstance(v, GradeGuaranteed):
            w.u32(1)
        elif isinstance(v, GradePossible):
            w.u32(2)
        elif isinstance(v, GradeNone_):
            w.u32(3)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Grade")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return GradeExact()
        if c == 1:
            return GradeGuaranteed()
        if c == 2:
            return GradePossible()
        if c == 3:
            return GradeNone_()
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Grade")


def grade_type() -> lungo_py.Type[Grade]:
    """Describes CapDAG.Grade for polymorphic functions."""
    return _GradeType()


Grade.__lungo_fingerprint__ = "0a2a20a14d9ecca6121343df2d8a7f2478b3e837710ed522ed385d35efdf46f2"
Grade.__lungo_descriptor__ = staticmethod(grade_type)


class Constraint:
    """Lean's TaggedUrn.Constraint: one of ConstraintMissing, ConstraintUnconstrained, ConstraintOptionalNot, ConstraintPresent, ConstraintPresentNot, ConstraintExact, ConstraintAbsent."""

    __slots__ = ()


@_dataclass(frozen=True)
class ConstraintMissing(Constraint):
    """Lean's TaggedUrn.Constraint.missing."""


@_dataclass(frozen=True)
class ConstraintUnconstrained(Constraint):
    """Lean's TaggedUrn.Constraint.unconstrained."""


@_dataclass(frozen=True)
class ConstraintOptionalNot(Constraint):
    """Lean's TaggedUrn.Constraint.optionalNot."""
    value: str


@_dataclass(frozen=True)
class ConstraintPresent(Constraint):
    """Lean's TaggedUrn.Constraint.present."""


@_dataclass(frozen=True)
class ConstraintPresentNot(Constraint):
    """Lean's TaggedUrn.Constraint.presentNot."""
    value: str


@_dataclass(frozen=True)
class ConstraintExact(Constraint):
    """Lean's TaggedUrn.Constraint.exact."""
    value: str


@_dataclass(frozen=True)
class ConstraintAbsent(Constraint):
    """Lean's TaggedUrn.Constraint.absent."""


class _ConstraintType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(23)

    def encode(self, w, v):
        if isinstance(v, ConstraintMissing):
            w.u32(0)
        elif isinstance(v, ConstraintUnconstrained):
            w.u32(1)
        elif isinstance(v, ConstraintOptionalNot):
            w.u32(2)
            lungo_py.STRING.encode(w, v.value)
        elif isinstance(v, ConstraintPresent):
            w.u32(3)
        elif isinstance(v, ConstraintPresentNot):
            w.u32(4)
            lungo_py.STRING.encode(w, v.value)
        elif isinstance(v, ConstraintExact):
            w.u32(5)
            lungo_py.STRING.encode(w, v.value)
        elif isinstance(v, ConstraintAbsent):
            w.u32(6)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a TaggedUrn.Constraint")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return ConstraintMissing()
        if c == 1:
            return ConstraintUnconstrained()
        if c == 2:
            return ConstraintOptionalNot(lungo_py.STRING.decode(r))
        if c == 3:
            return ConstraintPresent()
        if c == 4:
            return ConstraintPresentNot(lungo_py.STRING.decode(r))
        if c == 5:
            return ConstraintExact(lungo_py.STRING.decode(r))
        if c == 6:
            return ConstraintAbsent()
        raise lungo_py.MalformedError(f"constructor index {c} of TaggedUrn.Constraint")


def constraint_type() -> lungo_py.Type[Constraint]:
    """Describes TaggedUrn.Constraint for polymorphic functions."""
    return _ConstraintType()


Constraint.__lungo_fingerprint__ = "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7"
Constraint.__lungo_descriptor__ = staticmethod(constraint_type)


@_dataclass(frozen=True)
class Pool:
    """Lean's CapDAG.Bifaci.Pools.Pool."""
    name: str
    capacity: int
    active: int


class _PoolType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(24)

    def encode(self, w, v):
        if isinstance(v, Pool):
            w.u32(0)
            lungo_py.STRING.encode(w, v.name)
            lungo_py.NAT.encode(w, v.capacity)
            lungo_py.NAT.encode(w, v.active)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Bifaci.Pools.Pool")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return Pool(lungo_py.STRING.decode(r), lungo_py.NAT.decode(r), lungo_py.NAT.decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Bifaci.Pools.Pool")


def pool_type() -> lungo_py.Type[Pool]:
    """Describes CapDAG.Bifaci.Pools.Pool for polymorphic functions."""
    return _PoolType()


Pool.__lungo_fingerprint__ = "60bca9d670886c7830c76779ad692b4fbb6e4e30c0ce6b3e9d5a91a9b5b7b1e6"
Pool.__lungo_descriptor__ = staticmethod(pool_type)


class WfAsk:
    """Lean's CapDAG.Exec.WfAsk: one of WfAskUnknown, WfAskWithin, WfAskCovers, WfAskSame."""

    __slots__ = ()


@_dataclass(frozen=True)
class WfAskUnknown(WfAsk):
    """Lean's CapDAG.Exec.WfAsk.unknown."""


@_dataclass(frozen=True)
class WfAskWithin(WfAsk):
    """Lean's CapDAG.Exec.WfAsk.within."""
    u: _ext_0.Wf


@_dataclass(frozen=True)
class WfAskCovers(WfAsk):
    """Lean's CapDAG.Exec.WfAsk.covers."""
    u: _ext_0.Wf


@_dataclass(frozen=True)
class WfAskSame(WfAsk):
    """Lean's CapDAG.Exec.WfAsk.same."""
    u: _ext_0.Wf


class _WfAskType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(25)

    def encode(self, w, v):
        if isinstance(v, WfAskUnknown):
            w.u32(0)
        elif isinstance(v, WfAskWithin):
            w.u32(1)
            _ext_type_21().encode(w, v.u)
        elif isinstance(v, WfAskCovers):
            w.u32(2)
            _ext_type_21().encode(w, v.u)
        elif isinstance(v, WfAskSame):
            w.u32(3)
            _ext_type_21().encode(w, v.u)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Exec.WfAsk")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return WfAskUnknown()
        if c == 1:
            return WfAskWithin(_ext_type_21().decode(r))
        if c == 2:
            return WfAskCovers(_ext_type_21().decode(r))
        if c == 3:
            return WfAskSame(_ext_type_21().decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Exec.WfAsk")


def wf_ask_type() -> lungo_py.Type[WfAsk]:
    """Describes CapDAG.Exec.WfAsk for polymorphic functions."""
    return _WfAskType()


WfAsk.__lungo_fingerprint__ = "d286477c7abc4e6bc6ee2d06889372b71a5bb06605b592ebabb6ad3eaf71b952"
WfAsk.__lungo_descriptor__ = staticmethod(wf_ask_type)


def acquire(g: Gate, n: int) -> Acquire:
    """Lean's CapDAG.Bifaci.Credit.Gate.acquire : CapDAG.Bifaci.Credit.Gate → Nat → CapDAG.Bifaci.Credit.Acquire"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dacquire", (), ((gate_type(), g), (lungo_py.NAT, n),), lungo_py.value(acquire_type()))


def close(g: Gate, reason: str) -> Gate:
    """Lean's CapDAG.Bifaci.Credit.Gate.close : CapDAG.Bifaci.Credit.Gate → String → CapDAG.Bifaci.Credit.Gate"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dclose", (), ((gate_type(), g), (lungo_py.STRING, reason),), lungo_py.value(gate_type()))


def grant(g: Gate, n: int) -> Gate:
    """Lean's CapDAG.Bifaci.Credit.Gate.grant : CapDAG.Bifaci.Credit.Gate → Nat → CapDAG.Bifaci.Credit.Gate"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dgrant", (), ((gate_type(), g), (lungo_py.NAT, n),), lungo_py.value(gate_type()))


def gate_opened(window: int) -> Gate:
    """Lean's CapDAG.Bifaci.Credit.Gate.opened : Nat → CapDAG.Bifaci.Credit.Gate"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dCredit_dGate_dopened", (), ((lungo_py.NAT, window),), lungo_py.value(gate_type()))


def window_arrive(w_: Window) -> CreditArrival:
    """Lean's CapDAG.Bifaci.Credit.Window.arrive : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Arrival"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_darrive", (), ((window_type(), w_),), lungo_py.value(credit_arrival_type()))


def consume(w_: Window) -> Granted:
    """Lean's CapDAG.Bifaci.Credit.Window.consume : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dconsume", (), ((window_type(), w_),), lungo_py.value(granted_type()))


def continued(w_: Window) -> Granted:
    """Lean's CapDAG.Bifaci.Credit.Window.continued : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dcontinued", (), ((window_type(), w_),), lungo_py.value(granted_type()))


def flush(w_: Window) -> Granted:
    """Lean's CapDAG.Bifaci.Credit.Window.flush : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dflush", (), ((window_type(), w_),), lungo_py.value(granted_type()))


def window_opened(window: int) -> Window:
    """Lean's CapDAG.Bifaci.Credit.Window.opened : Nat → CapDAG.Bifaci.Credit.Window"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dCredit_dWindow_dopened", (), ((lungo_py.NAT, window),), lungo_py.value(window_type()))


def grant_target(streams: _t.List[_t.Optional[str]], named: _t.Optional[str]) -> _t.Optional[lungo_py.Some[_t.Optional[str]]]:
    """Lean's CapDAG.Bifaci.Credit.grantTarget : List (Option String) → Option String → Option (Option String)"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dCredit_dgrantTarget", (), ((lungo_py.list_of(lungo_py.option(lungo_py.STRING)), streams), (lungo_py.option(lungo_py.STRING), named),), lungo_py.value(lungo_py.option(lungo_py.option(lungo_py.STRING))))


def negotiate(ours: int, theirs: int) -> _t.Optional[int]:
    """Lean's CapDAG.Bifaci.Credit.negotiate : Nat → Nat → Option Nat"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dCredit_dnegotiate", (), ((lungo_py.NAT, ours), (lungo_py.NAT, theirs),), lungo_py.value(lungo_py.option(lungo_py.NAT)))


def code(a: FrameType) -> int:
    """Lean's CapDAG.Bifaci.Flow.FrameType.code : CapDAG.Bifaci.Flow.FrameType → Nat"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_dcode", (), ((frame_type_type(), a),), lungo_py.value(lungo_py.NAT))


def is_flow(a: FrameType) -> bool:
    """Lean's CapDAG.Bifaci.Flow.FrameType.isFlow : CapDAG.Bifaci.Flow.FrameType → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_disFlow", (), ((frame_type_type(), a),), lungo_py.value(lungo_py.BOOL))


def is_terminal(a: FrameType) -> bool:
    """Lean's CapDAG.Bifaci.Flow.FrameType.isTerminal : CapDAG.Bifaci.Flow.FrameType → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_disTerminal", (), ((frame_type_type(), a),), lungo_py.value(lungo_py.BOOL))


def of_code(a: int) -> _t.Optional[FrameType]:
    """Lean's CapDAG.Bifaci.Flow.FrameType.ofCode : Nat → Option CapDAG.Bifaci.Flow.FrameType"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dFlow_dFrameType_dofCode", (), ((lungo_py.NAT, a),), lungo_py.value(lungo_py.option(frame_type_type())))


def accept(r_: Reorder, seq: int, limit: int) -> Accepted:
    """Lean's CapDAG.Bifaci.Flow.Reorder.accept : CapDAG.Bifaci.Flow.Reorder → Nat → Nat → CapDAG.Bifaci.Flow.Accepted"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dFlow_dReorder_daccept", (), ((reorder_type(), r_), (lungo_py.NAT, seq), (lungo_py.NAT, limit),), lungo_py.value(accepted_type()))


def start() -> Reorder:
    """Lean's CapDAG.Bifaci.Flow.Reorder.start : CapDAG.Bifaci.Flow.Reorder"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dFlow_dReorder_dstart", (), (), lungo_py.value(reorder_type()))


def admit(s: State, ticket: int) -> _t.Optional[State]:
    """Lean's CapDAG.Bifaci.Pools.State.admit : CapDAG.Bifaci.Pools.State → Nat → Option CapDAG.Bifaci.Pools.State"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dadmit", (), ((state_type(), s), (lungo_py.NAT, ticket),), lungo_py.value(lungo_py.option(state_type())))


def admit_next(s: State) -> _t.Optional[_t.Tuple[Waiter, State]]:
    """Lean's CapDAG.Bifaci.Pools.State.admitNext : CapDAG.Bifaci.Pools.State → Option (CapDAG.Bifaci.Pools.Waiter × CapDAG.Bifaci.Pools.State)"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dadmitNext", (), ((state_type(), s),), lungo_py.value(lungo_py.option(lungo_py.pair(waiter_type(), state_type()))))


def state_arrive(s: State, chain: _t.List[str]) -> PoolsArrival:
    """Lean's CapDAG.Bifaci.Pools.State.arrive : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.Arrival"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_darrive", (), ((state_type(), s), (lungo_py.list_of(lungo_py.STRING), chain),), lungo_py.value(pools_arrival_type()))


def empty() -> State:
    """Lean's CapDAG.Bifaci.Pools.State.empty : CapDAG.Bifaci.Pools.State"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dempty", (), (), lungo_py.value(state_type()))


def has_room(s: State, chain: _t.List[str]) -> bool:
    """Lean's CapDAG.Bifaci.Pools.State.hasRoom : CapDAG.Bifaci.Pools.State → List String → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dhasRoom", (), ((state_type(), s), (lungo_py.list_of(lungo_py.STRING), chain),), lungo_py.value(lungo_py.BOOL))


def held_back(s: State, name: str) -> int:
    """Lean's CapDAG.Bifaci.Pools.State.heldBack : CapDAG.Bifaci.Pools.State → String → Nat"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dheldBack", (), ((state_type(), s), (lungo_py.STRING, name),), lungo_py.value(lungo_py.NAT))


def join(s: State, chain: _t.List[str]) -> PoolsArrival:
    """Lean's CapDAG.Bifaci.Pools.State.join : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.Arrival"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_djoin", (), ((state_type(), s), (lungo_py.list_of(lungo_py.STRING), chain),), lungo_py.value(pools_arrival_type()))


def leave(s: State, ticket: int) -> State:
    """Lean's CapDAG.Bifaci.Pools.State.leave : CapDAG.Bifaci.Pools.State → Nat → CapDAG.Bifaci.Pools.State"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dleave", (), ((state_type(), s), (lungo_py.NAT, ticket),), lungo_py.value(state_type()))


def position(s: State, ticket: int) -> int:
    """Lean's CapDAG.Bifaci.Pools.State.position : CapDAG.Bifaci.Pools.State → Nat → Nat"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dposition", (), ((state_type(), s), (lungo_py.NAT, ticket),), lungo_py.value(lungo_py.NAT))


def release(s: State, chain: _t.List[str]) -> State:
    """Lean's CapDAG.Bifaci.Pools.State.release : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.State"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_drelease", (), ((state_type(), s), (lungo_py.list_of(lungo_py.STRING), chain),), lungo_py.value(state_type()))


def set_capacity(s: State, name: str, capacity: int) -> State:
    """Lean's CapDAG.Bifaci.Pools.State.setCapacity : CapDAG.Bifaci.Pools.State → String → Nat → CapDAG.Bifaci.Pools.State"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_dState_dsetCapacity", (), ((state_type(), s), (lungo_py.STRING, name), (lungo_py.NAT, capacity),), lungo_py.value(state_type()))


def advertised(running: bool, pool: str, configured: int, available: _t.Optional[int]) -> int:
    """Lean's CapDAG.Bifaci.Pools.advertised : Bool → String → Nat → Option Nat → Nat"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_dadvertised", (), ((lungo_py.BOOL, running), (lungo_py.STRING, pool), (lungo_py.NAT, configured), (lungo_py.option(lungo_py.NAT), available),), lungo_py.value(lungo_py.NAT))


def chain(cap: str, shared: _t.List[_t.Tuple[str, _t.List[str]]]) -> _t.List[str]:
    """Lean's CapDAG.Bifaci.Pools.chain : String → List (String × List String) → List String"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_dchain", (), ((lungo_py.STRING, cap), (lungo_py.list_of(lungo_py.pair(lungo_py.STRING, lungo_py.list_of(lungo_py.STRING))), shared),), lungo_py.value(lungo_py.list_of(lungo_py.STRING)))


def effective(configured: int, available: _t.Optional[int]) -> int:
    """Lean's CapDAG.Bifaci.Pools.effective : Nat → Option Nat → Nat"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_deffective", (), ((lungo_py.NAT, configured), (lungo_py.option(lungo_py.NAT), available),), lungo_py.value(lungo_py.NAT))


def patience(unavailable_for: _t.Optional[int], grace: int) -> Patience:
    """Lean's CapDAG.Bifaci.Pools.patience : Option Nat → Nat → CapDAG.Bifaci.Pools.Patience"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dPools_dpatience", (), ((lungo_py.option(lungo_py.NAT), unavailable_for), (lungo_py.NAT, grace),), lungo_py.value(patience_type()))


def after(p: Phase, frame: FrameType) -> Phase:
    """Lean's CapDAG.Bifaci.Request.Phase.after : CapDAG.Bifaci.Request.Phase → CapDAG.Bifaci.Flow.FrameType → CapDAG.Bifaci.Request.Phase"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dRequest_dPhase_dafter", (), ((phase_type(), p), (frame_type_type(), frame),), lungo_py.value(phase_type()))


def check(frames: _t.List[Emitted]) -> _t.Optional[Violation]:
    """Lean's CapDAG.Bifaci.Request.check : List CapDAG.Bifaci.Request.Emitted → Option CapDAG.Bifaci.Request.Violation"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dRequest_dcheck", (), ((lungo_py.list_of(emitted_type()), frames),), lungo_py.value(lungo_py.option(violation_type())))


def dispose(live: bool, ended_lately: bool) -> Disposition:
    """Lean's CapDAG.Bifaci.Request.dispose : Bool → Bool → CapDAG.Bifaci.Request.Disposition"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dRequest_ddispose", (), ((lungo_py.BOOL, live), (lungo_py.BOOL, ended_lately),), lungo_py.value(disposition_type()))


def ledger(remaining: int, frame: FrameType, granted: int) -> int:
    """Lean's CapDAG.Bifaci.Request.ledger : Int → CapDAG.Bifaci.Flow.FrameType → Nat → Int"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dRequest_dledger", (), ((lungo_py.INT, remaining), (frame_type_type(), frame), (lungo_py.NAT, granted),), lungo_py.value(lungo_py.INT))


def terminal_of(a: FrameType) -> _t.Optional[Terminal]:
    """Lean's CapDAG.Bifaci.Request.terminalOf : CapDAG.Bifaci.Flow.FrameType → Option CapDAG.Bifaci.Request.Terminal"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dRequest_dterminalOf", (), ((frame_type_type(), a),), lungo_py.value(lungo_py.option(terminal_type())))


def write(over: bool, frame: FrameType) -> Write:
    """Lean's CapDAG.Bifaci.Request.write : Bool → CapDAG.Bifaci.Flow.FrameType → CapDAG.Bifaci.Request.Write"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dBifaci_dRequest_dwrite", (), ((lungo_py.BOOL, over), (frame_type_type(), frame),), lungo_py.value(write_type()))


def accepts(pattern: WfCap, cap: WfCap) -> bool:
    """Lean's CapDAG.Exec.accepts : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_daccepts", (), ((wf_cap_type(), pattern), (wf_cap_type(), cap),), lungo_py.value(lungo_py.BOOL))


def comparable(a: WfCap, b: WfCap) -> bool:
    """Lean's CapDAG.Exec.comparable : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dcomparable", (), ((wf_cap_type(), a), (wf_cap_type(), b),), lungo_py.value(lungo_py.BOOL))


def dispatch(candidate: WfCap, request: WfCap) -> bool:
    """Lean's CapDAG.Exec.dispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_ddispatch", (), ((wf_cap_type(), candidate), (wf_cap_type(), request),), lungo_py.value(lungo_py.BOOL))


def effect_ok(candidate: Effect, request: Effect) -> bool:
    """Lean's CapDAG.Exec.effectOk : CapDAG.Effect → CapDAG.Effect → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_deffectOk", (), ((effect_type(), candidate), (effect_type(), request),), lungo_py.value(lungo_py.BOOL))


def equivalent(a: WfCap, b: WfCap) -> bool:
    """Lean's CapDAG.Exec.equivalent : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dequivalent", (), ((wf_cap_type(), a), (wf_cap_type(), b),), lungo_py.value(lungo_py.BOOL))


def flows(a: WfCap, b: WfCap) -> bool:
    """Lean's CapDAG.Exec.flows : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dflows", (), ((wf_cap_type(), a), (wf_cap_type(), b),), lungo_py.value(lungo_py.BOOL))


def may_dispatch(candidate: WfCap, request: WfCap) -> bool:
    """Lean's CapDAG.Exec.mayDispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dmayDispatch", (), ((wf_cap_type(), candidate), (wf_cap_type(), request),), lungo_py.value(lungo_py.BOOL))


def may_flow(a: WfCap, b: WfCap) -> bool:
    """Lean's CapDAG.Exec.mayFlow : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dmayFlow", (), ((wf_cap_type(), a), (wf_cap_type(), b),), lungo_py.value(lungo_py.BOOL))


def query_admits(q: WfQuery, c_: WfCap) -> bool:
    """Lean's CapDAG.Exec.queryAdmits : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryAdmits", (), ((wf_query_type(), q), (wf_cap_type(), c_),), lungo_py.value(lungo_py.BOOL))


def query_between(input: _ext_0.Wf, output: _ext_0.Wf, tags: _ext_0.Wf) -> WfQuery:
    """Lean's CapDAG.Exec.queryBetween : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryBetween", (), ((_ext_type_21(), input), (_ext_type_21(), output), (_ext_type_21(), tags),), lungo_py.value(wf_query_type()))


def query_consuming(input: _ext_0.Wf, tags: _ext_0.Wf) -> WfQuery:
    """Lean's CapDAG.Exec.queryConsuming : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryConsuming", (), ((_ext_type_21(), input), (_ext_type_21(), tags),), lungo_py.value(wf_query_type()))


def query_grade(q: WfQuery, c_: WfCap) -> Grade:
    """Lean's CapDAG.Exec.queryGrade : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → CapDAG.Grade"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryGrade", (), ((wf_query_type(), q), (wf_cap_type(), c_),), lungo_py.value(grade_type()))


def query_may_admit(q: WfQuery, c_: WfCap) -> bool:
    """Lean's CapDAG.Exec.queryMayAdmit : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryMayAdmit", (), ((wf_query_type(), q), (wf_cap_type(), c_),), lungo_py.value(lungo_py.BOOL))


def query_of_pattern(p: WfCap) -> WfQuery:
    """Lean's CapDAG.Exec.queryOfPattern : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryOfPattern", (), ((wf_cap_type(), p),), lungo_py.value(wf_query_type()))


def query_of_request(r_: WfCap) -> WfQuery:
    """Lean's CapDAG.Exec.queryOfRequest : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryOfRequest", (), ((wf_cap_type(), r_),), lungo_py.value(wf_query_type()))


def query_producing(output: _ext_0.Wf, tags: _ext_0.Wf) -> WfQuery:
    """Lean's CapDAG.Exec.queryProducing : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryProducing", (), ((_ext_type_21(), output), (_ext_type_21(), tags),), lungo_py.value(wf_query_type()))


def ranking_key(candidate: WfCap, request: WfCap) -> _t.Tuple[int, int]:
    """Lean's CapDAG.Exec.rankingKey : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Nat × Nat"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_drankingKey", (), ((wf_cap_type(), candidate), (wf_cap_type(), request),), lungo_py.value(lungo_py.pair(lungo_py.NAT, lungo_py.NAT)))


def select(candidates: _t.List[WfCap], request: WfCap) -> _t.Optional[WfCap]:
    """Lean's CapDAG.Exec.select : List CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Option CapDAG.Exec.WfCap"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dselect", (), ((lungo_py.list_of(wf_cap_type()), candidates), (wf_cap_type(), request),), lungo_py.value(lungo_py.option(wf_cap_type())))


def specificity(c_: WfCap) -> int:
    """Lean's CapDAG.Exec.specificity : CapDAG.Exec.WfCap → Nat"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dspecificity", (), ((wf_cap_type(), c_),), lungo_py.value(lungo_py.NAT))


def make(scheme: str, tags: _t.List[_t.Tuple[str, Constraint]]) -> _t.Optional[_ext_0.Wf]:
    """Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf"""
    return _program.invoke("capdagFormal__call_l_TaggedUrn_dExec_dmake", (), ((lungo_py.STRING, scheme), (lungo_py.list_of(lungo_py.pair(lungo_py.STRING, constraint_type())), tags),), lungo_py.value(lungo_py.option(_ext_type_21())))
