"""The Lean program capdagFormal (generated by lungo 1.74.3213 from Lean 4.34.1). Do not edit."""

from __future__ import annotations

import os as _os
import sys as _sys
import typing as _t
from dataclasses import dataclass as _dataclass

import lungo_py
import tagged_urn._formal as _ext_0

if lungo_py.__version__ != "1.74.3213":
    raise ImportError(f"this package needs lungo_py 1.74.3213, not {lungo_py.__version__}")


def _library() -> str:
    name = {"win32": "capdagFormal_lean.dll", "darwin": "libcapdagFormal_lean.dylib"}.get(_sys.platform, "libcapdagFormal_lean.so")
    for directory in __path__:
        path = _os.path.join(directory, name)
        if _os.path.isfile(path):
            return path
    raise ImportError(f"the compiled program {name} is in none of {list(__path__)}: install the package with pip")


_program = lungo_py.Program(_library(), "capdagFormal__types")

if _ext_0.Wf.__lungo_fingerprint__ != "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785":
    raise ImportError("TaggedUrn.Exec.Wf of tagged_urn._formal has another layout than the one this program was generated for: regenerate both from the same Lean definition")


@_dataclass(frozen=True)
class WfCap:
    """Lean's CapDAG.Exec.WfCap."""
    input: _ext_0.Wf
    output: _ext_0.Wf
    other: _ext_0.Wf
    effect: Effect


class _WfCapType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(0)

    def encode(self, w, v):
        if isinstance(v, WfCap):
            w.u32(0)
            _ext_type_3().encode(w, v.input)
            _ext_type_3().encode(w, v.output)
            _ext_type_3().encode(w, v.other)
            effect_type().encode(w, v.effect)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Exec.WfCap")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return WfCap(_ext_type_3().decode(r), _ext_type_3().decode(r), _ext_type_3().decode(r), effect_type().decode(r))
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Exec.WfCap")


def wf_cap_type() -> lungo_py.Type[WfCap]:
    """Describes CapDAG.Exec.WfCap for polymorphic functions."""
    return _WfCapType()


WfCap.__lungo_fingerprint__ = "2b8d6466d218f4ae6bc98d95bba55d98f21cac4a49446ae170993773cefdb830"
WfCap.__lungo_descriptor__ = staticmethod(wf_cap_type)


class Effect:
    """Lean's CapDAG.Effect: one of EffectUnspecified, EffectDeclared, EffectNone_, EffectPatch."""

    __slots__ = ()


@_dataclass(frozen=True)
class EffectUnspecified(Effect):
    """Lean's CapDAG.Effect.unspecified."""


@_dataclass(frozen=True)
class EffectDeclared(Effect):
    """Lean's CapDAG.Effect.declared."""


@_dataclass(frozen=True)
class EffectNone_(Effect):
    """Lean's CapDAG.Effect.none."""


@_dataclass(frozen=True)
class EffectPatch(Effect):
    """Lean's CapDAG.Effect.patch."""


class _EffectType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(1)

    def encode(self, w, v):
        if isinstance(v, EffectUnspecified):
            w.u32(0)
        elif isinstance(v, EffectDeclared):
            w.u32(1)
        elif isinstance(v, EffectNone_):
            w.u32(2)
        elif isinstance(v, EffectPatch):
            w.u32(3)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a CapDAG.Effect")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return EffectUnspecified()
        if c == 1:
            return EffectDeclared()
        if c == 2:
            return EffectNone_()
        if c == 3:
            return EffectPatch()
        raise lungo_py.MalformedError(f"constructor index {c} of CapDAG.Effect")


def effect_type() -> lungo_py.Type[Effect]:
    """Describes CapDAG.Effect for polymorphic functions."""
    return _EffectType()


Effect.__lungo_fingerprint__ = "38c7bd3c0527cda156713cd441c9b6b92bd5df8a39108fa101449a789abcb477"
Effect.__lungo_descriptor__ = staticmethod(effect_type)


class Constraint:
    """Lean's TaggedUrn.Constraint: one of ConstraintMissing, ConstraintUnconstrained, ConstraintOptionalNot, ConstraintPresent, ConstraintPresentNot, ConstraintExact, ConstraintAbsent."""

    __slots__ = ()


@_dataclass(frozen=True)
class ConstraintMissing(Constraint):
    """Lean's TaggedUrn.Constraint.missing."""


@_dataclass(frozen=True)
class ConstraintUnconstrained(Constraint):
    """Lean's TaggedUrn.Constraint.unconstrained."""


@_dataclass(frozen=True)
class ConstraintOptionalNot(Constraint):
    """Lean's TaggedUrn.Constraint.optionalNot."""
    value: str


@_dataclass(frozen=True)
class ConstraintPresent(Constraint):
    """Lean's TaggedUrn.Constraint.present."""


@_dataclass(frozen=True)
class ConstraintPresentNot(Constraint):
    """Lean's TaggedUrn.Constraint.presentNot."""
    value: str


@_dataclass(frozen=True)
class ConstraintExact(Constraint):
    """Lean's TaggedUrn.Constraint.exact."""
    value: str


@_dataclass(frozen=True)
class ConstraintAbsent(Constraint):
    """Lean's TaggedUrn.Constraint.absent."""


class _ConstraintType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(2)

    def encode(self, w, v):
        if isinstance(v, ConstraintMissing):
            w.u32(0)
        elif isinstance(v, ConstraintUnconstrained):
            w.u32(1)
        elif isinstance(v, ConstraintOptionalNot):
            w.u32(2)
            lungo_py.STRING.encode(w, v.value)
        elif isinstance(v, ConstraintPresent):
            w.u32(3)
        elif isinstance(v, ConstraintPresentNot):
            w.u32(4)
            lungo_py.STRING.encode(w, v.value)
        elif isinstance(v, ConstraintExact):
            w.u32(5)
            lungo_py.STRING.encode(w, v.value)
        elif isinstance(v, ConstraintAbsent):
            w.u32(6)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a TaggedUrn.Constraint")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return ConstraintMissing()
        if c == 1:
            return ConstraintUnconstrained()
        if c == 2:
            return ConstraintOptionalNot(lungo_py.STRING.decode(r))
        if c == 3:
            return ConstraintPresent()
        if c == 4:
            return ConstraintPresentNot(lungo_py.STRING.decode(r))
        if c == 5:
            return ConstraintExact(lungo_py.STRING.decode(r))
        if c == 6:
            return ConstraintAbsent()
        raise lungo_py.MalformedError(f"constructor index {c} of TaggedUrn.Constraint")


def constraint_type() -> lungo_py.Type[Constraint]:
    """Describes TaggedUrn.Constraint for polymorphic functions."""
    return _ConstraintType()


Constraint.__lungo_fingerprint__ = "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7"
Constraint.__lungo_descriptor__ = staticmethod(constraint_type)


class _ExtType3(lungo_py.Type):
    """Lean's TaggedUrn.Exec.Wf, provided by tagged_urn._formal."""

    def __init__(self):
        self._provided = _ext_0.Wf.__lungo_descriptor__()

    def expr(self):
        return lungo_py.inductive_expr(3)

    def encode(self, w, v):
        self._provided.encode(w, v)

    def decode(self, r):
        return self._provided.decode(r)


def _ext_type_3():
    return _ExtType3()


def accepts(pattern: WfCap, request: WfCap) -> bool:
    """Lean's CapDAG.Exec.accepts : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_daccepts", (), ((wf_cap_type(), pattern), (wf_cap_type(), request),), lungo_py.value(lungo_py.BOOL))


def comparable(a: WfCap, b: WfCap) -> bool:
    """Lean's CapDAG.Exec.comparable : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dcomparable", (), ((wf_cap_type(), a), (wf_cap_type(), b),), lungo_py.value(lungo_py.BOOL))


def dispatch(candidate: WfCap, request: WfCap) -> bool:
    """Lean's CapDAG.Exec.dispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_ddispatch", (), ((wf_cap_type(), candidate), (wf_cap_type(), request),), lungo_py.value(lungo_py.BOOL))


def effect_ok(candidate: Effect, request: Effect) -> bool:
    """Lean's CapDAG.Exec.effectOk : CapDAG.Effect → CapDAG.Effect → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_deffectOk", (), ((effect_type(), candidate), (effect_type(), request),), lungo_py.value(lungo_py.BOOL))


def equivalent(a: WfCap, b: WfCap) -> bool:
    """Lean's CapDAG.Exec.equivalent : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dequivalent", (), ((wf_cap_type(), a), (wf_cap_type(), b),), lungo_py.value(lungo_py.BOOL))


def ranking_key(candidate: WfCap, request: WfCap) -> _t.Tuple[int, int]:
    """Lean's CapDAG.Exec.rankingKey : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Nat × Nat"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_drankingKey", (), ((wf_cap_type(), candidate), (wf_cap_type(), request),), lungo_py.value(lungo_py.pair(lungo_py.NAT, lungo_py.NAT)))


def select(candidates: _t.List[WfCap], request: WfCap) -> _t.Optional[WfCap]:
    """Lean's CapDAG.Exec.select : List CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Option CapDAG.Exec.WfCap"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dselect", (), ((lungo_py.list_of(wf_cap_type()), candidates), (wf_cap_type(), request),), lungo_py.value(lungo_py.option(wf_cap_type())))


def specificity(c_: WfCap) -> int:
    """Lean's CapDAG.Exec.specificity : CapDAG.Exec.WfCap → Nat"""
    return _program.invoke("capdagFormal__call_l_CapDAG_dExec_dspecificity", (), ((wf_cap_type(), c_),), lungo_py.value(lungo_py.NAT))


def make(scheme: str, tags: _t.List[_t.Tuple[str, Constraint]]) -> _t.Optional[_ext_0.Wf]:
    """Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf"""
    return _program.invoke("capdagFormal__call_l_TaggedUrn_dExec_dmake", (), ((lungo_py.STRING, scheme), (lungo_py.list_of(lungo_py.pair(lungo_py.STRING, constraint_type())), tags),), lungo_py.value(lungo_py.option(_ext_type_3())))
