"""Cap SDK - Core cap URN and definition system

This library provides the fundamental cap URN system used across
all MACINA plugins and providers. It defines the formal structure for cap
identifiers with flat tag-based naming, wildcard support, and specificity comparison.
"""

# URN module
from capdag.urn.media_urn import (
    MediaUrn,
    MediaUrnError,
    # Standard media URN constants
    MEDIA_VOID,
    MEDIA_STRING,
    MEDIA_INTEGER,
    MEDIA_NUMBER,
    MEDIA_BOOLEAN,
    MEDIA_OBJECT,
    MEDIA_IDENTITY,
    MEDIA_STRING_ARRAY,
    MEDIA_INTEGER_ARRAY,
    MEDIA_NUMBER_ARRAY,
    MEDIA_BOOLEAN_ARRAY,
    MEDIA_OBJECT_ARRAY,
    MEDIA_PNG,
    MEDIA_AUDIO,
    MEDIA_VIDEO,
    MEDIA_AUDIO_SPEECH,
    MEDIA_IMAGE_THUMBNAIL,
    MEDIA_PDF,
    MEDIA_EPUB,
    MEDIA_MD,
    MEDIA_TXT,
    MEDIA_RST,
    MEDIA_LOG,
    MEDIA_HTML,
    MEDIA_XML,
    MEDIA_JSON,
    MEDIA_JSON_SCHEMA,
    MEDIA_YAML,
    MEDIA_FILE_PATH,
    MEDIA_FILE_PATH_ARRAY,
    MEDIA_FRONTMATTER_TEXT,
    MEDIA_MODEL_SPEC,
    MEDIA_MODEL_SPEC_GGUF_VISION,
    MEDIA_MODEL_SPEC_GGUF_LLM,
    MEDIA_MODEL_SPEC_GGUF_EMBEDDINGS,
    MEDIA_MODEL_SPEC_MLX_VISION,
    MEDIA_MODEL_SPEC_MLX_LLM,
    MEDIA_MODEL_SPEC_MLX_EMBEDDINGS,
    MEDIA_MODEL_SPEC_CANDLE_VISION,
    MEDIA_MODEL_SPEC_CANDLE_EMBEDDINGS,
    MEDIA_MODEL_SPEC_CANDLE_IMAGE_EMBEDDINGS,
    MEDIA_MODEL_SPEC_CANDLE_TRANSCRIPTION,
    MEDIA_MLX_MODEL_PATH,
    MEDIA_MODEL_REPO,
    MEDIA_MODEL_DIM,
    MEDIA_DOWNLOAD_OUTPUT,
    MEDIA_LIST_OUTPUT,
    MEDIA_STATUS_OUTPUT,
    MEDIA_CONTENTS_OUTPUT,
    MEDIA_AVAILABILITY_OUTPUT,
    MEDIA_PATH_OUTPUT,
    MEDIA_EMBEDDING_VECTOR,
    MEDIA_LLM_INFERENCE_OUTPUT,
    MEDIA_FILE_METADATA,
    MEDIA_DOCUMENT_OUTLINE,
    MEDIA_DISBOUND_PAGE,
    MEDIA_IMAGE_DESCRIPTION,
    MEDIA_TRANSCRIPTION_OUTPUT,
    MEDIA_DECISION,
    MEDIA_DECISION_ARRAY,
    binary_media_urn_for_ext,
    text_media_urn_for_ext,
    image_media_urn_for_ext,
    audio_media_urn_for_ext,
)

from capdag.urn.cap_urn import (
    CapUrn,
    CapUrnError,
    CapUrnBuilder,
    CapMatcher,
)

from capdag.urn.cap_matrix import (
    CapGraph,
    CapGraphEdge,
    CapMatrix,
    CapBlock,
    BestCapSetMatch,
    CompositeCapSet,
    CapMatrixError,
    NoSetsFoundError,
    InvalidUrnError,
)

# Cap module
from capdag.cap.response import ResponseWrapper
from capdag.cap.definition import Cap, CapArg, CapOutput, RegisteredBy, StdinSource, PositionSource, CliFlagSource, MediaSpecDef
from capdag.cap.validation import (
    validate_cap_args,
    validate_positional_arguments,
    ValidationError,
    MissingRequiredArgumentError,
    InvalidArgumentTypeError,
    TooManyArgumentsError,
    InvalidCapSchemaError,
    MediaSpecValidationError,
    RESERVED_CLI_FLAGS,
)
from capdag.cap.schema_validation import (
    SchemaValidator,
    SchemaValidationError,
    SchemaCompilationError,
    ArgumentValidationError,
    OutputValidationError,
    MediaUrnNotResolvedError,
)
from capdag.cap.caller import (
    StdinSourceData,
    StdinSourceFileReference,
    CapArgumentValue,
    CapSet,
    CapCaller,
)
from capdag.cap.registry import (
    CapRegistry,
    RegistryConfig,
    RegistryError,
    HttpError,
    NotFoundError,
    ParseError,
    CacheError,
    normalize_cap_urn,
)

# Media module
from capdag.media.registry import (
    MediaUrnRegistry,
    StoredMediaSpec,
    MediaRegistryError,
    ExtensionNotFoundError,
    normalize_media_urn,
)
from capdag.media.spec import (
    MediaValidation,
    ResolvedMediaSpec,
    MediaSpecError,
    UnresolvableMediaUrn,
    DuplicateMediaUrn,
    resolve_media_urn,
    validate_media_specs_no_duplicates,
    # Profile URLs
    SCHEMA_BASE,
    PROFILE_STR,
    PROFILE_INT,
    PROFILE_NUM,
    PROFILE_BOOL,
    PROFILE_OBJ,
    PROFILE_STR_ARRAY,
    PROFILE_INT_ARRAY,
    PROFILE_NUM_ARRAY,
    PROFILE_BOOL_ARRAY,
    PROFILE_OBJ_ARRAY,
    PROFILE_VOID,
    PROFILE_IMAGE,
    PROFILE_AUDIO,
    PROFILE_VIDEO,
    PROFILE_TEXT,
    PROFILE_PDF,
    PROFILE_EPUB,
    PROFILE_MD,
    PROFILE_TXT,
    PROFILE_RST,
    PROFILE_LOG,
    PROFILE_HTML,
    PROFILE_XML,
    PROFILE_JSON,
    PROFILE_YAML,
    PROFILE_CAPDAG_DOWNLOAD_OUTPUT,
    PROFILE_CAPDAG_LOAD_OUTPUT,
    PROFILE_CAPDAG_UNLOAD_OUTPUT,
    PROFILE_CAPDAG_LIST_OUTPUT,
    PROFILE_CAPDAG_STATUS_OUTPUT,
    PROFILE_CAPDAG_CONTENTS_OUTPUT,
    PROFILE_CAPDAG_GENERATE_OUTPUT,
    PROFILE_CAPDAG_STRUCTURED_QUERY_OUTPUT,
    PROFILE_CAPDAG_QUESTIONS_ARRAY,
    get_schema_base,
    get_profile_url,
)

# Bifaci module
from capdag.bifaci import decode_chunk_payload
from capdag.bifaci.manifest import CapManifest
from capdag.bifaci.relay import (
    RelaySlave,
    RelayMaster,
    RelayError,
)

# Standard module
from capdag.standard.caps import (
    CAP_IDENTITY,
    CAP_DISCARD,
    identity_urn,
    discard_urn,
    identity_cap,
    discard_cap,
    media_urn_for_type,
    coercion_urn,
    all_coercion_paths,
    model_availability_urn,
    model_path_urn,
    llm_conversation_urn,
)

__all__ = [
    # MediaUrn
    "MediaUrn",
    "MediaUrnError",
    # Media constants
    "MEDIA_VOID",
    "MEDIA_STRING",
    "MEDIA_INTEGER",
    "MEDIA_NUMBER",
    "MEDIA_BOOLEAN",
    "MEDIA_OBJECT",
    "MEDIA_IDENTITY",
    "MEDIA_STRING_ARRAY",
    "MEDIA_INTEGER_ARRAY",
    "MEDIA_NUMBER_ARRAY",
    "MEDIA_BOOLEAN_ARRAY",
    "MEDIA_OBJECT_ARRAY",
    "MEDIA_PNG",
    "MEDIA_AUDIO",
    "MEDIA_VIDEO",
    "MEDIA_AUDIO_SPEECH",
    "MEDIA_IMAGE_THUMBNAIL",
    "MEDIA_PDF",
    "MEDIA_EPUB",
    "MEDIA_MD",
    "MEDIA_TXT",
    "MEDIA_RST",
    "MEDIA_LOG",
    "MEDIA_HTML",
    "MEDIA_XML",
    "MEDIA_JSON",
    "MEDIA_JSON_SCHEMA",
    "MEDIA_YAML",
    "MEDIA_FILE_PATH",
    "MEDIA_FILE_PATH_ARRAY",
    "MEDIA_FRONTMATTER_TEXT",
    "MEDIA_MODEL_SPEC",
    "MEDIA_MODEL_SPEC_GGUF_VISION",
    "MEDIA_MODEL_SPEC_GGUF_LLM",
    "MEDIA_MODEL_SPEC_GGUF_EMBEDDINGS",
    "MEDIA_MODEL_SPEC_MLX_VISION",
    "MEDIA_MODEL_SPEC_MLX_LLM",
    "MEDIA_MODEL_SPEC_MLX_EMBEDDINGS",
    "MEDIA_MODEL_SPEC_CANDLE_VISION",
    "MEDIA_MODEL_SPEC_CANDLE_EMBEDDINGS",
    "MEDIA_MODEL_SPEC_CANDLE_IMAGE_EMBEDDINGS",
    "MEDIA_MODEL_SPEC_CANDLE_TRANSCRIPTION",
    "MEDIA_MLX_MODEL_PATH",
    "MEDIA_MODEL_REPO",
    "MEDIA_MODEL_DIM",
    "MEDIA_DOWNLOAD_OUTPUT",
    "MEDIA_LIST_OUTPUT",
    "MEDIA_STATUS_OUTPUT",
    "MEDIA_CONTENTS_OUTPUT",
    "MEDIA_AVAILABILITY_OUTPUT",
    "MEDIA_PATH_OUTPUT",
    "MEDIA_EMBEDDING_VECTOR",
    "MEDIA_LLM_INFERENCE_OUTPUT",
    "MEDIA_FILE_METADATA",
    "MEDIA_DOCUMENT_OUTLINE",
    "MEDIA_DISBOUND_PAGE",
    "MEDIA_IMAGE_DESCRIPTION",
    "MEDIA_TRANSCRIPTION_OUTPUT",
    "MEDIA_DECISION",
    "MEDIA_DECISION_ARRAY",
    "binary_media_urn_for_ext",
    "text_media_urn_for_ext",
    "image_media_urn_for_ext",
    "audio_media_urn_for_ext",
    # CapUrn
    "CapUrn",
    "CapUrnError",
    "CapUrnBuilder",
    "CapMatcher",
    # Response
    "ResponseWrapper",
    # Cap
    "Cap",
    "CapArg",
    "CapOutput",
    "StdinSource",
    "PositionSource",
    "CliFlagSource",
    "MediaSpecDef",
    # Manifest
    "CapManifest",
    # Bifaci utilities
    "decode_chunk_payload",
    # Validation
    "validate_cap_args",
    "validate_positional_arguments",
    "ValidationError",
    "MissingRequiredArgumentError",
    "InvalidArgumentTypeError",
    "TooManyArgumentsError",
    "InvalidCapSchemaError",
    "MediaSpecValidationError",
    "RESERVED_CLI_FLAGS",
    # Schema validation
    "SchemaValidator",
    "SchemaValidationError",
    "SchemaCompilationError",
    "ArgumentValidationError",
    "OutputValidationError",
    "MediaUrnNotResolvedError",
    # Caller
    "StdinSourceData",
    "StdinSourceFileReference",
    "CapArgumentValue",
    "CapSet",
    "CapCaller",
    # Registry
    "CapRegistry",
    "RegistryConfig",
    "RegistryError",
    "HttpError",
    "NotFoundError",
    "ParseError",
    "CacheError",
    "normalize_cap_urn",
    # Media Registry
    "MediaUrnRegistry",
    "StoredMediaSpec",
    "MediaRegistryError",
    "ExtensionNotFoundError",
    "normalize_media_urn",
    # Media Spec
    "MediaValidation",
    "ResolvedMediaSpec",
    "MediaSpecError",
    "UnresolvableMediaUrn",
    "DuplicateMediaUrn",
    "resolve_media_urn",
    "validate_media_specs_no_duplicates",
    "SCHEMA_BASE",
    "PROFILE_STR",
    "PROFILE_INT",
    "PROFILE_NUM",
    "PROFILE_BOOL",
    "PROFILE_OBJ",
    "PROFILE_STR_ARRAY",
    "PROFILE_INT_ARRAY",
    "PROFILE_NUM_ARRAY",
    "PROFILE_BOOL_ARRAY",
    "PROFILE_OBJ_ARRAY",
    "PROFILE_VOID",
    "PROFILE_IMAGE",
    "PROFILE_AUDIO",
    "PROFILE_VIDEO",
    "PROFILE_TEXT",
    "PROFILE_PDF",
    "PROFILE_EPUB",
    "PROFILE_MD",
    "PROFILE_TXT",
    "PROFILE_RST",
    "PROFILE_LOG",
    "PROFILE_HTML",
    "PROFILE_XML",
    "PROFILE_JSON",
    "PROFILE_YAML",
    "PROFILE_CAPDAG_DOWNLOAD_OUTPUT",
    "PROFILE_CAPDAG_LOAD_OUTPUT",
    "PROFILE_CAPDAG_UNLOAD_OUTPUT",
    "PROFILE_CAPDAG_LIST_OUTPUT",
    "PROFILE_CAPDAG_STATUS_OUTPUT",
    "PROFILE_CAPDAG_CONTENTS_OUTPUT",
    "PROFILE_CAPDAG_GENERATE_OUTPUT",
    "PROFILE_CAPDAG_STRUCTURED_QUERY_OUTPUT",
    "PROFILE_CAPDAG_QUESTIONS_ARRAY",
    "get_schema_base",
    "get_profile_url",
    # CapMatrix
    "CapGraph",
    "CapGraphEdge",
    "CapMatrix",
    "CapBlock",
    "BestCapSetMatch",
    "CompositeCapSet",
    "CapMatrixError",
    "NoSetsFoundError",
    "InvalidUrnError",
    # Standard caps
    "CAP_IDENTITY",
    "CAP_DISCARD",
    "identity_urn",
    "discard_urn",
    "identity_cap",
    "discard_cap",
    "media_urn_for_type",
    "coercion_urn",
    "all_coercion_paths",
    "model_availability_urn",
    "model_path_urn",
    "llm_conversation_urn",
    # Relay
    "RelaySlave",
    "RelayMaster",
    "RelayError",
]
