"""Build-time-baked content hashes of this build's bundled cartridges.

Mirrors ``capdag::bundled_cartridge_hashes``. In Rust the table is
generated by ``build.rs`` from the ``MFR_BUNDLED_CARTRIDGE_HASHES`` env
var (a JSON ``{name: {version: sha256}}`` map the build pipeline computes
after building the provider binaries). It is empty when no providers were
bundled — which is the case for a plain test build.

``cartridge_discovery`` verifies any cartridge marked
``installed_from: bundle`` against this set: a bundled cartridge whose
on-disk directory does not hash to its baked value (or is absent from the
set) is surfaced incompatible and never hosted.
"""

from typing import List, Optional, Tuple

#: Baked ``(name, version, sha256)`` triples. Empty for an unbundled
#: build (the test build). A real bundle build replaces this with the
#: hashes recorded at build time.
BUNDLED_CARTRIDGE_HASHES: List[Tuple[str, str, str]] = []


def bundled_cartridge_expected_hash(name: str, version: str) -> Optional[str]:
    """Look up the baked expected directory hash for a bundled cartridge,
    or ``None`` if ``(name, version)`` was not recorded at build time."""
    for n, v, h in BUNDLED_CARTRIDGE_HASHES:
        if n == name and v == version:
            return h
    return None
