/* Generated by lungo 1.77.3244 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module CapDAG.Exec. */
#include "capdagFormal_program.h"

/* Lean: CapDAG.Exec.accepts */
/* Source: ../../../../formal/CapDAG/Exec.lean:48:1 */
uint8_t capdagFormal__l_CapDAG_dExec_daccepts(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    uint8_t x_10;
    uint8_t x_12;
    uint8_t x_13;
    uint8_t x_15;
    uint8_t x_16;
    uint8_t x_17;
    uint8_t x_18;
    uint8_t x_19;
    uint8_t x_20;
    x_3 = lungo_ctor_get(x_2, 0);
    x_4 = lungo_ctor_get(x_2, 1);
    x_5 = lungo_ctor_get(x_2, 2);
    x_6 = lungo_ctor_get_uint8(x_2, 3 * sizeof(size_t));
    x_7 = lungo_ctor_get(x_1, 0);
    x_8 = lungo_ctor_get(x_1, 1);
    x_9 = lungo_ctor_get(x_1, 2);
    x_10 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    x_19 = capdagFormal__l_TaggedUrn_dExec_drefines(x_3, x_7);
    switch (x_19) {
        case 0: {
            x_15 = x_19;
            goto block_14;
        }
        default: {
            x_20 = capdagFormal__l_TaggedUrn_dExec_drefines(x_8, x_4);
            x_15 = x_20;
            goto block_14;
        }
    }
    block_14:;
    switch (x_15) {
        case 0: {
            return x_15;
        }
        default: {
            x_16 = (uint8_t)0u;
            x_17 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_10, x_16);
            switch (x_17) {
                case 0: {
                    x_18 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_10, x_6);
                    x_12 = x_18;
                    goto block_11;
                }
                default: {
                    x_12 = x_17;
                    goto block_11;
                }
            }
        }
    }
    block_11:;
    switch (x_12) {
        case 0: {
            return x_12;
        }
        default: {
            x_13 = capdagFormal__l_TaggedUrn_dExec_drefines(x_5, x_9);
            return x_13;
        }
    }
}

/* Lean: CapDAG.Exec.accepts._boxed */
/* Compiled from: CapDAG.Exec.accepts */
/* Source: ../../../../formal/CapDAG/Exec.lean:48:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_daccepts_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_daccepts(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.Exec.comparable */
/* Source: ../../../../formal/CapDAG/Exec.lean:89:1 */
uint8_t capdagFormal__l_CapDAG_dExec_dcomparable(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    uint8_t x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_daccepts(x_1, x_2);
    switch (x_3) {
        case 0: {
            x_4 = capdagFormal__l_CapDAG_dExec_daccepts(x_2, x_1);
            return x_4;
        }
        default: {
            return x_3;
        }
    }
}

/* Lean: CapDAG.Exec.comparable._boxed */
/* Compiled from: CapDAG.Exec.comparable */
/* Source: ../../../../formal/CapDAG/Exec.lean:89:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dcomparable_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_dcomparable(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.Exec.dispatch */
/* Source: ../../../../formal/CapDAG/Exec.lean:35:1 */
uint8_t capdagFormal__l_CapDAG_dExec_ddispatch(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    uint8_t x_10;
    uint8_t x_12;
    uint8_t x_13;
    uint8_t x_14;
    uint8_t x_15;
    uint8_t x_16;
    x_3 = lungo_ctor_get(x_2, 0);
    x_4 = lungo_ctor_get(x_2, 1);
    x_5 = lungo_ctor_get(x_2, 2);
    x_6 = lungo_ctor_get_uint8(x_2, 3 * sizeof(size_t));
    x_7 = lungo_ctor_get(x_1, 0);
    x_8 = lungo_ctor_get(x_1, 1);
    x_9 = lungo_ctor_get(x_1, 2);
    x_10 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    x_15 = capdagFormal__l_TaggedUrn_dExec_drefines(x_3, x_7);
    switch (x_15) {
        case 0: {
            x_12 = x_15;
            goto block_11;
        }
        default: {
            x_16 = capdagFormal__l_TaggedUrn_dExec_drefines(x_8, x_4);
            x_12 = x_16;
            goto block_11;
        }
    }
    block_11:;
    switch (x_12) {
        case 0: {
            return x_12;
        }
        default: {
            x_13 = capdagFormal__l_CapDAG_dExec_deffectOk(x_10, x_6);
            switch (x_13) {
                case 0: {
                    return x_13;
                }
                default: {
                    x_14 = capdagFormal__l_TaggedUrn_dExec_drefines(x_9, x_5);
                    return x_14;
                }
            }
        }
    }
}

/* Lean: CapDAG.Exec.dispatch._boxed */
/* Compiled from: CapDAG.Exec.dispatch */
/* Source: ../../../../formal/CapDAG/Exec.lean:35:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_ddispatch_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_ddispatch(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.Exec.effectOk */
/* Source: ../../../../formal/CapDAG/Exec.lean:28:1 */
uint8_t capdagFormal__l_CapDAG_dExec_deffectOk(uint8_t x_1, uint8_t x_2) {
    uint8_t x_3;
    uint8_t x_4;
    uint8_t x_5;
    x_3 = (uint8_t)0u;
    x_4 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_2, x_3);
    switch (x_4) {
        case 0: {
            x_5 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_1, x_2);
            return x_5;
        }
        default: {
            return x_4;
        }
    }
}

/* Lean: CapDAG.Exec.effectOk._boxed */
/* Compiled from: CapDAG.Exec.effectOk */
/* Source: ../../../../formal/CapDAG/Exec.lean:28:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_deffectOk_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    uint8_t x_4;
    uint8_t x_5;
    lungo_obj x_6;
    x_3 = (uint8_t)lungo_unbox(x_1);
    x_4 = (uint8_t)lungo_unbox(x_2);
    x_5 = capdagFormal__l_CapDAG_dExec_deffectOk(x_3, x_4);
    x_6 = lungo_box((size_t)x_5);
    return x_6;
}

/* Lean: CapDAG.Exec.equivalent */
/* Source: ../../../../formal/CapDAG/Exec.lean:88:1 */
uint8_t capdagFormal__l_CapDAG_dExec_dequivalent(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    uint8_t x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_daccepts(x_1, x_2);
    switch (x_3) {
        case 0: {
            return x_3;
        }
        default: {
            x_4 = capdagFormal__l_CapDAG_dExec_daccepts(x_2, x_1);
            return x_4;
        }
    }
}

/* Lean: CapDAG.Exec.equivalent._boxed */
/* Compiled from: CapDAG.Exec.equivalent */
/* Source: ../../../../formal/CapDAG/Exec.lean:88:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dequivalent_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_dequivalent(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.Exec.rankingKey */
/* Source: ../../../../formal/CapDAG/Exec.lean:112:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_drankingKey(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    x_3 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfCap_dtoCap(x_1);
    x_4 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfCap_dtoCap(x_2);
    x_5 = capdagFormal__l_CapDAG_drankingKey(x_3, x_4);
    return x_5;
}

/* Lean: CapDAG.Exec.select */
/* Source: ../../../../formal/CapDAG/Exec.lean:116:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dselect(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    x_3 = lungo_box(0);
    x_4 = capdagFormal__l_List_dfoldl_d__at___dCapDAG_dExec_dselect_dspec__0(x_2, x_3, x_1);
    return x_4;
}

/* Lean: CapDAG.Exec.specificity */
/* Source: ../../../../formal/CapDAG/Exec.lean:110:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dspecificity(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    x_2 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfCap_dtoCap(x_1);
    x_3 = capdagFormal__l_CapDAG_dcapScore(x_2);
    return x_3;
}

/* Lean: List.foldl._at_.CapDAG.Exec.select.spec_0 */
/* Compiled from: List.foldl */
/* Source: <lean>/Init/Prelude.lean:3102:1 */
lungo_obj capdagFormal__l_List_dfoldl_d__at___dCapDAG_dExec_dselect_dspec__0(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_8;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    uint8_t x_13;
    lungo_obj x_16;
    uint8_t x_17;
    lungo_obj x_19;
    lungo_obj x_21;
    uint8_t x_22;
    lungo_obj x_23;
    _start:
    switch (lungo_obj_tag(x_3)) {
        case 0: {
            lungo_dec_ref(x_1);
            return x_2;
        }
        default: {
            x_4 = lungo_ctor_get(x_3, 0);
            lungo_inc(x_4);
            x_5 = lungo_ctor_get(x_3, 1);
            lungo_inc(x_5);
            lungo_dec_ref(x_3);
            x_6 = capdagFormal__l_CapDAG_dExec_ddispatch(x_4, x_1);
            switch (x_6) {
                case 0: {
                    lungo_dec(x_4);
                    {
                        lungo_obj t_0 = x_1;
                        lungo_obj t_1 = x_2;
                        lungo_obj t_2 = x_5;
                        x_1 = t_0;
                        x_2 = t_1;
                        x_3 = t_2;
                        goto _start;
                    }
                }
                default: {
                    switch (lungo_obj_tag(x_2)) {
                        case 0: {
                            x_8 = lungo_alloc_ctor(1, 1, 0);
                            lungo_ctor_set(x_8, 0, x_4);
                            {
                                lungo_obj t_0 = x_1;
                                lungo_obj t_1 = x_8;
                                lungo_obj t_2 = x_5;
                                x_1 = t_0;
                                x_2 = t_1;
                                x_3 = t_2;
                                goto _start;
                            }
                        }
                        default: {
                            x_10 = lungo_ctor_get(x_2, 0);
                            lungo_inc_ref_n(x_1, 2);
                            lungo_inc(x_4);
                            x_11 = capdagFormal__l_CapDAG_dExec_drankingKey(x_4, x_1);
                            lungo_inc(x_10);
                            x_12 = capdagFormal__l_CapDAG_dExec_drankingKey(x_10, x_1);
                            x_13 = capdagFormal__l_CapDAG_dbetterKey(x_11, x_12);
                            lungo_dec_ref(x_12);
                            lungo_dec_ref(x_11);
                            switch (x_13) {
                                case 0: {
                                    lungo_dec(x_4);
                                    {
                                        lungo_obj t_0 = x_1;
                                        lungo_obj t_1 = x_2;
                                        lungo_obj t_2 = x_5;
                                        x_1 = t_0;
                                        x_2 = t_1;
                                        x_3 = t_2;
                                        goto _start;
                                    }
                                }
                                default: {
                                    x_22 = !lungo_is_exclusive(x_2);
                                    switch (x_22) {
                                        case 0: {
                                            x_23 = lungo_ctor_get(x_2, 0);
                                            lungo_dec(x_23);
                                            x_16 = x_2;
                                            x_17 = x_22;
                                            goto block_15;
                                        }
                                        default: {
                                            lungo_dec(x_2);
                                            x_16 = lungo_box(0);
                                            x_17 = x_22;
                                            goto block_15;
                                        }
                                    }
                                    block_15:;
                                    switch (x_17) {
                                        case 0: {
                                            lungo_ctor_set(x_16, 0, x_4);
                                            x_19 = x_16;
                                            goto block_18;
                                        }
                                        default: {
                                            x_21 = lungo_alloc_ctor(1, 1, 0);
                                            lungo_ctor_set(x_21, 0, x_4);
                                            x_19 = x_21;
                                            goto block_18;
                                        }
                                    }
                                    block_18:;
                                    {
                                        lungo_obj t_0 = x_1;
                                        lungo_obj t_1 = x_19;
                                        lungo_obj t_2 = x_5;
                                        x_1 = t_0;
                                        x_2 = t_1;
                                        x_3 = t_2;
                                        goto _start;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.WfCap.toCap */
/* Source: ../../../../formal/CapDAG/Exec.lean:23:1 */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfCap_dtoCap(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_7;
    uint8_t x_8;
    lungo_obj x_10;
    lungo_obj x_11;
    uint8_t x_12;
    x_2 = lungo_ctor_get(x_1, 0);
    x_3 = lungo_ctor_get(x_1, 1);
    x_4 = lungo_ctor_get(x_1, 2);
    x_5 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    x_12 = !lungo_is_exclusive(x_1);
    switch (x_12) {
        case 0: {
            x_7 = x_1;
            x_8 = x_12;
            goto block_6;
        }
        default: {
            lungo_inc(x_4);
            lungo_inc(x_3);
            lungo_inc(x_2);
            lungo_dec(x_1);
            x_7 = lungo_box(0);
            x_8 = x_12;
            goto block_6;
        }
    }
    block_6:;
    switch (x_8) {
        case 0: {
            x_10 = x_7;
            goto block_9;
        }
        default: {
            x_11 = lungo_alloc_ctor(0, 3, 1);
            lungo_ctor_set(x_11, 0, x_2);
            lungo_ctor_set(x_11, 1, x_3);
            lungo_ctor_set(x_11, 2, x_4);
            lungo_ctor_set_uint8(x_11, 3 * sizeof(size_t), x_5);
            x_10 = x_11;
            goto block_9;
        }
    }
    block_9:;
    return x_10;
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.select.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dselect_dmatch__1_dsplitter(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec(x_4);
            x_5 = lungo_box(0);
            x_6 = lungo_apply_1(x_3, x_5);
            return x_6;
        }
        default: {
            lungo_dec(x_3);
            x_7 = lungo_ctor_get(x_2, 0);
            lungo_inc(x_7);
            lungo_dec_ref(x_2);
            x_8 = lungo_apply_1(x_4, x_7);
            return x_8;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.select.match_1.splitter._redArg */
/* Compiled from: _private.CapDAG.Exec.0.CapDAG.Exec.select.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dselect_dmatch__1_dsplitter_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            lungo_dec(x_3);
            x_4 = lungo_box(0);
            x_5 = lungo_apply_1(x_2, x_4);
            return x_5;
        }
        default: {
            lungo_dec(x_2);
            x_6 = lungo_ctor_get(x_1, 0);
            lungo_inc(x_6);
            lungo_dec_ref(x_1);
            x_7 = lungo_apply_1(x_3, x_6);
            return x_7;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.selectStep.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dselectStep_dmatch__1_dsplitter(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec(x_4);
            x_5 = lungo_box(0);
            x_6 = lungo_apply_1(x_3, x_5);
            return x_6;
        }
        default: {
            lungo_dec(x_3);
            x_7 = lungo_ctor_get(x_2, 0);
            lungo_inc(x_7);
            lungo_dec_ref(x_2);
            x_8 = lungo_apply_1(x_4, x_7);
            return x_8;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.selectStep.match_1.splitter._redArg */
/* Compiled from: _private.CapDAG.Exec.0.CapDAG.selectStep.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dselectStep_dmatch__1_dsplitter_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            lungo_dec(x_3);
            x_4 = lungo_box(0);
            x_5 = lungo_apply_1(x_2, x_4);
            return x_5;
        }
        default: {
            lungo_dec(x_2);
            x_6 = lungo_ctor_get(x_1, 0);
            lungo_inc(x_6);
            lungo_dec_ref(x_1);
            x_7 = lungo_apply_1(x_3, x_6);
            return x_7;
        }
    }
}

