/* Generated by lungo 1.88.0 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module CapDAG.Route. */
#include "capdagFormal_program.h"

/* Lean: CapDAG.instDecidableFlows */
/* Source: ../../../../formal/CapDAG/Route.lean:29:1 */
uint8_t capdagFormal__l_CapDAG_dinstDecidableFlows(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    x_3 = lungo_ctor_get(x_1, 1);
    lungo_inc_ref(x_3);
    lungo_dec_ref(x_1);
    x_4 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_4);
    lungo_dec_ref(x_2);
    x_5 = capdagFormal__l_TaggedUrn_dinstDecidableRefines(x_3, x_4);
    return x_5;
}

/* Lean: CapDAG.instDecidableFlows._boxed */
/* Compiled from: CapDAG.instDecidableFlows */
/* Source: ../../../../formal/CapDAG/Route.lean:29:1 */
lungo_obj capdagFormal__l_CapDAG_dinstDecidableFlows_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dinstDecidableFlows(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.instDecidableMayFlow */
/* Source: ../../../../formal/CapDAG/Route.lean:34:1 */
uint8_t capdagFormal__l_CapDAG_dinstDecidableMayFlow(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    x_3 = lungo_ctor_get(x_1, 1);
    lungo_inc_ref(x_3);
    lungo_dec_ref(x_1);
    x_4 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_4);
    lungo_dec_ref(x_2);
    x_5 = capdagFormal__l_TaggedUrn_dinstDecidableMeets(x_3, x_4);
    return x_5;
}

/* Lean: CapDAG.instDecidableMayFlow._boxed */
/* Compiled from: CapDAG.instDecidableMayFlow */
/* Source: ../../../../formal/CapDAG/Route.lean:34:1 */
lungo_obj capdagFormal__l_CapDAG_dinstDecidableMayFlow_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dinstDecidableMayFlow(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

