/* Generated by lungo 1.70.2879 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module CapDAG.Cap. */
#include "capdagFormal_program.h"

/* Lean: CapDAG.Cap.kind */
/* Source: ../../../../formal/CapDAG/Cap.lean:115:1 */
uint8_t capdagFormal__l_CapDAG_dCap_dkind(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    uint8_t x_7;
    lungo_obj x_8;
    uint8_t x_9;
    uint8_t x_10;
    uint8_t x_11;
    uint8_t x_12;
    uint8_t x_13;
    uint8_t x_14;
    lungo_obj x_16;
    uint8_t x_17;
    uint8_t x_18;
    uint8_t x_19;
    lungo_obj x_20;
    uint8_t x_21;
    uint8_t x_22;
    lungo_obj x_23;
    uint8_t x_24;
    uint8_t x_25;
    uint8_t x_26;
    uint8_t x_27;
    x_2 = lungo_ctor_get(x_1, 0);
    lungo_inc_ref_n(x_2, 2);
    x_3 = lungo_ctor_get(x_1, 1);
    lungo_inc_ref(x_3);
    x_4 = lungo_ctor_get(x_1, 2);
    lungo_inc_ref(x_4);
    x_5 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    lungo_dec_ref(x_1);
    x_20 = capdagFormal__l_CapDAG_dmediaTop();
    x_21 = capdagFormal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq(x_2, x_20);
    switch (x_21) {
        case 0: {
            lungo_dec_ref(x_4);
            goto block_15;
        }
        default: {
            lungo_inc_ref(x_3);
            x_22 = capdagFormal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq(x_3, x_20);
            switch (x_22) {
                case 0: {
                    lungo_dec_ref(x_4);
                    goto block_15;
                }
                default: {
                    x_23 = lungo_ctor_get(x_4, 1);
                    lungo_inc(x_23);
                    lungo_dec_ref(x_4);
                    x_24 = capdagFormal__l_List_dinstDecidableEqNil_d__redArg(x_23);
                    lungo_dec(x_23);
                    switch (x_24) {
                        case 0: {
                            goto block_15;
                        }
                        default: {
                            x_25 = (uint8_t)2u;
                            x_26 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_5, x_25);
                            switch (x_26) {
                                case 0: {
                                    goto block_15;
                                }
                                default: {
                                    lungo_dec_ref(x_3);
                                    lungo_dec_ref(x_2);
                                    x_27 = (uint8_t)0u;
                                    return x_27;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    block_15:;
    x_16 = capdagFormal__l_CapDAG_dmediaVoid();
    x_17 = capdagFormal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq(x_2, x_16);
    switch (x_17) {
        case 0: {
            x_7 = x_17;
            x_8 = x_16;
            goto block_6;
        }
        default: {
            lungo_inc_ref(x_3);
            x_18 = capdagFormal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq(x_3, x_16);
            switch (x_18) {
                case 0: {
                    switch (x_17) {
                        case 0: {
                            x_7 = x_17;
                            x_8 = x_16;
                            goto block_6;
                        }
                        default: {
                            lungo_dec_ref(x_3);
                            x_19 = (uint8_t)1u;
                            return x_19;
                        }
                    }
                }
                default: {
                    x_7 = x_17;
                    x_8 = x_16;
                    goto block_6;
                }
            }
        }
    }
    block_6:;
    switch (x_7) {
        case 0: {
            x_9 = capdagFormal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq(x_3, x_8);
            switch (x_9) {
                case 0: {
                    x_10 = (uint8_t)4u;
                    return x_10;
                }
                default: {
                    x_11 = (uint8_t)2u;
                    return x_11;
                }
            }
        }
        default: {
            x_12 = capdagFormal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq(x_3, x_8);
            switch (x_12) {
                case 0: {
                    x_13 = (uint8_t)4u;
                    return x_13;
                }
                default: {
                    x_14 = (uint8_t)3u;
                    return x_14;
                }
            }
        }
    }
}

/* Lean: CapDAG.Cap.kind._boxed */
/* Compiled from: CapDAG.Cap.kind */
/* Source: ../../../../formal/CapDAG/Cap.lean:115:1 */
lungo_obj capdagFormal__l_CapDAG_dCap_dkind_d__boxed(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    x_2 = capdagFormal__l_CapDAG_dCap_dkind(x_1);
    x_3 = lungo_box((size_t)x_2);
    return x_3;
}

/* Lean: CapDAG.CapKind.ctorElim */
/* Source: ../../../../formal/CapDAG/Cap.lean:111:1 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dctorElim(lungo_obj x_1, lungo_obj x_2, uint8_t x_3, lungo_obj x_4, lungo_obj x_5) {
    (void)x_1;
    (void)x_2;
    (void)x_3;
    (void)x_4;
    lungo_inc(x_5);
    return x_5;
}

/* Lean: CapDAG.CapKind.ctorElim._boxed */
/* Compiled from: CapDAG.CapKind.ctorElim */
/* Source: ../../../../formal/CapDAG/Cap.lean:111:1 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dctorElim_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5) {
    uint8_t x_6;
    lungo_obj x_7;
    x_6 = (uint8_t)lungo_unbox(x_3);
    x_7 = capdagFormal__l_CapDAG_dCapKind_dctorElim(x_1, x_2, x_6, x_4, x_5);
    lungo_dec(x_5);
    lungo_dec(x_2);
    return x_7;
}

/* Lean: CapDAG.CapKind.ctorElim._redArg */
/* Compiled from: CapDAG.CapKind.ctorElim */
/* Source: ../../../../formal/CapDAG/Cap.lean:111:1 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dctorElim_d__redArg(lungo_obj x_1) {
    lungo_inc(x_1);
    return x_1;
}

/* Lean: CapDAG.CapKind.ctorElim._redArg._boxed */
/* Compiled from: CapDAG.CapKind.ctorElim */
/* Source: ../../../../formal/CapDAG/Cap.lean:111:1 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dctorElim_d__redArg_d__boxed(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = capdagFormal__l_CapDAG_dCapKind_dctorElim_d__redArg(x_1);
    lungo_dec(x_1);
    return x_2;
}

/* Lean: CapDAG.CapKind.ctorIdx */
/* Source: ../../../../formal/CapDAG/Cap.lean */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dctorIdx(uint8_t x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    switch (x_1) {
        case 0: {
            x_2 = lungo_usize_to_nat(0u);
            return x_2;
        }
        case 1: {
            x_3 = lungo_usize_to_nat(1u);
            return x_3;
        }
        case 2: {
            x_4 = lungo_usize_to_nat(2u);
            return x_4;
        }
        case 3: {
            x_5 = lungo_usize_to_nat(3u);
            return x_5;
        }
        default: {
            x_6 = lungo_usize_to_nat(4u);
            return x_6;
        }
    }
}

/* Lean: CapDAG.CapKind.ctorIdx._boxed */
/* Compiled from: CapDAG.CapKind.ctorIdx */
/* Source: ../../../../formal/CapDAG/Cap.lean */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dctorIdx_d__boxed(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    x_2 = (uint8_t)lungo_unbox(x_1);
    x_3 = capdagFormal__l_CapDAG_dCapKind_dctorIdx(x_2);
    return x_3;
}

/* Lean: CapDAG.CapKind.effect.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:30 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_deffect_delim(lungo_obj x_1, uint8_t x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    (void)x_2;
    (void)x_3;
    lungo_inc(x_4);
    return x_4;
}

/* Lean: CapDAG.CapKind.effect.elim._boxed */
/* Compiled from: CapDAG.CapKind.effect.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:30 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_deffect_delim_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    uint8_t x_5;
    lungo_obj x_6;
    x_5 = (uint8_t)lungo_unbox(x_2);
    x_6 = capdagFormal__l_CapDAG_dCapKind_deffect_delim(x_1, x_5, x_3, x_4);
    lungo_dec(x_4);
    return x_6;
}

/* Lean: CapDAG.CapKind.effect.elim._redArg */
/* Compiled from: CapDAG.CapKind.effect.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:30 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_deffect_delim_d__redArg(lungo_obj x_1) {
    lungo_inc(x_1);
    return x_1;
}

/* Lean: CapDAG.CapKind.effect.elim._redArg._boxed */
/* Compiled from: CapDAG.CapKind.effect.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:30 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_deffect_delim_d__redArg_d__boxed(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = capdagFormal__l_CapDAG_dCapKind_deffect_delim_d__redArg(x_1);
    lungo_dec(x_1);
    return x_2;
}

/* Lean: CapDAG.CapKind.identity.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:3 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_didentity_delim(lungo_obj x_1, uint8_t x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    (void)x_2;
    (void)x_3;
    lungo_inc(x_4);
    return x_4;
}

/* Lean: CapDAG.CapKind.identity.elim._boxed */
/* Compiled from: CapDAG.CapKind.identity.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:3 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_didentity_delim_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    uint8_t x_5;
    lungo_obj x_6;
    x_5 = (uint8_t)lungo_unbox(x_2);
    x_6 = capdagFormal__l_CapDAG_dCapKind_didentity_delim(x_1, x_5, x_3, x_4);
    lungo_dec(x_4);
    return x_6;
}

/* Lean: CapDAG.CapKind.identity.elim._redArg */
/* Compiled from: CapDAG.CapKind.identity.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:3 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_didentity_delim_d__redArg(lungo_obj x_1) {
    lungo_inc(x_1);
    return x_1;
}

/* Lean: CapDAG.CapKind.identity.elim._redArg._boxed */
/* Compiled from: CapDAG.CapKind.identity.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:3 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_didentity_delim_d__redArg_d__boxed(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = capdagFormal__l_CapDAG_dCapKind_didentity_delim_d__redArg(x_1);
    lungo_dec(x_1);
    return x_2;
}

/* Lean: CapDAG.CapKind.ofNat */
/* Source: ../../../../formal/CapDAG/Cap.lean */
uint8_t capdagFormal__l_CapDAG_dCapKind_dofNat(lungo_obj x_1) {
    lungo_obj x_2;
    uint8_t x_3;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_6;
    uint8_t x_7;
    uint8_t x_8;
    uint8_t x_9;
    uint8_t x_10;
    lungo_obj x_11;
    uint8_t x_12;
    uint8_t x_13;
    uint8_t x_14;
    x_2 = lungo_usize_to_nat(1u);
    x_3 = capdagFormal__l_Nat_dble(x_1, x_2);
    switch (x_3) {
        case 0: {
            x_4 = lungo_usize_to_nat(2u);
            x_5 = capdagFormal__l_Nat_dble(x_1, x_4);
            switch (x_5) {
                case 0: {
                    x_6 = lungo_usize_to_nat(3u);
                    x_7 = capdagFormal__l_Nat_dble(x_1, x_6);
                    switch (x_7) {
                        case 0: {
                            x_8 = (uint8_t)4u;
                            return x_8;
                        }
                        default: {
                            x_9 = (uint8_t)3u;
                            return x_9;
                        }
                    }
                }
                default: {
                    x_10 = (uint8_t)2u;
                    return x_10;
                }
            }
        }
        default: {
            x_11 = lungo_usize_to_nat(0u);
            x_12 = capdagFormal__l_Nat_dble(x_1, x_11);
            switch (x_12) {
                case 0: {
                    x_13 = (uint8_t)1u;
                    return x_13;
                }
                default: {
                    x_14 = (uint8_t)0u;
                    return x_14;
                }
            }
        }
    }
}

/* Lean: CapDAG.CapKind.ofNat._boxed */
/* Compiled from: CapDAG.CapKind.ofNat */
/* Source: ../../../../formal/CapDAG/Cap.lean */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dofNat_d__boxed(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    x_2 = capdagFormal__l_CapDAG_dCapKind_dofNat(x_1);
    lungo_dec(x_1);
    x_3 = lungo_box((size_t)x_2);
    return x_3;
}

/* Lean: CapDAG.CapKind.sink.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:23 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dsink_delim(lungo_obj x_1, uint8_t x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    (void)x_2;
    (void)x_3;
    lungo_inc(x_4);
    return x_4;
}

/* Lean: CapDAG.CapKind.sink.elim._boxed */
/* Compiled from: CapDAG.CapKind.sink.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:23 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dsink_delim_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    uint8_t x_5;
    lungo_obj x_6;
    x_5 = (uint8_t)lungo_unbox(x_2);
    x_6 = capdagFormal__l_CapDAG_dCapKind_dsink_delim(x_1, x_5, x_3, x_4);
    lungo_dec(x_4);
    return x_6;
}

/* Lean: CapDAG.CapKind.sink.elim._redArg */
/* Compiled from: CapDAG.CapKind.sink.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:23 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dsink_delim_d__redArg(lungo_obj x_1) {
    lungo_inc(x_1);
    return x_1;
}

/* Lean: CapDAG.CapKind.sink.elim._redArg._boxed */
/* Compiled from: CapDAG.CapKind.sink.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:23 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dsink_delim_d__redArg_d__boxed(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = capdagFormal__l_CapDAG_dCapKind_dsink_delim_d__redArg(x_1);
    lungo_dec(x_1);
    return x_2;
}

/* Lean: CapDAG.CapKind.source.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:14 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dsource_delim(lungo_obj x_1, uint8_t x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    (void)x_2;
    (void)x_3;
    lungo_inc(x_4);
    return x_4;
}

/* Lean: CapDAG.CapKind.source.elim._boxed */
/* Compiled from: CapDAG.CapKind.source.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:14 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dsource_delim_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    uint8_t x_5;
    lungo_obj x_6;
    x_5 = (uint8_t)lungo_unbox(x_2);
    x_6 = capdagFormal__l_CapDAG_dCapKind_dsource_delim(x_1, x_5, x_3, x_4);
    lungo_dec(x_4);
    return x_6;
}

/* Lean: CapDAG.CapKind.source.elim._redArg */
/* Compiled from: CapDAG.CapKind.source.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:14 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dsource_delim_d__redArg(lungo_obj x_1) {
    lungo_inc(x_1);
    return x_1;
}

/* Lean: CapDAG.CapKind.source.elim._redArg._boxed */
/* Compiled from: CapDAG.CapKind.source.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:14 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dsource_delim_d__redArg_d__boxed(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = capdagFormal__l_CapDAG_dCapKind_dsource_delim_d__redArg(x_1);
    lungo_dec(x_1);
    return x_2;
}

/* Lean: CapDAG.CapKind.transform.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:39 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dtransform_delim(lungo_obj x_1, uint8_t x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    (void)x_2;
    (void)x_3;
    lungo_inc(x_4);
    return x_4;
}

/* Lean: CapDAG.CapKind.transform.elim._boxed */
/* Compiled from: CapDAG.CapKind.transform.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:39 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dtransform_delim_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    uint8_t x_5;
    lungo_obj x_6;
    x_5 = (uint8_t)lungo_unbox(x_2);
    x_6 = capdagFormal__l_CapDAG_dCapKind_dtransform_delim(x_1, x_5, x_3, x_4);
    lungo_dec(x_4);
    return x_6;
}

/* Lean: CapDAG.CapKind.transform.elim._redArg */
/* Compiled from: CapDAG.CapKind.transform.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:39 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dtransform_delim_d__redArg(lungo_obj x_1) {
    lungo_inc(x_1);
    return x_1;
}

/* Lean: CapDAG.CapKind.transform.elim._redArg._boxed */
/* Compiled from: CapDAG.CapKind.transform.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:112:39 */
lungo_obj capdagFormal__l_CapDAG_dCapKind_dtransform_delim_d__redArg_d__boxed(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = capdagFormal__l_CapDAG_dCapKind_dtransform_delim_d__redArg(x_1);
    lungo_dec(x_1);
    return x_2;
}

/* Lean: CapDAG.Effect.ctorElim */
/* Source: ../../../../formal/CapDAG/Cap.lean:25:1 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dctorElim(lungo_obj x_1, lungo_obj x_2, uint8_t x_3, lungo_obj x_4, lungo_obj x_5) {
    (void)x_1;
    (void)x_2;
    (void)x_3;
    (void)x_4;
    lungo_inc(x_5);
    return x_5;
}

/* Lean: CapDAG.Effect.ctorElim._boxed */
/* Compiled from: CapDAG.Effect.ctorElim */
/* Source: ../../../../formal/CapDAG/Cap.lean:25:1 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dctorElim_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5) {
    uint8_t x_6;
    lungo_obj x_7;
    x_6 = (uint8_t)lungo_unbox(x_3);
    x_7 = capdagFormal__l_CapDAG_dEffect_dctorElim(x_1, x_2, x_6, x_4, x_5);
    lungo_dec(x_5);
    lungo_dec(x_2);
    return x_7;
}

/* Lean: CapDAG.Effect.ctorElim._redArg */
/* Compiled from: CapDAG.Effect.ctorElim */
/* Source: ../../../../formal/CapDAG/Cap.lean:25:1 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dctorElim_d__redArg(lungo_obj x_1) {
    lungo_inc(x_1);
    return x_1;
}

/* Lean: CapDAG.Effect.ctorElim._redArg._boxed */
/* Compiled from: CapDAG.Effect.ctorElim */
/* Source: ../../../../formal/CapDAG/Cap.lean:25:1 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dctorElim_d__redArg_d__boxed(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = capdagFormal__l_CapDAG_dEffect_dctorElim_d__redArg(x_1);
    lungo_dec(x_1);
    return x_2;
}

/* Lean: CapDAG.Effect.ctorIdx */
/* Source: ../../../../formal/CapDAG/Cap.lean */
lungo_obj capdagFormal__l_CapDAG_dEffect_dctorIdx(uint8_t x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    switch (x_1) {
        case 0: {
            x_2 = lungo_usize_to_nat(0u);
            return x_2;
        }
        case 1: {
            x_3 = lungo_usize_to_nat(1u);
            return x_3;
        }
        case 2: {
            x_4 = lungo_usize_to_nat(2u);
            return x_4;
        }
        default: {
            x_5 = lungo_usize_to_nat(3u);
            return x_5;
        }
    }
}

/* Lean: CapDAG.Effect.ctorIdx._boxed */
/* Compiled from: CapDAG.Effect.ctorIdx */
/* Source: ../../../../formal/CapDAG/Cap.lean */
lungo_obj capdagFormal__l_CapDAG_dEffect_dctorIdx_d__boxed(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    x_2 = (uint8_t)lungo_unbox(x_1);
    x_3 = capdagFormal__l_CapDAG_dEffect_dctorIdx(x_2);
    return x_3;
}

/* Lean: CapDAG.Effect.declared.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:17 */
lungo_obj capdagFormal__l_CapDAG_dEffect_ddeclared_delim(lungo_obj x_1, uint8_t x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    (void)x_2;
    (void)x_3;
    lungo_inc(x_4);
    return x_4;
}

/* Lean: CapDAG.Effect.declared.elim._boxed */
/* Compiled from: CapDAG.Effect.declared.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:17 */
lungo_obj capdagFormal__l_CapDAG_dEffect_ddeclared_delim_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    uint8_t x_5;
    lungo_obj x_6;
    x_5 = (uint8_t)lungo_unbox(x_2);
    x_6 = capdagFormal__l_CapDAG_dEffect_ddeclared_delim(x_1, x_5, x_3, x_4);
    lungo_dec(x_4);
    return x_6;
}

/* Lean: CapDAG.Effect.declared.elim._redArg */
/* Compiled from: CapDAG.Effect.declared.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:17 */
lungo_obj capdagFormal__l_CapDAG_dEffect_ddeclared_delim_d__redArg(lungo_obj x_1) {
    lungo_inc(x_1);
    return x_1;
}

/* Lean: CapDAG.Effect.declared.elim._redArg._boxed */
/* Compiled from: CapDAG.Effect.declared.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:17 */
lungo_obj capdagFormal__l_CapDAG_dEffect_ddeclared_delim_d__redArg_d__boxed(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = capdagFormal__l_CapDAG_dEffect_ddeclared_delim_d__redArg(x_1);
    lungo_dec(x_1);
    return x_2;
}

/* Lean: CapDAG.Effect.none.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:28 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dnone_delim(lungo_obj x_1, uint8_t x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    (void)x_2;
    (void)x_3;
    lungo_inc(x_4);
    return x_4;
}

/* Lean: CapDAG.Effect.none.elim._boxed */
/* Compiled from: CapDAG.Effect.none.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:28 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dnone_delim_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    uint8_t x_5;
    lungo_obj x_6;
    x_5 = (uint8_t)lungo_unbox(x_2);
    x_6 = capdagFormal__l_CapDAG_dEffect_dnone_delim(x_1, x_5, x_3, x_4);
    lungo_dec(x_4);
    return x_6;
}

/* Lean: CapDAG.Effect.none.elim._redArg */
/* Compiled from: CapDAG.Effect.none.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:28 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dnone_delim_d__redArg(lungo_obj x_1) {
    lungo_inc(x_1);
    return x_1;
}

/* Lean: CapDAG.Effect.none.elim._redArg._boxed */
/* Compiled from: CapDAG.Effect.none.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:28 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dnone_delim_d__redArg_d__boxed(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = capdagFormal__l_CapDAG_dEffect_dnone_delim_d__redArg(x_1);
    lungo_dec(x_1);
    return x_2;
}

/* Lean: CapDAG.Effect.ofNat */
/* Source: ../../../../formal/CapDAG/Cap.lean */
uint8_t capdagFormal__l_CapDAG_dEffect_dofNat(lungo_obj x_1) {
    lungo_obj x_2;
    uint8_t x_3;
    lungo_obj x_4;
    uint8_t x_5;
    uint8_t x_6;
    uint8_t x_7;
    lungo_obj x_8;
    uint8_t x_9;
    uint8_t x_10;
    uint8_t x_11;
    x_2 = lungo_usize_to_nat(1u);
    x_3 = capdagFormal__l_Nat_dble(x_1, x_2);
    switch (x_3) {
        case 0: {
            x_4 = lungo_usize_to_nat(2u);
            x_5 = capdagFormal__l_Nat_dble(x_1, x_4);
            switch (x_5) {
                case 0: {
                    x_6 = (uint8_t)3u;
                    return x_6;
                }
                default: {
                    x_7 = (uint8_t)2u;
                    return x_7;
                }
            }
        }
        default: {
            x_8 = lungo_usize_to_nat(0u);
            x_9 = capdagFormal__l_Nat_dble(x_1, x_8);
            switch (x_9) {
                case 0: {
                    x_10 = (uint8_t)1u;
                    return x_10;
                }
                default: {
                    x_11 = (uint8_t)0u;
                    return x_11;
                }
            }
        }
    }
}

/* Lean: CapDAG.Effect.ofNat._boxed */
/* Compiled from: CapDAG.Effect.ofNat */
/* Source: ../../../../formal/CapDAG/Cap.lean */
lungo_obj capdagFormal__l_CapDAG_dEffect_dofNat_d__boxed(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    x_2 = capdagFormal__l_CapDAG_dEffect_dofNat(x_1);
    lungo_dec(x_1);
    x_3 = lungo_box((size_t)x_2);
    return x_3;
}

/* Lean: CapDAG.Effect.patch.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:35 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dpatch_delim(lungo_obj x_1, uint8_t x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    (void)x_2;
    (void)x_3;
    lungo_inc(x_4);
    return x_4;
}

/* Lean: CapDAG.Effect.patch.elim._boxed */
/* Compiled from: CapDAG.Effect.patch.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:35 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dpatch_delim_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    uint8_t x_5;
    lungo_obj x_6;
    x_5 = (uint8_t)lungo_unbox(x_2);
    x_6 = capdagFormal__l_CapDAG_dEffect_dpatch_delim(x_1, x_5, x_3, x_4);
    lungo_dec(x_4);
    return x_6;
}

/* Lean: CapDAG.Effect.patch.elim._redArg */
/* Compiled from: CapDAG.Effect.patch.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:35 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dpatch_delim_d__redArg(lungo_obj x_1) {
    lungo_inc(x_1);
    return x_1;
}

/* Lean: CapDAG.Effect.patch.elim._redArg._boxed */
/* Compiled from: CapDAG.Effect.patch.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:35 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dpatch_delim_d__redArg_d__boxed(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = capdagFormal__l_CapDAG_dEffect_dpatch_delim_d__redArg(x_1);
    lungo_dec(x_1);
    return x_2;
}

/* Lean: CapDAG.Effect.unspecified.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:3 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dunspecified_delim(lungo_obj x_1, uint8_t x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    (void)x_2;
    (void)x_3;
    lungo_inc(x_4);
    return x_4;
}

/* Lean: CapDAG.Effect.unspecified.elim._boxed */
/* Compiled from: CapDAG.Effect.unspecified.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:3 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dunspecified_delim_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    uint8_t x_5;
    lungo_obj x_6;
    x_5 = (uint8_t)lungo_unbox(x_2);
    x_6 = capdagFormal__l_CapDAG_dEffect_dunspecified_delim(x_1, x_5, x_3, x_4);
    lungo_dec(x_4);
    return x_6;
}

/* Lean: CapDAG.Effect.unspecified.elim._redArg */
/* Compiled from: CapDAG.Effect.unspecified.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:3 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dunspecified_delim_d__redArg(lungo_obj x_1) {
    lungo_inc(x_1);
    return x_1;
}

/* Lean: CapDAG.Effect.unspecified.elim._redArg._boxed */
/* Compiled from: CapDAG.Effect.unspecified.elim */
/* Source: ../../../../formal/CapDAG/Cap.lean:26:3 */
lungo_obj capdagFormal__l_CapDAG_dEffect_dunspecified_delim_d__redArg_d__boxed(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = capdagFormal__l_CapDAG_dEffect_dunspecified_delim_d__redArg(x_1);
    lungo_dec(x_1);
    return x_2;
}

/* Lean: CapDAG.instDecidableAccepts */
/* Source: ../../../../formal/CapDAG/Cap.lean:71:1 */
uint8_t capdagFormal__l_CapDAG_dinstDecidableAccepts(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    uint8_t x_10;
    uint8_t x_11;
    uint8_t x_12;
    uint8_t x_13;
    uint8_t x_14;
    uint8_t x_15;
    uint8_t x_16;
    uint8_t x_17;
    x_3 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_3);
    x_4 = lungo_ctor_get(x_2, 1);
    lungo_inc_ref(x_4);
    x_5 = lungo_ctor_get(x_2, 2);
    lungo_inc_ref(x_5);
    x_6 = lungo_ctor_get_uint8(x_2, 3 * sizeof(size_t));
    lungo_dec_ref(x_2);
    x_7 = lungo_ctor_get(x_1, 0);
    lungo_inc_ref(x_7);
    x_8 = lungo_ctor_get(x_1, 1);
    lungo_inc_ref(x_8);
    x_9 = lungo_ctor_get(x_1, 2);
    lungo_inc_ref(x_9);
    x_10 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    lungo_dec_ref(x_1);
    x_11 = capdagFormal__l_TaggedUrn_dinstDecidableRefines(x_3, x_7);
    switch (x_11) {
        case 0: {
            lungo_dec_ref(x_9);
            lungo_dec_ref(x_8);
            lungo_dec_ref(x_5);
            lungo_dec_ref(x_4);
            return x_11;
        }
        default: {
            x_12 = capdagFormal__l_TaggedUrn_dinstDecidableRefines(x_8, x_4);
            switch (x_12) {
                case 0: {
                    lungo_dec_ref(x_9);
                    lungo_dec_ref(x_5);
                    return x_12;
                }
                default: {
                    x_13 = (uint8_t)0u;
                    x_14 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_10, x_13);
                    switch (x_14) {
                        case 0: {
                            x_15 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_10, x_6);
                            switch (x_15) {
                                case 0: {
                                    lungo_dec_ref(x_9);
                                    lungo_dec_ref(x_5);
                                    return x_15;
                                }
                                default: {
                                    x_16 = capdagFormal__l_TaggedUrn_dinstDecidableRefines(x_5, x_9);
                                    return x_16;
                                }
                            }
                        }
                        default: {
                            x_17 = capdagFormal__l_TaggedUrn_dinstDecidableRefines(x_5, x_9);
                            return x_17;
                        }
                    }
                }
            }
        }
    }
}

/* Lean: CapDAG.instDecidableAccepts._boxed */
/* Compiled from: CapDAG.instDecidableAccepts */
/* Source: ../../../../formal/CapDAG/Cap.lean:71:1 */
lungo_obj capdagFormal__l_CapDAG_dinstDecidableAccepts_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dinstDecidableAccepts(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.instDecidableDispatch */
/* Source: ../../../../formal/CapDAG/Cap.lean:58:1 */
uint8_t capdagFormal__l_CapDAG_dinstDecidableDispatch(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    uint8_t x_10;
    uint8_t x_11;
    uint8_t x_12;
    uint8_t x_13;
    uint8_t x_14;
    x_3 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_3);
    x_4 = lungo_ctor_get(x_2, 1);
    lungo_inc_ref(x_4);
    x_5 = lungo_ctor_get(x_2, 2);
    lungo_inc_ref(x_5);
    x_6 = lungo_ctor_get_uint8(x_2, 3 * sizeof(size_t));
    lungo_dec_ref(x_2);
    x_7 = lungo_ctor_get(x_1, 0);
    lungo_inc_ref(x_7);
    x_8 = lungo_ctor_get(x_1, 1);
    lungo_inc_ref(x_8);
    x_9 = lungo_ctor_get(x_1, 2);
    lungo_inc_ref(x_9);
    x_10 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    lungo_dec_ref(x_1);
    x_11 = capdagFormal__l_TaggedUrn_dinstDecidableRefines(x_3, x_7);
    switch (x_11) {
        case 0: {
            lungo_dec_ref(x_9);
            lungo_dec_ref(x_8);
            lungo_dec_ref(x_5);
            lungo_dec_ref(x_4);
            return x_11;
        }
        default: {
            x_12 = capdagFormal__l_TaggedUrn_dinstDecidableRefines(x_8, x_4);
            switch (x_12) {
                case 0: {
                    lungo_dec_ref(x_9);
                    lungo_dec_ref(x_5);
                    return x_12;
                }
                default: {
                    x_13 = capdagFormal__l_CapDAG_dinstDecidableEffectOk(x_10, x_6);
                    switch (x_13) {
                        case 0: {
                            lungo_dec_ref(x_9);
                            lungo_dec_ref(x_5);
                            return x_13;
                        }
                        default: {
                            x_14 = capdagFormal__l_TaggedUrn_dinstDecidableRefines(x_9, x_5);
                            return x_14;
                        }
                    }
                }
            }
        }
    }
}

/* Lean: CapDAG.instDecidableDispatch._boxed */
/* Compiled from: CapDAG.instDecidableDispatch */
/* Source: ../../../../formal/CapDAG/Cap.lean:58:1 */
lungo_obj capdagFormal__l_CapDAG_dinstDecidableDispatch_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dinstDecidableDispatch(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.instDecidableEffectOk */
/* Source: ../../../../formal/CapDAG/Cap.lean:49:1 */
uint8_t capdagFormal__l_CapDAG_dinstDecidableEffectOk(uint8_t x_1, uint8_t x_2) {
    uint8_t x_3;
    uint8_t x_4;
    uint8_t x_5;
    x_3 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_1, x_2);
    x_4 = (uint8_t)0u;
    x_5 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_2, x_4);
    switch (x_5) {
        case 0: {
            return x_3;
        }
        default: {
            return x_5;
        }
    }
}

/* Lean: CapDAG.instDecidableEffectOk._boxed */
/* Compiled from: CapDAG.instDecidableEffectOk */
/* Source: ../../../../formal/CapDAG/Cap.lean:49:1 */
lungo_obj capdagFormal__l_CapDAG_dinstDecidableEffectOk_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    uint8_t x_4;
    uint8_t x_5;
    lungo_obj x_6;
    x_3 = (uint8_t)lungo_unbox(x_1);
    x_4 = (uint8_t)lungo_unbox(x_2);
    x_5 = capdagFormal__l_CapDAG_dinstDecidableEffectOk(x_3, x_4);
    x_6 = lungo_box((size_t)x_5);
    return x_6;
}

/* Lean: CapDAG.instDecidableEqCap */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:18 */
uint8_t capdagFormal__l_CapDAG_dinstDecidableEqCap(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    x_3 = capdagFormal__l_CapDAG_dinstDecidableEqCap_ddecEq(x_1, x_2);
    return x_3;
}

/* Lean: CapDAG.instDecidableEqCap._boxed */
/* Compiled from: CapDAG.instDecidableEqCap */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:18 */
lungo_obj capdagFormal__l_CapDAG_dinstDecidableEqCap_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dinstDecidableEqCap(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.instDecidableEqCap.decEq */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:18 */
uint8_t capdagFormal__l_CapDAG_dinstDecidableEqCap_ddecEq(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    uint8_t x_10;
    uint8_t x_11;
    uint8_t x_12;
    uint8_t x_13;
    uint8_t x_14;
    x_3 = lungo_ctor_get(x_1, 0);
    lungo_inc_ref(x_3);
    x_4 = lungo_ctor_get(x_1, 1);
    lungo_inc_ref(x_4);
    x_5 = lungo_ctor_get(x_1, 2);
    lungo_inc_ref(x_5);
    x_6 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    lungo_dec_ref(x_1);
    x_7 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_7);
    x_8 = lungo_ctor_get(x_2, 1);
    lungo_inc_ref(x_8);
    x_9 = lungo_ctor_get(x_2, 2);
    lungo_inc_ref(x_9);
    x_10 = lungo_ctor_get_uint8(x_2, 3 * sizeof(size_t));
    lungo_dec_ref(x_2);
    x_11 = capdagFormal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq(x_3, x_7);
    switch (x_11) {
        case 0: {
            lungo_dec_ref(x_9);
            lungo_dec_ref(x_8);
            lungo_dec_ref(x_5);
            lungo_dec_ref(x_4);
            return x_11;
        }
        default: {
            x_12 = capdagFormal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq(x_4, x_8);
            switch (x_12) {
                case 0: {
                    lungo_dec_ref(x_9);
                    lungo_dec_ref(x_5);
                    return x_12;
                }
                default: {
                    x_13 = capdagFormal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq(x_5, x_9);
                    switch (x_13) {
                        case 0: {
                            return x_13;
                        }
                        default: {
                            x_14 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_6, x_10);
                            return x_14;
                        }
                    }
                }
            }
        }
    }
}

/* Lean: CapDAG.instDecidableEqCap.decEq._boxed */
/* Compiled from: CapDAG.instDecidableEqCap.decEq */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:18 */
lungo_obj capdagFormal__l_CapDAG_dinstDecidableEqCap_ddecEq_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dinstDecidableEqCap_ddecEq(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.instDecidableEqCapKind */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:12 */
uint8_t capdagFormal__l_CapDAG_dinstDecidableEqCapKind(uint8_t x_1, uint8_t x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    x_3 = capdagFormal__l_CapDAG_dCapKind_dctorIdx(x_1);
    x_4 = capdagFormal__l_CapDAG_dCapKind_dctorIdx(x_2);
    x_5 = capdagFormal__l_Nat_ddecEq(x_3, x_4);
    lungo_dec(x_4);
    lungo_dec(x_3);
    return x_5;
}

/* Lean: CapDAG.instDecidableEqCapKind._boxed */
/* Compiled from: CapDAG.instDecidableEqCapKind */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:12 */
lungo_obj capdagFormal__l_CapDAG_dinstDecidableEqCapKind_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    uint8_t x_4;
    uint8_t x_5;
    lungo_obj x_6;
    x_3 = (uint8_t)lungo_unbox(x_1);
    x_4 = (uint8_t)lungo_unbox(x_2);
    x_5 = capdagFormal__l_CapDAG_dinstDecidableEqCapKind(x_3, x_4);
    x_6 = lungo_box((size_t)x_5);
    return x_6;
}

/* Lean: CapDAG.instDecidableEqEffect */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:12 */
uint8_t capdagFormal__l_CapDAG_dinstDecidableEqEffect(uint8_t x_1, uint8_t x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    x_3 = capdagFormal__l_CapDAG_dEffect_dctorIdx(x_1);
    x_4 = capdagFormal__l_CapDAG_dEffect_dctorIdx(x_2);
    x_5 = capdagFormal__l_Nat_ddecEq(x_3, x_4);
    lungo_dec(x_4);
    lungo_dec(x_3);
    return x_5;
}

/* Lean: CapDAG.instDecidableEqEffect._boxed */
/* Compiled from: CapDAG.instDecidableEqEffect */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:12 */
lungo_obj capdagFormal__l_CapDAG_dinstDecidableEqEffect_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    uint8_t x_4;
    uint8_t x_5;
    lungo_obj x_6;
    x_3 = (uint8_t)lungo_unbox(x_1);
    x_4 = (uint8_t)lungo_unbox(x_2);
    x_5 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_3, x_4);
    x_6 = lungo_box((size_t)x_5);
    return x_6;
}

/* Lean: CapDAG.instDecidableUnconstrainedMedia */
/* Source: ../../../../formal/CapDAG/Cap.lean:43:1 */
uint8_t capdagFormal__l_CapDAG_dinstDecidableUnconstrainedMedia(lungo_obj x_1) {
    lungo_obj x_2;
    uint8_t x_3;
    x_2 = capdagFormal__l_CapDAG_dmediaTop();
    x_3 = capdagFormal__l_TaggedUrn_dinstDecidableRefines(x_2, x_1);
    return x_3;
}

/* Lean: CapDAG.instDecidableUnconstrainedMedia._boxed */
/* Compiled from: CapDAG.instDecidableUnconstrainedMedia */
/* Source: ../../../../formal/CapDAG/Cap.lean:43:1 */
lungo_obj capdagFormal__l_CapDAG_dinstDecidableUnconstrainedMedia_d__boxed(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    x_2 = capdagFormal__l_CapDAG_dinstDecidableUnconstrainedMedia(x_1);
    x_3 = lungo_box((size_t)x_2);
    return x_3;
}

/* Lean: CapDAG.instReprCap */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap__init(void) {
    lungo_obj x_1;
    x_1 = capdagFormal__l_CapDAG_dinstReprCap_d__closed__0();
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap__cell, capdagFormal__l_CapDAG_dinstReprCap__init);
}

/* Lean: CapDAG.instReprCap._closed_0 */
/* Compiled from: CapDAG.instReprCap */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_alloc_closure((void *)capdagFormal__l_CapDAG_dinstReprCap_drepr_d__boxed, 2, 0);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_d__closed__0__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_d__closed__0__cell, capdagFormal__l_CapDAG_dinstReprCap_d__closed__0__init);
}

/* Lean: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr(lungo_obj x_1, lungo_obj x_2) {
    (void)x_2;
    lungo_obj x_3;
    x_3 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg(x_1);
    return x_3;
}

/* Lean: CapDAG.instReprCap.repr._boxed */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = capdagFormal__l_CapDAG_dinstReprCap_drepr(x_1, x_2);
    lungo_dec(x_2);
    return x_3;
}

/* Lean: CapDAG.instReprCap.repr._redArg */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    uint8_t x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    lungo_obj x_15;
    lungo_obj x_16;
    lungo_obj x_17;
    lungo_obj x_18;
    lungo_obj x_19;
    lungo_obj x_20;
    lungo_obj x_21;
    lungo_obj x_22;
    lungo_obj x_23;
    lungo_obj x_24;
    lungo_obj x_25;
    lungo_obj x_26;
    lungo_obj x_27;
    lungo_obj x_28;
    lungo_obj x_29;
    lungo_obj x_30;
    lungo_obj x_31;
    lungo_obj x_32;
    lungo_obj x_33;
    lungo_obj x_34;
    lungo_obj x_35;
    lungo_obj x_36;
    lungo_obj x_37;
    lungo_obj x_38;
    lungo_obj x_39;
    lungo_obj x_40;
    lungo_obj x_41;
    lungo_obj x_42;
    lungo_obj x_43;
    lungo_obj x_44;
    lungo_obj x_45;
    lungo_obj x_46;
    lungo_obj x_47;
    lungo_obj x_48;
    lungo_obj x_49;
    lungo_obj x_50;
    lungo_obj x_51;
    x_2 = lungo_ctor_get(x_1, 0);
    lungo_inc_ref(x_2);
    x_3 = lungo_ctor_get(x_1, 1);
    lungo_inc_ref(x_3);
    x_4 = lungo_ctor_get(x_1, 2);
    lungo_inc_ref(x_4);
    x_5 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    lungo_dec_ref(x_1);
    x_6 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__5();
    x_7 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__6();
    x_8 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__7();
    x_9 = lungo_usize_to_nat(0u);
    x_10 = capdagFormal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg(x_2);
    x_11 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_11, 0, x_8);
    lungo_ctor_set(x_11, 1, x_10);
    x_12 = (uint8_t)0u;
    x_13 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_13, 0, x_11);
    lungo_ctor_set_uint8(x_13, 1 * sizeof(size_t), x_12);
    x_14 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_14, 0, x_7);
    lungo_ctor_set(x_14, 1, x_13);
    x_15 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__9();
    x_16 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_16, 0, x_14);
    lungo_ctor_set(x_16, 1, x_15);
    x_17 = lungo_box(1);
    x_18 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_18, 0, x_16);
    lungo_ctor_set(x_18, 1, x_17);
    x_19 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__11();
    x_20 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_20, 0, x_18);
    lungo_ctor_set(x_20, 1, x_19);
    x_21 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_21, 0, x_20);
    lungo_ctor_set(x_21, 1, x_6);
    x_22 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__12();
    x_23 = capdagFormal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg(x_3);
    x_24 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_24, 0, x_22);
    lungo_ctor_set(x_24, 1, x_23);
    x_25 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_25, 0, x_24);
    lungo_ctor_set_uint8(x_25, 1 * sizeof(size_t), x_12);
    x_26 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_26, 0, x_21);
    lungo_ctor_set(x_26, 1, x_25);
    x_27 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_27, 0, x_26);
    lungo_ctor_set(x_27, 1, x_15);
    x_28 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_28, 0, x_27);
    lungo_ctor_set(x_28, 1, x_17);
    x_29 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__14();
    x_30 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_30, 0, x_28);
    lungo_ctor_set(x_30, 1, x_29);
    x_31 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_31, 0, x_30);
    lungo_ctor_set(x_31, 1, x_6);
    x_32 = capdagFormal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg(x_4);
    x_33 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_33, 0, x_8);
    lungo_ctor_set(x_33, 1, x_32);
    x_34 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_34, 0, x_33);
    lungo_ctor_set_uint8(x_34, 1 * sizeof(size_t), x_12);
    x_35 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_35, 0, x_31);
    lungo_ctor_set(x_35, 1, x_34);
    x_36 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_36, 0, x_35);
    lungo_ctor_set(x_36, 1, x_15);
    x_37 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_37, 0, x_36);
    lungo_ctor_set(x_37, 1, x_17);
    x_38 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__16();
    x_39 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_39, 0, x_37);
    lungo_ctor_set(x_39, 1, x_38);
    x_40 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_40, 0, x_39);
    lungo_ctor_set(x_40, 1, x_6);
    x_41 = capdagFormal__l_CapDAG_dinstReprEffect_drepr(x_5, x_9);
    x_42 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_42, 0, x_22);
    lungo_ctor_set(x_42, 1, x_41);
    x_43 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_43, 0, x_42);
    lungo_ctor_set_uint8(x_43, 1 * sizeof(size_t), x_12);
    x_44 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_44, 0, x_40);
    lungo_ctor_set(x_44, 1, x_43);
    x_45 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__19();
    x_46 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__20();
    x_47 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_47, 0, x_46);
    lungo_ctor_set(x_47, 1, x_44);
    x_48 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__21();
    x_49 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_49, 0, x_47);
    lungo_ctor_set(x_49, 1, x_48);
    x_50 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_50, 0, x_45);
    lungo_ctor_set(x_50, 1, x_49);
    x_51 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_51, 0, x_50);
    lungo_ctor_set_uint8(x_51, 1 * sizeof(size_t), x_12);
    return x_51;
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_0 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"{ ", 2, 2);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__0__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__0__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__0__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_1 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__1__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"input", 5, 5);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__1__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__1(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__1__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__1__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_10 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__10__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"output", 6, 6);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__10__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__10(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__10__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__10__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_11 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__11__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__10();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__11__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__11(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__11__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__11__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_12 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__12__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = lungo_usize_to_nat(10u);
    x_2 = capdagFormal__l_Int_dofNat(x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__12__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__12(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__12__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__12__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_13 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__13__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"other", 5, 5);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__13__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__13(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__13__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__13__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_14 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__14__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__13();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__14__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__14(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__14__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__14__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_15 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__15__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"effect", 6, 6);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__15__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__15(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__15__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__15__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_16 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__16__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__15();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__16__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__16(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__16__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__16__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_17 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__17__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)" }", 2, 2);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__17__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__17(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__17__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__17__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_18 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__18__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__0();
    x_2 = capdagFormal__l_String_dInternal_dlength(x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__18__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__18(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__18__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__18__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_19 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__19__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__18();
    x_2 = capdagFormal__l_Int_dofNat(x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__19__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__19(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__19__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__19__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_2 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__2__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__1();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__2__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__2(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__2__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__2__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_20 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__20__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__0();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__20__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__20(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__20__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__20__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_21 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__21__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__17();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__21__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__21(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__21__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__21__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_3 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__3__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    lungo_obj x_3;
    x_1 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__2();
    x_2 = lungo_box(0);
    x_3 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set(x_3, 1, x_1);
    return x_3;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__3__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__3(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__3__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__3__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_4 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__4__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)" := ", 4, 4);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__4__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__4(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__4__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__4__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_5 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__5__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__4();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__5__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__5(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__5__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__5__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_6 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__6__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    lungo_obj x_3;
    x_1 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__5();
    x_2 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__3();
    x_3 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set(x_3, 1, x_1);
    return x_3;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__6__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__6(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__6__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__6__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_7 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__7__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = lungo_usize_to_nat(9u);
    x_2 = capdagFormal__l_Int_dofNat(x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__7__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__7(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__7__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__7__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_8 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__8__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)",", 1, 1);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__8__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__8(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__8__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__8__init);
}

/* Lean: CapDAG.instReprCap.repr._redArg._closed_9 */
/* Compiled from: CapDAG.instReprCap.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:34:12 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__9__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__8();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__9__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__9(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__9__cell, capdagFormal__l_CapDAG_dinstReprCap_drepr_d__redArg_d__closed__9__init);
}

/* Lean: CapDAG.instReprCapKind */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind__init(void) {
    lungo_obj x_1;
    x_1 = capdagFormal__l_CapDAG_dinstReprCapKind_d__closed__0();
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCapKind__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCapKind__cell, capdagFormal__l_CapDAG_dinstReprCapKind__init);
}

/* Lean: CapDAG.instReprCapKind._closed_0 */
/* Compiled from: CapDAG.instReprCapKind */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_alloc_closure((void *)capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__boxed, 2, 0);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCapKind_d__closed__0__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCapKind_d__closed__0__cell, capdagFormal__l_CapDAG_dinstReprCapKind_d__closed__0__init);
}

/* Lean: CapDAG.instReprCapKind.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:25 */
lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr(uint8_t x_1, lungo_obj x_2) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    uint8_t x_14;
    lungo_obj x_15;
    lungo_obj x_16;
    lungo_obj x_18;
    lungo_obj x_19;
    lungo_obj x_20;
    uint8_t x_21;
    lungo_obj x_22;
    lungo_obj x_23;
    lungo_obj x_25;
    lungo_obj x_26;
    lungo_obj x_27;
    uint8_t x_28;
    lungo_obj x_29;
    lungo_obj x_30;
    lungo_obj x_32;
    lungo_obj x_33;
    lungo_obj x_34;
    uint8_t x_35;
    lungo_obj x_36;
    lungo_obj x_37;
    lungo_obj x_38;
    uint8_t x_39;
    lungo_obj x_40;
    lungo_obj x_41;
    lungo_obj x_42;
    uint8_t x_43;
    lungo_obj x_44;
    lungo_obj x_45;
    lungo_obj x_46;
    uint8_t x_47;
    lungo_obj x_48;
    lungo_obj x_49;
    lungo_obj x_50;
    uint8_t x_51;
    lungo_obj x_52;
    lungo_obj x_53;
    lungo_obj x_54;
    uint8_t x_55;
    lungo_obj x_56;
    lungo_obj x_57;
    switch (x_1) {
        case 0: {
            x_38 = lungo_usize_to_nat(1024u);
            x_39 = capdagFormal__l_Nat_ddecLe(x_38, x_2);
            switch (x_39) {
                case 0: {
                    x_40 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__8();
                    x_4 = x_40;
                    goto block_3;
                }
                default: {
                    x_41 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__9();
                    x_4 = x_41;
                    goto block_3;
                }
            }
        }
        case 1: {
            x_42 = lungo_usize_to_nat(1024u);
            x_43 = capdagFormal__l_Nat_ddecLe(x_42, x_2);
            switch (x_43) {
                case 0: {
                    x_44 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__8();
                    x_11 = x_44;
                    goto block_10;
                }
                default: {
                    x_45 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__9();
                    x_11 = x_45;
                    goto block_10;
                }
            }
        }
        case 2: {
            x_46 = lungo_usize_to_nat(1024u);
            x_47 = capdagFormal__l_Nat_ddecLe(x_46, x_2);
            switch (x_47) {
                case 0: {
                    x_48 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__8();
                    x_18 = x_48;
                    goto block_17;
                }
                default: {
                    x_49 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__9();
                    x_18 = x_49;
                    goto block_17;
                }
            }
        }
        case 3: {
            x_50 = lungo_usize_to_nat(1024u);
            x_51 = capdagFormal__l_Nat_ddecLe(x_50, x_2);
            switch (x_51) {
                case 0: {
                    x_52 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__8();
                    x_25 = x_52;
                    goto block_24;
                }
                default: {
                    x_53 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__9();
                    x_25 = x_53;
                    goto block_24;
                }
            }
        }
        default: {
            x_54 = lungo_usize_to_nat(1024u);
            x_55 = capdagFormal__l_Nat_ddecLe(x_54, x_2);
            switch (x_55) {
                case 0: {
                    x_56 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__8();
                    x_32 = x_56;
                    goto block_31;
                }
                default: {
                    x_57 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__9();
                    x_32 = x_57;
                    goto block_31;
                }
            }
        }
    }
    block_31:;
    x_33 = capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__9();
    lungo_inc(x_32);
    x_34 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_34, 0, x_32);
    lungo_ctor_set(x_34, 1, x_33);
    x_35 = (uint8_t)0u;
    x_36 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_36, 0, x_34);
    lungo_ctor_set_uint8(x_36, 1 * sizeof(size_t), x_35);
    x_37 = capdagFormal__l_Repr_daddAppParen(x_36, x_2);
    return x_37;
    block_24:;
    x_26 = capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__7();
    lungo_inc(x_25);
    x_27 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_27, 0, x_25);
    lungo_ctor_set(x_27, 1, x_26);
    x_28 = (uint8_t)0u;
    x_29 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_29, 0, x_27);
    lungo_ctor_set_uint8(x_29, 1 * sizeof(size_t), x_28);
    x_30 = capdagFormal__l_Repr_daddAppParen(x_29, x_2);
    return x_30;
    block_17:;
    x_19 = capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__5();
    lungo_inc(x_18);
    x_20 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_20, 0, x_18);
    lungo_ctor_set(x_20, 1, x_19);
    x_21 = (uint8_t)0u;
    x_22 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_22, 0, x_20);
    lungo_ctor_set_uint8(x_22, 1 * sizeof(size_t), x_21);
    x_23 = capdagFormal__l_Repr_daddAppParen(x_22, x_2);
    return x_23;
    block_10:;
    x_12 = capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__3();
    lungo_inc(x_11);
    x_13 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_13, 0, x_11);
    lungo_ctor_set(x_13, 1, x_12);
    x_14 = (uint8_t)0u;
    x_15 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_15, 0, x_13);
    lungo_ctor_set_uint8(x_15, 1 * sizeof(size_t), x_14);
    x_16 = capdagFormal__l_Repr_daddAppParen(x_15, x_2);
    return x_16;
    block_3:;
    x_5 = capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__1();
    lungo_inc(x_4);
    x_6 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_6, 0, x_4);
    lungo_ctor_set(x_6, 1, x_5);
    x_7 = (uint8_t)0u;
    x_8 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_8, 0, x_6);
    lungo_ctor_set_uint8(x_8, 1 * sizeof(size_t), x_7);
    x_9 = capdagFormal__l_Repr_daddAppParen(x_8, x_2);
    return x_9;
}

/* Lean: CapDAG.instReprCapKind.repr._boxed */
/* Compiled from: CapDAG.instReprCapKind.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:25 */
lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = (uint8_t)lungo_unbox(x_1);
    x_4 = capdagFormal__l_CapDAG_dinstReprCapKind_drepr(x_3, x_2);
    lungo_dec(x_2);
    return x_4;
}

/* Lean: CapDAG.instReprCapKind.repr._closed_0 */
/* Compiled from: CapDAG.instReprCapKind.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"CapDAG.CapKind.identity", 23, 23);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__0__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__0__cell, capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__0__init);
}

/* Lean: CapDAG.instReprCapKind.repr._closed_1 */
/* Compiled from: CapDAG.instReprCapKind.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__1__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__0();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__1__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__1(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__1__cell, capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__1__init);
}

/* Lean: CapDAG.instReprCapKind.repr._closed_2 */
/* Compiled from: CapDAG.instReprCapKind.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__2__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"CapDAG.CapKind.source", 21, 21);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__2__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__2(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__2__cell, capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__2__init);
}

/* Lean: CapDAG.instReprCapKind.repr._closed_3 */
/* Compiled from: CapDAG.instReprCapKind.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__3__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__2();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__3__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__3(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__3__cell, capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__3__init);
}

/* Lean: CapDAG.instReprCapKind.repr._closed_4 */
/* Compiled from: CapDAG.instReprCapKind.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__4__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"CapDAG.CapKind.sink", 19, 19);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__4__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__4(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__4__cell, capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__4__init);
}

/* Lean: CapDAG.instReprCapKind.repr._closed_5 */
/* Compiled from: CapDAG.instReprCapKind.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__5__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__4();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__5__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__5(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__5__cell, capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__5__init);
}

/* Lean: CapDAG.instReprCapKind.repr._closed_6 */
/* Compiled from: CapDAG.instReprCapKind.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__6__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"CapDAG.CapKind.effect", 21, 21);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__6__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__6(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__6__cell, capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__6__init);
}

/* Lean: CapDAG.instReprCapKind.repr._closed_7 */
/* Compiled from: CapDAG.instReprCapKind.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__7__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__6();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__7__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__7(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__7__cell, capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__7__init);
}

/* Lean: CapDAG.instReprCapKind.repr._closed_8 */
/* Compiled from: CapDAG.instReprCapKind.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__8__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"CapDAG.CapKind.transform", 24, 24);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__8__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__8(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__8__cell, capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__8__init);
}

/* Lean: CapDAG.instReprCapKind.repr._closed_9 */
/* Compiled from: CapDAG.instReprCapKind.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:113:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__9__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__8();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__9__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__9(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__9__cell, capdagFormal__l_CapDAG_dinstReprCapKind_drepr_d__closed__9__init);
}

/* Lean: CapDAG.instReprEffect */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprEffect__init(void) {
    lungo_obj x_1;
    x_1 = capdagFormal__l_CapDAG_dinstReprEffect_d__closed__0();
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprEffect__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprEffect(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprEffect__cell, capdagFormal__l_CapDAG_dinstReprEffect__init);
}

/* Lean: CapDAG.instReprEffect._closed_0 */
/* Compiled from: CapDAG.instReprEffect */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_alloc_closure((void *)capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__boxed, 2, 0);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprEffect_d__closed__0__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprEffect_d__closed__0__cell, capdagFormal__l_CapDAG_dinstReprEffect_d__closed__0__init);
}

/* Lean: CapDAG.instReprEffect.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:25 */
lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr(uint8_t x_1, lungo_obj x_2) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    uint8_t x_14;
    lungo_obj x_15;
    lungo_obj x_16;
    lungo_obj x_18;
    lungo_obj x_19;
    lungo_obj x_20;
    uint8_t x_21;
    lungo_obj x_22;
    lungo_obj x_23;
    lungo_obj x_25;
    lungo_obj x_26;
    lungo_obj x_27;
    uint8_t x_28;
    lungo_obj x_29;
    lungo_obj x_30;
    lungo_obj x_31;
    uint8_t x_32;
    lungo_obj x_33;
    lungo_obj x_34;
    lungo_obj x_35;
    uint8_t x_36;
    lungo_obj x_37;
    lungo_obj x_38;
    lungo_obj x_39;
    uint8_t x_40;
    lungo_obj x_41;
    lungo_obj x_42;
    lungo_obj x_43;
    uint8_t x_44;
    lungo_obj x_45;
    lungo_obj x_46;
    switch (x_1) {
        case 0: {
            x_31 = lungo_usize_to_nat(1024u);
            x_32 = capdagFormal__l_Nat_ddecLe(x_31, x_2);
            switch (x_32) {
                case 0: {
                    x_33 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__8();
                    x_4 = x_33;
                    goto block_3;
                }
                default: {
                    x_34 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__9();
                    x_4 = x_34;
                    goto block_3;
                }
            }
        }
        case 1: {
            x_35 = lungo_usize_to_nat(1024u);
            x_36 = capdagFormal__l_Nat_ddecLe(x_35, x_2);
            switch (x_36) {
                case 0: {
                    x_37 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__8();
                    x_11 = x_37;
                    goto block_10;
                }
                default: {
                    x_38 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__9();
                    x_11 = x_38;
                    goto block_10;
                }
            }
        }
        case 2: {
            x_39 = lungo_usize_to_nat(1024u);
            x_40 = capdagFormal__l_Nat_ddecLe(x_39, x_2);
            switch (x_40) {
                case 0: {
                    x_41 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__8();
                    x_18 = x_41;
                    goto block_17;
                }
                default: {
                    x_42 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__9();
                    x_18 = x_42;
                    goto block_17;
                }
            }
        }
        default: {
            x_43 = lungo_usize_to_nat(1024u);
            x_44 = capdagFormal__l_Nat_ddecLe(x_43, x_2);
            switch (x_44) {
                case 0: {
                    x_45 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__8();
                    x_25 = x_45;
                    goto block_24;
                }
                default: {
                    x_46 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__9();
                    x_25 = x_46;
                    goto block_24;
                }
            }
        }
    }
    block_24:;
    x_26 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__7();
    lungo_inc(x_25);
    x_27 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_27, 0, x_25);
    lungo_ctor_set(x_27, 1, x_26);
    x_28 = (uint8_t)0u;
    x_29 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_29, 0, x_27);
    lungo_ctor_set_uint8(x_29, 1 * sizeof(size_t), x_28);
    x_30 = capdagFormal__l_Repr_daddAppParen(x_29, x_2);
    return x_30;
    block_17:;
    x_19 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__5();
    lungo_inc(x_18);
    x_20 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_20, 0, x_18);
    lungo_ctor_set(x_20, 1, x_19);
    x_21 = (uint8_t)0u;
    x_22 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_22, 0, x_20);
    lungo_ctor_set_uint8(x_22, 1 * sizeof(size_t), x_21);
    x_23 = capdagFormal__l_Repr_daddAppParen(x_22, x_2);
    return x_23;
    block_10:;
    x_12 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__3();
    lungo_inc(x_11);
    x_13 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_13, 0, x_11);
    lungo_ctor_set(x_13, 1, x_12);
    x_14 = (uint8_t)0u;
    x_15 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_15, 0, x_13);
    lungo_ctor_set_uint8(x_15, 1 * sizeof(size_t), x_14);
    x_16 = capdagFormal__l_Repr_daddAppParen(x_15, x_2);
    return x_16;
    block_3:;
    x_5 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__1();
    lungo_inc(x_4);
    x_6 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_6, 0, x_4);
    lungo_ctor_set(x_6, 1, x_5);
    x_7 = (uint8_t)0u;
    x_8 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_8, 0, x_6);
    lungo_ctor_set_uint8(x_8, 1 * sizeof(size_t), x_7);
    x_9 = capdagFormal__l_Repr_daddAppParen(x_8, x_2);
    return x_9;
}

/* Lean: CapDAG.instReprEffect.repr._boxed */
/* Compiled from: CapDAG.instReprEffect.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:25 */
lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = (uint8_t)lungo_unbox(x_1);
    x_4 = capdagFormal__l_CapDAG_dinstReprEffect_drepr(x_3, x_2);
    lungo_dec(x_2);
    return x_4;
}

/* Lean: CapDAG.instReprEffect.repr._closed_0 */
/* Compiled from: CapDAG.instReprEffect.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"CapDAG.Effect.unspecified", 25, 25);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__0__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__0__cell, capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__0__init);
}

/* Lean: CapDAG.instReprEffect.repr._closed_1 */
/* Compiled from: CapDAG.instReprEffect.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__1__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__0();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__1__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__1(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__1__cell, capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__1__init);
}

/* Lean: CapDAG.instReprEffect.repr._closed_2 */
/* Compiled from: CapDAG.instReprEffect.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__2__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"CapDAG.Effect.declared", 22, 22);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__2__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__2(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__2__cell, capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__2__init);
}

/* Lean: CapDAG.instReprEffect.repr._closed_3 */
/* Compiled from: CapDAG.instReprEffect.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__3__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__2();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__3__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__3(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__3__cell, capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__3__init);
}

/* Lean: CapDAG.instReprEffect.repr._closed_4 */
/* Compiled from: CapDAG.instReprEffect.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__4__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"CapDAG.Effect.none", 18, 18);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__4__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__4(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__4__cell, capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__4__init);
}

/* Lean: CapDAG.instReprEffect.repr._closed_5 */
/* Compiled from: CapDAG.instReprEffect.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__5__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__4();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__5__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__5(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__5__cell, capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__5__init);
}

/* Lean: CapDAG.instReprEffect.repr._closed_6 */
/* Compiled from: CapDAG.instReprEffect.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__6__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"CapDAG.Effect.patch", 19, 19);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__6__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__6(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__6__cell, capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__6__init);
}

/* Lean: CapDAG.instReprEffect.repr._closed_7 */
/* Compiled from: CapDAG.instReprEffect.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__7__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__6();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__7__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__7(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__7__cell, capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__7__init);
}

/* Lean: CapDAG.instReprEffect.repr._closed_8 */
/* Compiled from: CapDAG.instReprEffect.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__8__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = lungo_usize_to_nat(2u);
    x_2 = capdagFormal__l_Int_dofNat(x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__8__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__8(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__8__cell, capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__8__init);
}

/* Lean: CapDAG.instReprEffect.repr._closed_9 */
/* Compiled from: CapDAG.instReprEffect.repr */
/* Source: ../../../../formal/CapDAG/Cap.lean:27:25 */
static lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__9__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = lungo_usize_to_nat(1u);
    x_2 = capdagFormal__l_Int_dofNat(x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__9__cell;
lungo_obj capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__9(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__9__cell, capdagFormal__l_CapDAG_dinstReprEffect_drepr_d__closed__9__init);
}

/* Lean: CapDAG.mediaTop */
/* Source: ../../../../formal/CapDAG/Cap.lean:36:1 */
static lungo_obj capdagFormal__l_CapDAG_dmediaTop__init(void) {
    lungo_obj x_1;
    x_1 = capdagFormal__l_CapDAG_dmediaTop_d__closed__1();
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dmediaTop__cell;
lungo_obj capdagFormal__l_CapDAG_dmediaTop(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dmediaTop__cell, capdagFormal__l_CapDAG_dmediaTop__init);
}

/* Lean: CapDAG.mediaTop._closed_0 */
/* Compiled from: CapDAG.mediaTop */
/* Source: ../../../../formal/CapDAG/Cap.lean:36:1 */
static lungo_obj capdagFormal__l_CapDAG_dmediaTop_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"media", 5, 5);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dmediaTop_d__closed__0__cell;
lungo_obj capdagFormal__l_CapDAG_dmediaTop_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dmediaTop_d__closed__0__cell, capdagFormal__l_CapDAG_dmediaTop_d__closed__0__init);
}

/* Lean: CapDAG.mediaTop._closed_1 */
/* Compiled from: CapDAG.mediaTop */
/* Source: ../../../../formal/CapDAG/Cap.lean:36:1 */
static lungo_obj capdagFormal__l_CapDAG_dmediaTop_d__closed__1__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    lungo_obj x_3;
    x_1 = lungo_box(0);
    x_2 = capdagFormal__l_CapDAG_dmediaTop_d__closed__0();
    x_3 = lungo_alloc_ctor(0, 2, 0);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set(x_3, 1, x_1);
    return x_3;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dmediaTop_d__closed__1__cell;
lungo_obj capdagFormal__l_CapDAG_dmediaTop_d__closed__1(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dmediaTop_d__closed__1__cell, capdagFormal__l_CapDAG_dmediaTop_d__closed__1__init);
}

/* Lean: CapDAG.mediaVoid */
/* Source: ../../../../formal/CapDAG/Cap.lean:37:1 */
static lungo_obj capdagFormal__l_CapDAG_dmediaVoid__init(void) {
    lungo_obj x_1;
    x_1 = capdagFormal__l_CapDAG_dmediaVoid_d__closed__3();
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dmediaVoid__cell;
lungo_obj capdagFormal__l_CapDAG_dmediaVoid(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dmediaVoid__cell, capdagFormal__l_CapDAG_dmediaVoid__init);
}

/* Lean: CapDAG.mediaVoid._closed_0 */
/* Compiled from: CapDAG.mediaVoid */
/* Source: ../../../../formal/CapDAG/Cap.lean:37:1 */
static lungo_obj capdagFormal__l_CapDAG_dmediaVoid_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"void", 4, 4);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dmediaVoid_d__closed__0__cell;
lungo_obj capdagFormal__l_CapDAG_dmediaVoid_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dmediaVoid_d__closed__0__cell, capdagFormal__l_CapDAG_dmediaVoid_d__closed__0__init);
}

/* Lean: CapDAG.mediaVoid._closed_1 */
/* Compiled from: CapDAG.mediaVoid */
/* Source: ../../../../formal/CapDAG/Cap.lean:37:1 */
static lungo_obj capdagFormal__l_CapDAG_dmediaVoid_d__closed__1__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    lungo_obj x_3;
    x_1 = lungo_box(3);
    x_2 = capdagFormal__l_CapDAG_dmediaVoid_d__closed__0();
    x_3 = lungo_alloc_ctor(0, 2, 0);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set(x_3, 1, x_1);
    return x_3;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dmediaVoid_d__closed__1__cell;
lungo_obj capdagFormal__l_CapDAG_dmediaVoid_d__closed__1(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dmediaVoid_d__closed__1__cell, capdagFormal__l_CapDAG_dmediaVoid_d__closed__1__init);
}

/* Lean: CapDAG.mediaVoid._closed_2 */
/* Compiled from: CapDAG.mediaVoid */
/* Source: ../../../../formal/CapDAG/Cap.lean:37:1 */
static lungo_obj capdagFormal__l_CapDAG_dmediaVoid_d__closed__2__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    lungo_obj x_3;
    x_1 = lungo_box(0);
    x_2 = capdagFormal__l_CapDAG_dmediaVoid_d__closed__1();
    x_3 = lungo_alloc_ctor(1, 2, 0);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set(x_3, 1, x_1);
    return x_3;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dmediaVoid_d__closed__2__cell;
lungo_obj capdagFormal__l_CapDAG_dmediaVoid_d__closed__2(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dmediaVoid_d__closed__2__cell, capdagFormal__l_CapDAG_dmediaVoid_d__closed__2__init);
}

/* Lean: CapDAG.mediaVoid._closed_3 */
/* Compiled from: CapDAG.mediaVoid */
/* Source: ../../../../formal/CapDAG/Cap.lean:37:1 */
static lungo_obj capdagFormal__l_CapDAG_dmediaVoid_d__closed__3__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    lungo_obj x_3;
    x_1 = capdagFormal__l_CapDAG_dmediaVoid_d__closed__2();
    x_2 = capdagFormal__l_CapDAG_dmediaTop_d__closed__0();
    x_3 = lungo_alloc_ctor(0, 2, 0);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set(x_3, 1, x_1);
    return x_3;
}
static lungo_lazy_obj capdagFormal__l_CapDAG_dmediaVoid_d__closed__3__cell;
lungo_obj capdagFormal__l_CapDAG_dmediaVoid_d__closed__3(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_CapDAG_dmediaVoid_d__closed__3__cell, capdagFormal__l_CapDAG_dmediaVoid_d__closed__3__init);
}

