/* Generated by lungo 1.105.524 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module CapDAG.Ranking. */
#include "capdagFormal_program.h"

/* Lean: CapDAG.betterKey */
/* Source: ../../../../formal/CapDAG/Ranking.lean:33:1 */
uint8_t capdagFormal__l_CapDAG_dbetterKey(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    uint8_t x_8;
    uint8_t x_9;
    x_3 = lungo_ctor_get(x_1, 0);
    x_4 = lungo_ctor_get(x_1, 1);
    x_5 = lungo_ctor_get(x_2, 0);
    x_6 = lungo_ctor_get(x_2, 1);
    x_7 = capdagFormal__l_Nat_ddecLt(x_3, x_5);
    switch (x_7) {
        case 0: {
            x_8 = capdagFormal__l_Nat_ddecEq(x_3, x_5);
            switch (x_8) {
                case 0: {
                    return x_8;
                }
                default: {
                    x_9 = capdagFormal__l_Nat_ddecLt(x_4, x_6);
                    return x_9;
                }
            }
        }
        default: {
            return x_7;
        }
    }
}

/* Lean: CapDAG.betterKey._boxed */
/* Compiled from: CapDAG.betterKey */
/* Source: ../../../../formal/CapDAG/Ranking.lean:33:1 */
lungo_obj capdagFormal__l_CapDAG_dbetterKey_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dbetterKey(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.capScore */
/* Source: ../../../../formal/CapDAG/Ranking.lean:22:1 */
lungo_obj capdagFormal__l_CapDAG_dcapScore(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    x_2 = lungo_ctor_get(x_1, 0);
    lungo_inc_ref(x_2);
    x_3 = lungo_ctor_get(x_1, 1);
    lungo_inc_ref(x_3);
    x_4 = lungo_ctor_get(x_1, 2);
    lungo_inc_ref(x_4);
    lungo_dec_ref(x_1);
    x_5 = lungo_usize_to_nat(10000u);
    x_6 = capdagFormal__l_TaggedUrn_durnScore(x_3);
    x_7 = capdagFormal__l_Nat_dmul(x_5, x_6);
    lungo_dec(x_6);
    x_8 = lungo_usize_to_nat(100u);
    x_9 = capdagFormal__l_TaggedUrn_durnScore(x_2);
    x_10 = capdagFormal__l_Nat_dmul(x_8, x_9);
    lungo_dec(x_9);
    x_11 = capdagFormal__l_Nat_dadd(x_7, x_10);
    lungo_dec(x_10);
    lungo_dec(x_7);
    x_12 = capdagFormal__l_TaggedUrn_durnScore(x_4);
    x_13 = capdagFormal__l_Nat_dadd(x_11, x_12);
    lungo_dec(x_12);
    lungo_dec(x_11);
    return x_13;
}

/* Lean: CapDAG.rankingKey */
/* Source: ../../../../formal/CapDAG/Ranking.lean:26:1 */
lungo_obj capdagFormal__l_CapDAG_drankingKey(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    x_3 = capdagFormal__l_CapDAG_dcapScore(x_1);
    x_4 = capdagFormal__l_CapDAG_dcapScore(x_2);
    x_5 = capdagFormal__l_Nat_ddecLe(x_4, x_3);
    switch (x_5) {
        case 0: {
            x_6 = lungo_usize_to_nat(1u);
            x_7 = capdagFormal__l_Nat_dsub(x_4, x_3);
            lungo_dec(x_3);
            lungo_dec(x_4);
            x_8 = lungo_alloc_ctor(0, 2, 0);
            lungo_ctor_set(x_8, 0, x_6);
            lungo_ctor_set(x_8, 1, x_7);
            return x_8;
        }
        default: {
            x_9 = lungo_usize_to_nat(0u);
            x_10 = capdagFormal__l_Nat_dsub(x_3, x_4);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_11 = lungo_alloc_ctor(0, 2, 0);
            lungo_ctor_set(x_11, 0, x_9);
            lungo_ctor_set(x_11, 1, x_10);
            return x_11;
        }
    }
}

/* Lean: CapDAG.select */
/* Source: ../../../../formal/CapDAG/Ranking.lean:55:1 */
lungo_obj capdagFormal__l_CapDAG_dselect(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    x_3 = lungo_box(0);
    x_4 = capdagFormal__l_List_dfoldl_d__at___dCapDAG_dselect_dspec__0(x_2, x_3, x_1);
    return x_4;
}

/* Lean: CapDAG.selectStep */
/* Source: ../../../../formal/CapDAG/Ranking.lean:44:1 */
lungo_obj capdagFormal__l_CapDAG_dselectStep(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    uint8_t x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    uint8_t x_9;
    lungo_obj x_11;
    uint8_t x_12;
    lungo_obj x_14;
    lungo_obj x_15;
    uint8_t x_16;
    lungo_obj x_17;
    lungo_inc_ref(x_1);
    lungo_inc_ref(x_3);
    x_4 = capdagFormal__l_CapDAG_dinstDecidableServes(x_3, x_1);
    switch (x_4) {
        case 0: {
            lungo_dec_ref(x_3);
            lungo_dec_ref(x_1);
            return x_2;
        }
        default: {
            switch (lungo_obj_tag(x_2)) {
                case 0: {
                    lungo_dec_ref(x_1);
                    x_5 = lungo_alloc_ctor(1, 1, 0);
                    lungo_ctor_set(x_5, 0, x_3);
                    return x_5;
                }
                default: {
                    x_6 = lungo_ctor_get(x_2, 0);
                    lungo_inc_ref(x_1);
                    lungo_inc_ref(x_3);
                    x_7 = capdagFormal__l_CapDAG_drankingKey(x_3, x_1);
                    lungo_inc(x_6);
                    x_8 = capdagFormal__l_CapDAG_drankingKey(x_6, x_1);
                    x_9 = capdagFormal__l_CapDAG_dbetterKey(x_7, x_8);
                    lungo_dec_ref(x_8);
                    lungo_dec_ref(x_7);
                    switch (x_9) {
                        case 0: {
                            lungo_dec_ref(x_3);
                            return x_2;
                        }
                        default: {
                            x_16 = !lungo_is_exclusive(x_2);
                            switch (x_16) {
                                case 0: {
                                    x_17 = lungo_ctor_get(x_2, 0);
                                    lungo_dec(x_17);
                                    x_11 = x_2;
                                    x_12 = x_16;
                                    goto block_10;
                                }
                                default: {
                                    lungo_dec(x_2);
                                    x_11 = lungo_box(0);
                                    x_12 = x_16;
                                    goto block_10;
                                }
                            }
                            block_10:;
                            switch (x_12) {
                                case 0: {
                                    lungo_ctor_set(x_11, 0, x_3);
                                    x_14 = x_11;
                                    goto block_13;
                                }
                                default: {
                                    x_15 = lungo_alloc_ctor(1, 1, 0);
                                    lungo_ctor_set(x_15, 0, x_3);
                                    x_14 = x_15;
                                    goto block_13;
                                }
                            }
                            block_13:;
                            return x_14;
                        }
                    }
                }
            }
        }
    }
}

/* Lean: List.foldl._at_.CapDAG.select.spec_0 */
/* Compiled from: List.foldl */
/* Source: <lean>/Init/Prelude.lean:3102:1 */
lungo_obj capdagFormal__l_List_dfoldl_d__at___dCapDAG_dselect_dspec__0(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    _start:
    switch (lungo_obj_tag(x_3)) {
        case 0: {
            lungo_dec_ref(x_1);
            return x_2;
        }
        default: {
            x_4 = lungo_ctor_get(x_3, 0);
            lungo_inc(x_4);
            x_5 = lungo_ctor_get(x_3, 1);
            lungo_inc(x_5);
            lungo_dec_ref(x_3);
            lungo_inc_ref(x_1);
            x_6 = capdagFormal__l_CapDAG_dselectStep(x_1, x_2, x_4);
            {
                lungo_obj t_0 = x_1;
                lungo_obj t_1 = x_6;
                lungo_obj t_2 = x_5;
                x_1 = t_0;
                x_2 = t_1;
                x_3 = t_2;
                goto _start;
            }
        }
    }
}

/* Lean: _private.CapDAG.Ranking.0.CapDAG.selectStep.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Ranking.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dRanking_d0_dCapDAG_dselectStep_dmatch__1_dsplitter(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec(x_4);
            x_5 = lungo_box(0);
            x_6 = lungo_apply_1(x_3, x_5);
            return x_6;
        }
        default: {
            lungo_dec(x_3);
            x_7 = lungo_ctor_get(x_2, 0);
            lungo_inc(x_7);
            lungo_dec_ref(x_2);
            x_8 = lungo_apply_1(x_4, x_7);
            return x_8;
        }
    }
}

/* Lean: _private.CapDAG.Ranking.0.CapDAG.selectStep.match_1.splitter._redArg */
/* Compiled from: _private.CapDAG.Ranking.0.CapDAG.selectStep.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Ranking.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dRanking_d0_dCapDAG_dselectStep_dmatch__1_dsplitter_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            lungo_dec(x_3);
            x_4 = lungo_box(0);
            x_5 = lungo_apply_1(x_2, x_4);
            return x_5;
        }
        default: {
            lungo_dec(x_2);
            x_6 = lungo_ctor_get(x_1, 0);
            lungo_inc(x_6);
            lungo_dec_ref(x_1);
            x_7 = lungo_apply_1(x_3, x_6);
            return x_7;
        }
    }
}

