/* Generated by lungo 1.81.24 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module CapDAG.Exec. */
#include "capdagFormal_program.h"

/* Lean: CapDAG.Exec.WfAsk.covers.elim */
/* Source: ../../../../formal/CapDAG/Exec.lean:53:3 */
lungo_obj capdagFormal__l_CapDAG_dExec_dWfAsk_dcovers_delim(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    (void)x_3;
    lungo_obj x_5;
    x_5 = capdagFormal__l_CapDAG_dExec_dWfAsk_dctorElim_d__redArg(x_2, x_4);
    return x_5;
}

/* Lean: CapDAG.Exec.WfAsk.covers.elim._redArg */
/* Compiled from: CapDAG.Exec.WfAsk.covers.elim */
/* Source: ../../../../formal/CapDAG/Exec.lean:53:3 */
lungo_obj capdagFormal__l_CapDAG_dExec_dWfAsk_dcovers_delim_d__redArg(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = capdagFormal__l_CapDAG_dExec_dWfAsk_dctorElim_d__redArg(x_1, x_2);
    return x_3;
}

/* Lean: CapDAG.Exec.WfAsk.ctorElim */
/* Source: ../../../../formal/CapDAG/Exec.lean:49:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dWfAsk_dctorElim(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5) {
    (void)x_1;
    (void)x_2;
    (void)x_4;
    lungo_obj x_6;
    x_6 = capdagFormal__l_CapDAG_dExec_dWfAsk_dctorElim_d__redArg(x_3, x_5);
    return x_6;
}

/* Lean: CapDAG.Exec.WfAsk.ctorElim._boxed */
/* Compiled from: CapDAG.Exec.WfAsk.ctorElim */
/* Source: ../../../../formal/CapDAG/Exec.lean:49:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dWfAsk_dctorElim_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5) {
    lungo_obj x_6;
    x_6 = capdagFormal__l_CapDAG_dExec_dWfAsk_dctorElim(x_1, x_2, x_3, x_4, x_5);
    lungo_dec(x_2);
    return x_6;
}

/* Lean: CapDAG.Exec.WfAsk.ctorElim._redArg */
/* Compiled from: CapDAG.Exec.WfAsk.ctorElim */
/* Source: ../../../../formal/CapDAG/Exec.lean:49:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dWfAsk_dctorElim_d__redArg(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            return x_2;
        }
        default: {
            x_3 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_3);
            lungo_dec(x_1);
            x_4 = lungo_apply_1(x_2, x_3);
            return x_4;
        }
    }
}

/* Lean: CapDAG.Exec.WfAsk.ctorIdx */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l_CapDAG_dExec_dWfAsk_dctorIdx(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_2 = lungo_usize_to_nat(0u);
            return x_2;
        }
        case 1: {
            x_3 = lungo_usize_to_nat(1u);
            return x_3;
        }
        case 2: {
            x_4 = lungo_usize_to_nat(2u);
            return x_4;
        }
        default: {
            x_5 = lungo_usize_to_nat(3u);
            return x_5;
        }
    }
}

/* Lean: CapDAG.Exec.WfAsk.ctorIdx._boxed */
/* Compiled from: CapDAG.Exec.WfAsk.ctorIdx */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l_CapDAG_dExec_dWfAsk_dctorIdx_d__boxed(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = capdagFormal__l_CapDAG_dExec_dWfAsk_dctorIdx(x_1);
    lungo_dec(x_1);
    return x_2;
}

/* Lean: CapDAG.Exec.WfAsk.same.elim */
/* Source: ../../../../formal/CapDAG/Exec.lean:54:3 */
lungo_obj capdagFormal__l_CapDAG_dExec_dWfAsk_dsame_delim(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    (void)x_3;
    lungo_obj x_5;
    x_5 = capdagFormal__l_CapDAG_dExec_dWfAsk_dctorElim_d__redArg(x_2, x_4);
    return x_5;
}

/* Lean: CapDAG.Exec.WfAsk.same.elim._redArg */
/* Compiled from: CapDAG.Exec.WfAsk.same.elim */
/* Source: ../../../../formal/CapDAG/Exec.lean:54:3 */
lungo_obj capdagFormal__l_CapDAG_dExec_dWfAsk_dsame_delim_d__redArg(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = capdagFormal__l_CapDAG_dExec_dWfAsk_dctorElim_d__redArg(x_1, x_2);
    return x_3;
}

/* Lean: CapDAG.Exec.WfAsk.unknown.elim */
/* Source: ../../../../formal/CapDAG/Exec.lean:51:3 */
lungo_obj capdagFormal__l_CapDAG_dExec_dWfAsk_dunknown_delim(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    (void)x_3;
    lungo_obj x_5;
    x_5 = capdagFormal__l_CapDAG_dExec_dWfAsk_dctorElim_d__redArg(x_2, x_4);
    return x_5;
}

/* Lean: CapDAG.Exec.WfAsk.unknown.elim._redArg */
/* Compiled from: CapDAG.Exec.WfAsk.unknown.elim */
/* Source: ../../../../formal/CapDAG/Exec.lean:51:3 */
lungo_obj capdagFormal__l_CapDAG_dExec_dWfAsk_dunknown_delim_d__redArg(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = capdagFormal__l_CapDAG_dExec_dWfAsk_dctorElim_d__redArg(x_1, x_2);
    return x_3;
}

/* Lean: CapDAG.Exec.WfAsk.within.elim */
/* Source: ../../../../formal/CapDAG/Exec.lean:52:3 */
lungo_obj capdagFormal__l_CapDAG_dExec_dWfAsk_dwithin_delim(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    (void)x_3;
    lungo_obj x_5;
    x_5 = capdagFormal__l_CapDAG_dExec_dWfAsk_dctorElim_d__redArg(x_2, x_4);
    return x_5;
}

/* Lean: CapDAG.Exec.WfAsk.within.elim._redArg */
/* Compiled from: CapDAG.Exec.WfAsk.within.elim */
/* Source: ../../../../formal/CapDAG/Exec.lean:52:3 */
lungo_obj capdagFormal__l_CapDAG_dExec_dWfAsk_dwithin_delim_d__redArg(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = capdagFormal__l_CapDAG_dExec_dWfAsk_dctorElim_d__redArg(x_1, x_2);
    return x_3;
}

/* Lean: CapDAG.Exec.accepts */
/* Source: ../../../../formal/CapDAG/Exec.lean:208:1 */
uint8_t capdagFormal__l_CapDAG_dExec_daccepts(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    uint8_t x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_dqueryOfPattern(x_1);
    x_4 = capdagFormal__l_CapDAG_dExec_dqueryAdmits(x_3, x_2);
    return x_4;
}

/* Lean: CapDAG.Exec.accepts._boxed */
/* Compiled from: CapDAG.Exec.accepts */
/* Source: ../../../../formal/CapDAG/Exec.lean:208:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_daccepts_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_daccepts(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.Exec.comparable */
/* Source: ../../../../formal/CapDAG/Exec.lean:254:1 */
uint8_t capdagFormal__l_CapDAG_dExec_dcomparable(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    uint8_t x_4;
    x_3 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dsameSides(x_1, x_2);
    switch (x_3) {
        case 0: {
            x_4 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dsameSides(x_2, x_1);
            return x_4;
        }
        default: {
            return x_3;
        }
    }
}

/* Lean: CapDAG.Exec.comparable._boxed */
/* Compiled from: CapDAG.Exec.comparable */
/* Source: ../../../../formal/CapDAG/Exec.lean:254:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dcomparable_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_dcomparable(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.Exec.dispatch */
/* Source: ../../../../formal/CapDAG/Exec.lean:190:1 */
uint8_t capdagFormal__l_CapDAG_dExec_ddispatch(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    uint8_t x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_dqueryOfRequest(x_2);
    x_4 = capdagFormal__l_CapDAG_dExec_dqueryAdmits(x_3, x_1);
    return x_4;
}

/* Lean: CapDAG.Exec.dispatch._boxed */
/* Compiled from: CapDAG.Exec.dispatch */
/* Source: ../../../../formal/CapDAG/Exec.lean:190:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_ddispatch_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_ddispatch(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.Exec.effectOk */
/* Source: ../../../../formal/CapDAG/Exec.lean:29:1 */
uint8_t capdagFormal__l_CapDAG_dExec_deffectOk(uint8_t x_1, uint8_t x_2) {
    uint8_t x_3;
    uint8_t x_4;
    uint8_t x_5;
    x_3 = (uint8_t)0u;
    x_4 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_2, x_3);
    switch (x_4) {
        case 0: {
            x_5 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_1, x_2);
            return x_5;
        }
        default: {
            return x_4;
        }
    }
}

/* Lean: CapDAG.Exec.effectOk._boxed */
/* Compiled from: CapDAG.Exec.effectOk */
/* Source: ../../../../formal/CapDAG/Exec.lean:29:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_deffectOk_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    uint8_t x_4;
    uint8_t x_5;
    lungo_obj x_6;
    x_3 = (uint8_t)lungo_unbox(x_1);
    x_4 = (uint8_t)lungo_unbox(x_2);
    x_5 = capdagFormal__l_CapDAG_dExec_deffectOk(x_3, x_4);
    x_6 = lungo_box((size_t)x_5);
    return x_6;
}

/* Lean: CapDAG.Exec.equivalent */
/* Source: ../../../../formal/CapDAG/Exec.lean:253:1 */
uint8_t capdagFormal__l_CapDAG_dExec_dequivalent(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    uint8_t x_4;
    x_3 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dsameSides(x_1, x_2);
    switch (x_3) {
        case 0: {
            return x_3;
        }
        default: {
            x_4 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dsameSides(x_2, x_1);
            return x_4;
        }
    }
}

/* Lean: CapDAG.Exec.equivalent._boxed */
/* Compiled from: CapDAG.Exec.equivalent */
/* Source: ../../../../formal/CapDAG/Exec.lean:253:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dequivalent_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_dequivalent(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.Exec.flows */
/* Source: ../../../../formal/CapDAG/Exec.lean:277:1 */
uint8_t capdagFormal__l_CapDAG_dExec_dflows(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    x_3 = lungo_ctor_get(x_1, 1);
    x_4 = lungo_ctor_get(x_2, 0);
    x_5 = capdagFormal__l_TaggedUrn_dExec_drefines(x_3, x_4);
    return x_5;
}

/* Lean: CapDAG.Exec.flows._boxed */
/* Compiled from: CapDAG.Exec.flows */
/* Source: ../../../../formal/CapDAG/Exec.lean:277:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dflows_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_dflows(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.Exec.mayDispatch */
/* Source: ../../../../formal/CapDAG/Exec.lean:199:1 */
uint8_t capdagFormal__l_CapDAG_dExec_dmayDispatch(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    uint8_t x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_dqueryOfRequest(x_2);
    x_4 = capdagFormal__l_CapDAG_dExec_dqueryMayAdmit(x_3, x_1);
    return x_4;
}

/* Lean: CapDAG.Exec.mayDispatch._boxed */
/* Compiled from: CapDAG.Exec.mayDispatch */
/* Source: ../../../../formal/CapDAG/Exec.lean:199:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dmayDispatch_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_dmayDispatch(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.Exec.mayFlow */
/* Source: ../../../../formal/CapDAG/Exec.lean:283:1 */
uint8_t capdagFormal__l_CapDAG_dExec_dmayFlow(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    x_3 = lungo_ctor_get(x_1, 1);
    lungo_inc_ref(x_3);
    lungo_dec_ref(x_1);
    x_4 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_4);
    lungo_dec_ref(x_2);
    x_5 = capdagFormal__l_TaggedUrn_dExec_dmeets(x_3, x_4);
    return x_5;
}

/* Lean: CapDAG.Exec.mayFlow._boxed */
/* Compiled from: CapDAG.Exec.mayFlow */
/* Source: ../../../../formal/CapDAG/Exec.lean:283:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dmayFlow_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_dmayFlow(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.Exec.queryAdmits */
/* Source: ../../../../formal/CapDAG/Exec.lean:134:1 */
uint8_t capdagFormal__l_CapDAG_dExec_dqueryAdmits(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    uint8_t x_10;
    uint8_t x_12;
    uint8_t x_13;
    uint8_t x_14;
    uint8_t x_15;
    uint8_t x_16;
    x_3 = lungo_ctor_get(x_1, 0);
    lungo_inc(x_3);
    x_4 = lungo_ctor_get(x_1, 1);
    lungo_inc(x_4);
    x_5 = lungo_ctor_get(x_1, 2);
    lungo_inc_ref(x_5);
    x_6 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    lungo_dec_ref(x_1);
    x_7 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_7);
    x_8 = lungo_ctor_get(x_2, 1);
    lungo_inc_ref(x_8);
    x_9 = lungo_ctor_get(x_2, 2);
    lungo_inc_ref(x_9);
    x_10 = lungo_ctor_get_uint8(x_2, 3 * sizeof(size_t));
    lungo_dec_ref(x_2);
    x_15 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_daskAdmits(x_3, x_7);
    lungo_dec_ref(x_7);
    lungo_dec(x_3);
    switch (x_15) {
        case 0: {
            lungo_dec_ref(x_8);
            lungo_dec(x_4);
            x_12 = x_15;
            goto block_11;
        }
        default: {
            x_16 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_daskAdmits(x_4, x_8);
            lungo_dec_ref(x_8);
            lungo_dec(x_4);
            x_12 = x_16;
            goto block_11;
        }
    }
    block_11:;
    switch (x_12) {
        case 0: {
            lungo_dec_ref(x_9);
            lungo_dec_ref(x_5);
            return x_12;
        }
        default: {
            x_13 = capdagFormal__l_CapDAG_dExec_deffectOk(x_10, x_6);
            switch (x_13) {
                case 0: {
                    lungo_dec_ref(x_9);
                    lungo_dec_ref(x_5);
                    return x_13;
                }
                default: {
                    x_14 = capdagFormal__l_TaggedUrn_dExec_drefinesClosed(x_9, x_5);
                    return x_14;
                }
            }
        }
    }
}

/* Lean: CapDAG.Exec.queryAdmits._boxed */
/* Compiled from: CapDAG.Exec.queryAdmits */
/* Source: ../../../../formal/CapDAG/Exec.lean:134:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dqueryAdmits_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_dqueryAdmits(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.Exec.queryBetween */
/* Source: ../../../../formal/CapDAG/Exec.lean:96:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dqueryBetween(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_7;
    x_4 = lungo_alloc_ctor(2, 1, 0);
    lungo_ctor_set(x_4, 0, x_1);
    x_5 = lungo_alloc_ctor(1, 1, 0);
    lungo_ctor_set(x_5, 0, x_2);
    x_6 = (uint8_t)0u;
    x_7 = lungo_alloc_ctor(0, 3, 1);
    lungo_ctor_set(x_7, 0, x_4);
    lungo_ctor_set(x_7, 1, x_5);
    lungo_ctor_set(x_7, 2, x_3);
    lungo_ctor_set_uint8(x_7, 3 * sizeof(size_t), x_6);
    return x_7;
}

/* Lean: CapDAG.Exec.queryConsuming */
/* Source: ../../../../formal/CapDAG/Exec.lean:92:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dqueryConsuming(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_6;
    x_3 = lungo_alloc_ctor(2, 1, 0);
    lungo_ctor_set(x_3, 0, x_1);
    x_4 = lungo_box(0);
    x_5 = (uint8_t)0u;
    x_6 = lungo_alloc_ctor(0, 3, 1);
    lungo_ctor_set(x_6, 0, x_3);
    lungo_ctor_set(x_6, 1, x_4);
    lungo_ctor_set(x_6, 2, x_2);
    lungo_ctor_set_uint8(x_6, 3 * sizeof(size_t), x_5);
    return x_6;
}

/* Lean: CapDAG.Exec.queryGrade */
/* Source: ../../../../formal/CapDAG/Exec.lean:170:1 */
uint8_t capdagFormal__l_CapDAG_dExec_dqueryGrade(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    uint8_t x_4;
    uint8_t x_5;
    uint8_t x_6;
    uint8_t x_7;
    uint8_t x_8;
    uint8_t x_9;
    uint8_t x_10;
    lungo_inc_ref(x_1);
    x_3 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfQuery_dexactly(x_1);
    lungo_inc_ref(x_2);
    x_4 = capdagFormal__l_CapDAG_dExec_dqueryAdmits(x_3, x_2);
    switch (x_4) {
        case 0: {
            lungo_inc_ref(x_2);
            lungo_inc_ref(x_1);
            x_5 = capdagFormal__l_CapDAG_dExec_dqueryAdmits(x_1, x_2);
            switch (x_5) {
                case 0: {
                    x_6 = capdagFormal__l_CapDAG_dExec_dqueryMayAdmit(x_1, x_2);
                    switch (x_6) {
                        case 0: {
                            x_7 = (uint8_t)3u;
                            return x_7;
                        }
                        default: {
                            x_8 = (uint8_t)2u;
                            return x_8;
                        }
                    }
                }
                default: {
                    lungo_dec_ref(x_2);
                    lungo_dec_ref(x_1);
                    x_9 = (uint8_t)1u;
                    return x_9;
                }
            }
        }
        default: {
            lungo_dec_ref(x_2);
            lungo_dec_ref(x_1);
            x_10 = (uint8_t)0u;
            return x_10;
        }
    }
}

/* Lean: CapDAG.Exec.queryGrade._boxed */
/* Compiled from: CapDAG.Exec.queryGrade */
/* Source: ../../../../formal/CapDAG/Exec.lean:170:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dqueryGrade_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_dqueryGrade(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.Exec.queryMayAdmit */
/* Source: ../../../../formal/CapDAG/Exec.lean:146:1 */
uint8_t capdagFormal__l_CapDAG_dExec_dqueryMayAdmit(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    uint8_t x_10;
    uint8_t x_12;
    uint8_t x_13;
    uint8_t x_14;
    uint8_t x_15;
    uint8_t x_16;
    x_3 = lungo_ctor_get(x_1, 0);
    lungo_inc(x_3);
    x_4 = lungo_ctor_get(x_1, 1);
    lungo_inc(x_4);
    x_5 = lungo_ctor_get(x_1, 2);
    lungo_inc_ref(x_5);
    x_6 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    lungo_dec_ref(x_1);
    x_7 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_7);
    x_8 = lungo_ctor_get(x_2, 1);
    lungo_inc_ref(x_8);
    x_9 = lungo_ctor_get(x_2, 2);
    lungo_inc_ref(x_9);
    x_10 = lungo_ctor_get_uint8(x_2, 3 * sizeof(size_t));
    lungo_dec_ref(x_2);
    x_15 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_daskMayAdmit(x_3, x_7);
    switch (x_15) {
        case 0: {
            lungo_dec_ref(x_8);
            lungo_dec(x_4);
            x_12 = x_15;
            goto block_11;
        }
        default: {
            x_16 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_daskMayAdmit(x_4, x_8);
            x_12 = x_16;
            goto block_11;
        }
    }
    block_11:;
    switch (x_12) {
        case 0: {
            lungo_dec_ref(x_9);
            lungo_dec_ref(x_5);
            return x_12;
        }
        default: {
            x_13 = capdagFormal__l_CapDAG_dExec_deffectOk(x_10, x_6);
            switch (x_13) {
                case 0: {
                    lungo_dec_ref(x_9);
                    lungo_dec_ref(x_5);
                    return x_13;
                }
                default: {
                    x_14 = capdagFormal__l_TaggedUrn_dExec_dmeetsClosed(x_9, x_5);
                    return x_14;
                }
            }
        }
    }
}

/* Lean: CapDAG.Exec.queryMayAdmit._boxed */
/* Compiled from: CapDAG.Exec.queryMayAdmit */
/* Source: ../../../../formal/CapDAG/Exec.lean:146:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dqueryMayAdmit_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_CapDAG_dExec_dqueryMayAdmit(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: CapDAG.Exec.queryOfPattern */
/* Source: ../../../../formal/CapDAG/Exec.lean:80:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dqueryOfPattern(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_7;
    uint8_t x_8;
    lungo_obj x_9;
    uint8_t x_10;
    lungo_obj x_11;
    lungo_obj x_13;
    lungo_obj x_14;
    lungo_obj x_15;
    lungo_obj x_17;
    lungo_obj x_18;
    uint8_t x_19;
    x_2 = lungo_ctor_get(x_1, 0);
    x_3 = lungo_ctor_get(x_1, 1);
    x_4 = lungo_ctor_get(x_1, 2);
    x_5 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    x_19 = !lungo_is_exclusive(x_1);
    switch (x_19) {
        case 0: {
            x_7 = x_1;
            x_8 = x_19;
            goto block_6;
        }
        default: {
            lungo_inc(x_4);
            lungo_inc(x_3);
            lungo_inc(x_2);
            lungo_dec(x_1);
            x_7 = lungo_box(0);
            x_8 = x_19;
            goto block_6;
        }
    }
    block_6:;
    x_9 = lungo_alloc_ctor(1, 1, 0);
    lungo_ctor_set(x_9, 0, x_2);
    x_10 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dunconstrained(x_3);
    switch (x_10) {
        case 0: {
            x_11 = lungo_alloc_ctor(2, 1, 0);
            lungo_ctor_set(x_11, 0, x_3);
            switch (x_8) {
                case 0: {
                    lungo_ctor_set(x_7, 1, x_11);
                    lungo_ctor_set(x_7, 0, x_9);
                    x_13 = x_7;
                    goto block_12;
                }
                default: {
                    x_14 = lungo_alloc_ctor(0, 3, 1);
                    lungo_ctor_set(x_14, 0, x_9);
                    lungo_ctor_set(x_14, 1, x_11);
                    lungo_ctor_set(x_14, 2, x_4);
                    lungo_ctor_set_uint8(x_14, 3 * sizeof(size_t), x_5);
                    x_13 = x_14;
                    goto block_12;
                }
            }
            block_12:;
            return x_13;
        }
        default: {
            lungo_dec_ref(x_3);
            x_15 = lungo_box(0);
            switch (x_8) {
                case 0: {
                    lungo_ctor_set(x_7, 1, x_15);
                    lungo_ctor_set(x_7, 0, x_9);
                    x_17 = x_7;
                    goto block_16;
                }
                default: {
                    x_18 = lungo_alloc_ctor(0, 3, 1);
                    lungo_ctor_set(x_18, 0, x_9);
                    lungo_ctor_set(x_18, 1, x_15);
                    lungo_ctor_set(x_18, 2, x_4);
                    lungo_ctor_set_uint8(x_18, 3 * sizeof(size_t), x_5);
                    x_17 = x_18;
                    goto block_16;
                }
            }
            block_16:;
            return x_17;
        }
    }
}

/* Lean: CapDAG.Exec.queryOfRequest */
/* Source: ../../../../formal/CapDAG/Exec.lean:74:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dqueryOfRequest(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_7;
    uint8_t x_8;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_13;
    lungo_obj x_14;
    uint8_t x_15;
    lungo_obj x_16;
    lungo_obj x_17;
    uint8_t x_18;
    x_2 = lungo_ctor_get(x_1, 0);
    x_3 = lungo_ctor_get(x_1, 1);
    x_4 = lungo_ctor_get(x_1, 2);
    x_5 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    x_18 = !lungo_is_exclusive(x_1);
    switch (x_18) {
        case 0: {
            x_7 = x_1;
            x_8 = x_18;
            goto block_6;
        }
        default: {
            lungo_inc(x_4);
            lungo_inc(x_3);
            lungo_inc(x_2);
            lungo_dec(x_1);
            x_7 = lungo_box(0);
            x_8 = x_18;
            goto block_6;
        }
    }
    block_6:;
    x_15 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dunconstrained(x_2);
    switch (x_15) {
        case 0: {
            x_16 = lungo_alloc_ctor(2, 1, 0);
            lungo_ctor_set(x_16, 0, x_2);
            x_10 = x_16;
            goto block_9;
        }
        default: {
            lungo_dec_ref(x_2);
            x_17 = lungo_box(0);
            x_10 = x_17;
            goto block_9;
        }
    }
    block_9:;
    x_11 = lungo_alloc_ctor(1, 1, 0);
    lungo_ctor_set(x_11, 0, x_3);
    switch (x_8) {
        case 0: {
            lungo_ctor_set(x_7, 1, x_11);
            lungo_ctor_set(x_7, 0, x_10);
            x_13 = x_7;
            goto block_12;
        }
        default: {
            x_14 = lungo_alloc_ctor(0, 3, 1);
            lungo_ctor_set(x_14, 0, x_10);
            lungo_ctor_set(x_14, 1, x_11);
            lungo_ctor_set(x_14, 2, x_4);
            lungo_ctor_set_uint8(x_14, 3 * sizeof(size_t), x_5);
            x_13 = x_14;
            goto block_12;
        }
    }
    block_12:;
    return x_13;
}

/* Lean: CapDAG.Exec.queryProducing */
/* Source: ../../../../formal/CapDAG/Exec.lean:87:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dqueryProducing(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_6;
    x_3 = lungo_box(0);
    x_4 = lungo_alloc_ctor(1, 1, 0);
    lungo_ctor_set(x_4, 0, x_1);
    x_5 = (uint8_t)0u;
    x_6 = lungo_alloc_ctor(0, 3, 1);
    lungo_ctor_set(x_6, 0, x_3);
    lungo_ctor_set(x_6, 1, x_4);
    lungo_ctor_set(x_6, 2, x_2);
    lungo_ctor_set_uint8(x_6, 3 * sizeof(size_t), x_5);
    return x_6;
}

/* Lean: CapDAG.Exec.rankingKey */
/* Source: ../../../../formal/CapDAG/Exec.lean:291:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_drankingKey(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    x_3 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfCap_dtoCap(x_1);
    x_4 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfCap_dtoCap(x_2);
    x_5 = capdagFormal__l_CapDAG_drankingKey(x_3, x_4);
    return x_5;
}

/* Lean: CapDAG.Exec.select */
/* Source: ../../../../formal/CapDAG/Exec.lean:295:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dselect(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    x_3 = lungo_box(0);
    x_4 = capdagFormal__l_List_dfoldl_d__at___dCapDAG_dExec_dselect_dspec__0(x_2, x_3, x_1);
    return x_4;
}

/* Lean: CapDAG.Exec.specificity */
/* Source: ../../../../formal/CapDAG/Exec.lean:289:1 */
lungo_obj capdagFormal__l_CapDAG_dExec_dspecificity(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    x_2 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfCap_dtoCap(x_1);
    x_3 = capdagFormal__l_CapDAG_dcapScore(x_2);
    return x_3;
}

/* Lean: List.foldl._at_.CapDAG.Exec.select.spec_0 */
/* Compiled from: List.foldl */
/* Source: <lean>/Init/Prelude.lean:3102:1 */
lungo_obj capdagFormal__l_List_dfoldl_d__at___dCapDAG_dExec_dselect_dspec__0(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_8;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    uint8_t x_13;
    lungo_obj x_16;
    uint8_t x_17;
    lungo_obj x_19;
    lungo_obj x_21;
    uint8_t x_22;
    lungo_obj x_23;
    _start:
    switch (lungo_obj_tag(x_3)) {
        case 0: {
            lungo_dec_ref(x_1);
            return x_2;
        }
        default: {
            x_4 = lungo_ctor_get(x_3, 0);
            lungo_inc_n(x_4, 2);
            x_5 = lungo_ctor_get(x_3, 1);
            lungo_inc(x_5);
            lungo_dec_ref(x_3);
            lungo_inc_ref(x_1);
            x_6 = capdagFormal__l_CapDAG_dExec_ddispatch(x_4, x_1);
            switch (x_6) {
                case 0: {
                    lungo_dec(x_4);
                    {
                        lungo_obj t_0 = x_1;
                        lungo_obj t_1 = x_2;
                        lungo_obj t_2 = x_5;
                        x_1 = t_0;
                        x_2 = t_1;
                        x_3 = t_2;
                        goto _start;
                    }
                }
                default: {
                    switch (lungo_obj_tag(x_2)) {
                        case 0: {
                            x_8 = lungo_alloc_ctor(1, 1, 0);
                            lungo_ctor_set(x_8, 0, x_4);
                            {
                                lungo_obj t_0 = x_1;
                                lungo_obj t_1 = x_8;
                                lungo_obj t_2 = x_5;
                                x_1 = t_0;
                                x_2 = t_1;
                                x_3 = t_2;
                                goto _start;
                            }
                        }
                        default: {
                            x_10 = lungo_ctor_get(x_2, 0);
                            lungo_inc_ref_n(x_1, 2);
                            lungo_inc(x_4);
                            x_11 = capdagFormal__l_CapDAG_dExec_drankingKey(x_4, x_1);
                            lungo_inc(x_10);
                            x_12 = capdagFormal__l_CapDAG_dExec_drankingKey(x_10, x_1);
                            x_13 = capdagFormal__l_CapDAG_dbetterKey(x_11, x_12);
                            lungo_dec_ref(x_12);
                            lungo_dec_ref(x_11);
                            switch (x_13) {
                                case 0: {
                                    lungo_dec(x_4);
                                    {
                                        lungo_obj t_0 = x_1;
                                        lungo_obj t_1 = x_2;
                                        lungo_obj t_2 = x_5;
                                        x_1 = t_0;
                                        x_2 = t_1;
                                        x_3 = t_2;
                                        goto _start;
                                    }
                                }
                                default: {
                                    x_22 = !lungo_is_exclusive(x_2);
                                    switch (x_22) {
                                        case 0: {
                                            x_23 = lungo_ctor_get(x_2, 0);
                                            lungo_dec(x_23);
                                            x_16 = x_2;
                                            x_17 = x_22;
                                            goto block_15;
                                        }
                                        default: {
                                            lungo_dec(x_2);
                                            x_16 = lungo_box(0);
                                            x_17 = x_22;
                                            goto block_15;
                                        }
                                    }
                                    block_15:;
                                    switch (x_17) {
                                        case 0: {
                                            lungo_ctor_set(x_16, 0, x_4);
                                            x_19 = x_16;
                                            goto block_18;
                                        }
                                        default: {
                                            x_21 = lungo_alloc_ctor(1, 1, 0);
                                            lungo_ctor_set(x_21, 0, x_4);
                                            x_19 = x_21;
                                            goto block_18;
                                        }
                                    }
                                    block_18:;
                                    {
                                        lungo_obj t_0 = x_1;
                                        lungo_obj t_1 = x_19;
                                        lungo_obj t_2 = x_5;
                                        x_1 = t_0;
                                        x_2 = t_1;
                                        x_3 = t_2;
                                        goto _start;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.WfAsk.exactly */
/* Source: ../../../../formal/CapDAG/Exec.lean:158:1 */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfAsk_dexactly(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_7;
    lungo_obj x_8;
    uint8_t x_9;
    lungo_obj x_10;
    lungo_obj x_12;
    uint8_t x_13;
    lungo_obj x_15;
    lungo_obj x_16;
    uint8_t x_17;
    switch (lungo_obj_tag(x_1)) {
        case 1: {
            x_2 = lungo_ctor_get(x_1, 0);
            x_9 = !lungo_is_exclusive(x_1);
            switch (x_9) {
                case 0: {
                    x_4 = x_1;
                    x_5 = x_9;
                    goto block_3;
                }
                default: {
                    lungo_inc(x_2);
                    lungo_dec(x_1);
                    x_4 = lungo_box(0);
                    x_5 = x_9;
                    goto block_3;
                }
            }
            block_3:;
            switch (x_5) {
                case 0: {
                    lungo_ctor_set_tag(x_4, 3);
                    x_7 = x_4;
                    goto block_6;
                }
                default: {
                    x_8 = lungo_alloc_ctor(3, 1, 0);
                    lungo_ctor_set(x_8, 0, x_2);
                    x_7 = x_8;
                    goto block_6;
                }
            }
            block_6:;
            return x_7;
        }
        case 2: {
            x_10 = lungo_ctor_get(x_1, 0);
            x_17 = !lungo_is_exclusive(x_1);
            switch (x_17) {
                case 0: {
                    x_12 = x_1;
                    x_13 = x_17;
                    goto block_11;
                }
                default: {
                    lungo_inc(x_10);
                    lungo_dec(x_1);
                    x_12 = lungo_box(0);
                    x_13 = x_17;
                    goto block_11;
                }
            }
            block_11:;
            switch (x_13) {
                case 0: {
                    lungo_ctor_set_tag(x_12, 3);
                    x_15 = x_12;
                    goto block_14;
                }
                default: {
                    x_16 = lungo_alloc_ctor(3, 1, 0);
                    lungo_ctor_set(x_16, 0, x_10);
                    x_15 = x_16;
                    goto block_14;
                }
            }
            block_14:;
            return x_15;
        }
        default: {
            return x_1;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.WfAsk.toAsk */
/* Source: ../../../../formal/CapDAG/Exec.lean:65:1 */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfAsk_dtoAsk(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_8;
    lungo_obj x_9;
    uint8_t x_10;
    lungo_obj x_11;
    lungo_obj x_13;
    uint8_t x_14;
    lungo_obj x_16;
    lungo_obj x_17;
    uint8_t x_18;
    lungo_obj x_19;
    lungo_obj x_21;
    uint8_t x_22;
    lungo_obj x_24;
    lungo_obj x_25;
    uint8_t x_26;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_2 = lungo_box(0);
            return x_2;
        }
        case 1: {
            x_3 = lungo_ctor_get(x_1, 0);
            x_10 = !lungo_is_exclusive(x_1);
            switch (x_10) {
                case 0: {
                    x_5 = x_1;
                    x_6 = x_10;
                    goto block_4;
                }
                default: {
                    lungo_inc(x_3);
                    lungo_dec(x_1);
                    x_5 = lungo_box(0);
                    x_6 = x_10;
                    goto block_4;
                }
            }
            block_4:;
            switch (x_6) {
                case 0: {
                    x_8 = x_5;
                    goto block_7;
                }
                default: {
                    x_9 = lungo_alloc_ctor(1, 1, 0);
                    lungo_ctor_set(x_9, 0, x_3);
                    x_8 = x_9;
                    goto block_7;
                }
            }
            block_7:;
            return x_8;
        }
        case 2: {
            x_11 = lungo_ctor_get(x_1, 0);
            x_18 = !lungo_is_exclusive(x_1);
            switch (x_18) {
                case 0: {
                    x_13 = x_1;
                    x_14 = x_18;
                    goto block_12;
                }
                default: {
                    lungo_inc(x_11);
                    lungo_dec(x_1);
                    x_13 = lungo_box(0);
                    x_14 = x_18;
                    goto block_12;
                }
            }
            block_12:;
            switch (x_14) {
                case 0: {
                    x_16 = x_13;
                    goto block_15;
                }
                default: {
                    x_17 = lungo_alloc_ctor(2, 1, 0);
                    lungo_ctor_set(x_17, 0, x_11);
                    x_16 = x_17;
                    goto block_15;
                }
            }
            block_15:;
            return x_16;
        }
        default: {
            x_19 = lungo_ctor_get(x_1, 0);
            x_26 = !lungo_is_exclusive(x_1);
            switch (x_26) {
                case 0: {
                    x_21 = x_1;
                    x_22 = x_26;
                    goto block_20;
                }
                default: {
                    lungo_inc(x_19);
                    lungo_dec(x_1);
                    x_21 = lungo_box(0);
                    x_22 = x_26;
                    goto block_20;
                }
            }
            block_20:;
            switch (x_22) {
                case 0: {
                    x_24 = x_21;
                    goto block_23;
                }
                default: {
                    x_25 = lungo_alloc_ctor(3, 1, 0);
                    lungo_ctor_set(x_25, 0, x_19);
                    x_24 = x_25;
                    goto block_23;
                }
            }
            block_23:;
            return x_24;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.WfAsk.toAsk.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfAsk_dtoAsk_dmatch__1_dsplitter(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5, lungo_obj x_6) {
    (void)x_1;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_4);
            x_7 = lungo_box(0);
            x_8 = lungo_apply_1(x_3, x_7);
            return x_8;
        }
        case 1: {
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_3);
            x_9 = lungo_ctor_get(x_2, 0);
            lungo_inc_ref(x_9);
            lungo_dec_ref(x_2);
            x_10 = lungo_apply_1(x_4, x_9);
            return x_10;
        }
        case 2: {
            lungo_dec(x_6);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_11 = lungo_ctor_get(x_2, 0);
            lungo_inc_ref(x_11);
            lungo_dec_ref(x_2);
            x_12 = lungo_apply_1(x_5, x_11);
            return x_12;
        }
        default: {
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_13 = lungo_ctor_get(x_2, 0);
            lungo_inc_ref(x_13);
            lungo_dec_ref(x_2);
            x_14 = lungo_apply_1(x_6, x_13);
            return x_14;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.WfAsk.toAsk.match_1.splitter._redArg */
/* Compiled from: _private.CapDAG.Exec.0.CapDAG.Exec.WfAsk.toAsk.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfAsk_dtoAsk_dmatch__1_dsplitter_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5) {
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_6 = lungo_box(0);
            x_7 = lungo_apply_1(x_2, x_6);
            return x_7;
        }
        case 1: {
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_2);
            x_8 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_8);
            lungo_dec_ref(x_1);
            x_9 = lungo_apply_1(x_3, x_8);
            return x_9;
        }
        case 2: {
            lungo_dec(x_5);
            lungo_dec(x_3);
            lungo_dec(x_2);
            x_10 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_10);
            lungo_dec_ref(x_1);
            x_11 = lungo_apply_1(x_4, x_10);
            return x_11;
        }
        default: {
            lungo_dec(x_4);
            lungo_dec(x_3);
            lungo_dec(x_2);
            x_12 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_12);
            lungo_dec_ref(x_1);
            x_13 = lungo_apply_1(x_5, x_12);
            return x_13;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.WfCap.toCap */
/* Source: ../../../../formal/CapDAG/Exec.lean:24:1 */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfCap_dtoCap(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_7;
    uint8_t x_8;
    lungo_obj x_10;
    lungo_obj x_11;
    uint8_t x_12;
    x_2 = lungo_ctor_get(x_1, 0);
    x_3 = lungo_ctor_get(x_1, 1);
    x_4 = lungo_ctor_get(x_1, 2);
    x_5 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    x_12 = !lungo_is_exclusive(x_1);
    switch (x_12) {
        case 0: {
            x_7 = x_1;
            x_8 = x_12;
            goto block_6;
        }
        default: {
            lungo_inc(x_4);
            lungo_inc(x_3);
            lungo_inc(x_2);
            lungo_dec(x_1);
            x_7 = lungo_box(0);
            x_8 = x_12;
            goto block_6;
        }
    }
    block_6:;
    switch (x_8) {
        case 0: {
            x_10 = x_7;
            goto block_9;
        }
        default: {
            x_11 = lungo_alloc_ctor(0, 3, 1);
            lungo_ctor_set(x_11, 0, x_2);
            lungo_ctor_set(x_11, 1, x_3);
            lungo_ctor_set(x_11, 2, x_4);
            lungo_ctor_set_uint8(x_11, 3 * sizeof(size_t), x_5);
            x_10 = x_11;
            goto block_9;
        }
    }
    block_9:;
    return x_10;
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.WfQuery.exactly */
/* Source: ../../../../formal/CapDAG/Exec.lean:162:1 */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfQuery_dexactly(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_7;
    uint8_t x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_12;
    lungo_obj x_13;
    uint8_t x_14;
    x_2 = lungo_ctor_get(x_1, 0);
    x_3 = lungo_ctor_get(x_1, 1);
    x_4 = lungo_ctor_get(x_1, 2);
    x_5 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    x_14 = !lungo_is_exclusive(x_1);
    switch (x_14) {
        case 0: {
            x_7 = x_1;
            x_8 = x_14;
            goto block_6;
        }
        default: {
            lungo_inc(x_4);
            lungo_inc(x_3);
            lungo_inc(x_2);
            lungo_dec(x_1);
            x_7 = lungo_box(0);
            x_8 = x_14;
            goto block_6;
        }
    }
    block_6:;
    x_9 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfAsk_dexactly(x_2);
    x_10 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfAsk_dexactly(x_3);
    switch (x_8) {
        case 0: {
            lungo_ctor_set(x_7, 1, x_10);
            lungo_ctor_set(x_7, 0, x_9);
            x_12 = x_7;
            goto block_11;
        }
        default: {
            x_13 = lungo_alloc_ctor(0, 3, 1);
            lungo_ctor_set(x_13, 0, x_9);
            lungo_ctor_set(x_13, 1, x_10);
            lungo_ctor_set(x_13, 2, x_4);
            lungo_ctor_set_uint8(x_13, 3 * sizeof(size_t), x_5);
            x_12 = x_13;
            goto block_11;
        }
    }
    block_11:;
    return x_12;
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.WfQuery.toQuery */
/* Source: ../../../../formal/CapDAG/Exec.lean:71:1 */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfQuery_dtoQuery(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_7;
    uint8_t x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_12;
    lungo_obj x_13;
    uint8_t x_14;
    x_2 = lungo_ctor_get(x_1, 0);
    x_3 = lungo_ctor_get(x_1, 1);
    x_4 = lungo_ctor_get(x_1, 2);
    x_5 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    x_14 = !lungo_is_exclusive(x_1);
    switch (x_14) {
        case 0: {
            x_7 = x_1;
            x_8 = x_14;
            goto block_6;
        }
        default: {
            lungo_inc(x_4);
            lungo_inc(x_3);
            lungo_inc(x_2);
            lungo_dec(x_1);
            x_7 = lungo_box(0);
            x_8 = x_14;
            goto block_6;
        }
    }
    block_6:;
    x_9 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfAsk_dtoAsk(x_2);
    x_10 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dWfAsk_dtoAsk(x_3);
    switch (x_8) {
        case 0: {
            lungo_ctor_set(x_7, 1, x_10);
            lungo_ctor_set(x_7, 0, x_9);
            x_12 = x_7;
            goto block_11;
        }
        default: {
            x_13 = lungo_alloc_ctor(0, 3, 1);
            lungo_ctor_set(x_13, 0, x_9);
            lungo_ctor_set(x_13, 1, x_10);
            lungo_ctor_set(x_13, 2, x_4);
            lungo_ctor_set_uint8(x_13, 3 * sizeof(size_t), x_5);
            x_12 = x_13;
            goto block_11;
        }
    }
    block_11:;
    return x_12;
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.askAdmits */
/* Source: ../../../../formal/CapDAG/Exec.lean:116:1 */
uint8_t capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_daskAdmits(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_6;
    uint8_t x_7;
    lungo_obj x_8;
    uint8_t x_9;
    uint8_t x_10;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_3 = (uint8_t)1u;
            return x_3;
        }
        case 1: {
            x_4 = lungo_ctor_get(x_1, 0);
            x_5 = capdagFormal__l_TaggedUrn_dExec_drefines(x_2, x_4);
            return x_5;
        }
        case 2: {
            x_6 = lungo_ctor_get(x_1, 0);
            x_7 = capdagFormal__l_TaggedUrn_dExec_drefines(x_6, x_2);
            return x_7;
        }
        default: {
            x_8 = lungo_ctor_get(x_1, 0);
            x_9 = capdagFormal__l_TaggedUrn_dExec_drefines(x_2, x_8);
            switch (x_9) {
                case 0: {
                    return x_9;
                }
                default: {
                    x_10 = capdagFormal__l_TaggedUrn_dExec_drefines(x_8, x_2);
                    return x_10;
                }
            }
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.askAdmits._boxed */
/* Compiled from: _private.CapDAG.Exec.0.CapDAG.Exec.askAdmits */
/* Source: ../../../../formal/CapDAG/Exec.lean:116:1 */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_daskAdmits_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_daskAdmits(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.askAdmits.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_daskAdmits_dmatch__1_dsplitter(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5, lungo_obj x_6, lungo_obj x_7) {
    (void)x_1;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec(x_7);
            lungo_dec(x_6);
            lungo_dec(x_5);
            x_8 = lungo_apply_1(x_4, x_3);
            return x_8;
        }
        case 1: {
            lungo_dec(x_7);
            lungo_dec(x_6);
            lungo_dec(x_4);
            x_9 = lungo_ctor_get(x_2, 0);
            lungo_inc_ref(x_9);
            lungo_dec_ref(x_2);
            x_10 = lungo_apply_2(x_5, x_9, x_3);
            return x_10;
        }
        case 2: {
            lungo_dec(x_7);
            lungo_dec(x_5);
            lungo_dec(x_4);
            x_11 = lungo_ctor_get(x_2, 0);
            lungo_inc_ref(x_11);
            lungo_dec_ref(x_2);
            x_12 = lungo_apply_2(x_6, x_11, x_3);
            return x_12;
        }
        default: {
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_4);
            x_13 = lungo_ctor_get(x_2, 0);
            lungo_inc_ref(x_13);
            lungo_dec_ref(x_2);
            x_14 = lungo_apply_2(x_7, x_13, x_3);
            return x_14;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.askAdmits.match_1.splitter._redArg */
/* Compiled from: _private.CapDAG.Exec.0.CapDAG.Exec.askAdmits.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_daskAdmits_dmatch__1_dsplitter_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5, lungo_obj x_6) {
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_4);
            x_7 = lungo_apply_1(x_3, x_2);
            return x_7;
        }
        case 1: {
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_3);
            x_8 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_8);
            lungo_dec_ref(x_1);
            x_9 = lungo_apply_2(x_4, x_8, x_2);
            return x_9;
        }
        case 2: {
            lungo_dec(x_6);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_10 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_10);
            lungo_dec_ref(x_1);
            x_11 = lungo_apply_2(x_5, x_10, x_2);
            return x_11;
        }
        default: {
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_12 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_12);
            lungo_dec_ref(x_1);
            x_13 = lungo_apply_2(x_6, x_12, x_2);
            return x_13;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.askMayAdmit */
/* Source: ../../../../formal/CapDAG/Exec.lean:126:1 */
uint8_t capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_daskMayAdmit(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    uint8_t x_5;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            lungo_dec_ref(x_2);
            x_3 = (uint8_t)1u;
            return x_3;
        }
        default: {
            x_4 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_4);
            lungo_dec(x_1);
            x_5 = capdagFormal__l_TaggedUrn_dExec_dmeets(x_2, x_4);
            return x_5;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.askMayAdmit._boxed */
/* Compiled from: _private.CapDAG.Exec.0.CapDAG.Exec.askMayAdmit */
/* Source: ../../../../formal/CapDAG/Exec.lean:126:1 */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_daskMayAdmit_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_daskMayAdmit(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.sameSides */
/* Source: ../../../../formal/CapDAG/Exec.lean:226:1 */
uint8_t capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dsameSides(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    uint8_t x_10;
    uint8_t x_12;
    uint8_t x_13;
    uint8_t x_15;
    uint8_t x_16;
    uint8_t x_17;
    uint8_t x_18;
    uint8_t x_19;
    uint8_t x_20;
    x_3 = lungo_ctor_get(x_2, 0);
    x_4 = lungo_ctor_get(x_2, 1);
    x_5 = lungo_ctor_get(x_2, 2);
    x_6 = lungo_ctor_get_uint8(x_2, 3 * sizeof(size_t));
    x_7 = lungo_ctor_get(x_1, 0);
    x_8 = lungo_ctor_get(x_1, 1);
    x_9 = lungo_ctor_get(x_1, 2);
    x_10 = lungo_ctor_get_uint8(x_1, 3 * sizeof(size_t));
    x_19 = capdagFormal__l_TaggedUrn_dExec_drefines(x_3, x_7);
    switch (x_19) {
        case 0: {
            x_15 = x_19;
            goto block_14;
        }
        default: {
            x_20 = capdagFormal__l_TaggedUrn_dExec_drefines(x_8, x_4);
            x_15 = x_20;
            goto block_14;
        }
    }
    block_14:;
    switch (x_15) {
        case 0: {
            return x_15;
        }
        default: {
            x_16 = (uint8_t)0u;
            x_17 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_10, x_16);
            switch (x_17) {
                case 0: {
                    x_18 = capdagFormal__l_CapDAG_dinstDecidableEqEffect(x_10, x_6);
                    x_12 = x_18;
                    goto block_11;
                }
                default: {
                    x_12 = x_17;
                    goto block_11;
                }
            }
        }
    }
    block_11:;
    switch (x_12) {
        case 0: {
            return x_12;
        }
        default: {
            x_13 = capdagFormal__l_TaggedUrn_dExec_drefines(x_5, x_9);
            return x_13;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.sameSides._boxed */
/* Compiled from: _private.CapDAG.Exec.0.CapDAG.Exec.sameSides */
/* Source: ../../../../formal/CapDAG/Exec.lean:226:1 */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dsameSides_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dsameSides(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.select.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dselect_dmatch__1_dsplitter(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec(x_4);
            x_5 = lungo_box(0);
            x_6 = lungo_apply_1(x_3, x_5);
            return x_6;
        }
        default: {
            lungo_dec(x_3);
            x_7 = lungo_ctor_get(x_2, 0);
            lungo_inc(x_7);
            lungo_dec_ref(x_2);
            x_8 = lungo_apply_1(x_4, x_7);
            return x_8;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.select.match_1.splitter._redArg */
/* Compiled from: _private.CapDAG.Exec.0.CapDAG.Exec.select.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dselect_dmatch__1_dsplitter_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            lungo_dec(x_3);
            x_4 = lungo_box(0);
            x_5 = lungo_apply_1(x_2, x_4);
            return x_5;
        }
        default: {
            lungo_dec(x_2);
            x_6 = lungo_ctor_get(x_1, 0);
            lungo_inc(x_6);
            lungo_dec_ref(x_1);
            x_7 = lungo_apply_1(x_3, x_6);
            return x_7;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.topWf */
/* Source: ../../../../formal/CapDAG/Exec.lean:36:1 */
static lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dtopWf__init(void) {
    lungo_obj x_1;
    x_1 = capdagFormal__l_CapDAG_dmediaTop();
    return x_1;
}
static lungo_lazy_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dtopWf__cell;
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dtopWf(void) {
    return lungo_lazy_obj_get(&capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dtopWf__cell, capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dtopWf__init);
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.unconstrained */
/* Source: ../../../../formal/CapDAG/Exec.lean:39:1 */
uint8_t capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dunconstrained(lungo_obj x_1) {
    lungo_obj x_2;
    uint8_t x_3;
    x_2 = capdagFormal__l_CapDAG_dmediaTop();
    x_3 = capdagFormal__l_TaggedUrn_dExec_drefines(x_2, x_1);
    return x_3;
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.Exec.unconstrained._boxed */
/* Compiled from: _private.CapDAG.Exec.0.CapDAG.Exec.unconstrained */
/* Source: ../../../../formal/CapDAG/Exec.lean:39:1 */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dunconstrained_d__boxed(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    x_2 = capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dExec_dunconstrained(x_1);
    lungo_dec_ref(x_1);
    x_3 = lungo_box((size_t)x_2);
    return x_3;
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.instReprAsk.repr.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dinstReprAsk_drepr_dmatch__1_dsplitter(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5, lungo_obj x_6) {
    (void)x_1;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_4);
            x_7 = lungo_box(0);
            x_8 = lungo_apply_1(x_3, x_7);
            return x_8;
        }
        case 1: {
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_3);
            x_9 = lungo_ctor_get(x_2, 0);
            lungo_inc_ref(x_9);
            lungo_dec_ref(x_2);
            x_10 = lungo_apply_1(x_4, x_9);
            return x_10;
        }
        case 2: {
            lungo_dec(x_6);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_11 = lungo_ctor_get(x_2, 0);
            lungo_inc_ref(x_11);
            lungo_dec_ref(x_2);
            x_12 = lungo_apply_1(x_5, x_11);
            return x_12;
        }
        default: {
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_13 = lungo_ctor_get(x_2, 0);
            lungo_inc_ref(x_13);
            lungo_dec_ref(x_2);
            x_14 = lungo_apply_1(x_6, x_13);
            return x_14;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.instReprAsk.repr.match_1.splitter._redArg */
/* Compiled from: _private.CapDAG.Exec.0.CapDAG.instReprAsk.repr.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dinstReprAsk_drepr_dmatch__1_dsplitter_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5) {
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_6 = lungo_box(0);
            x_7 = lungo_apply_1(x_2, x_6);
            return x_7;
        }
        case 1: {
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_2);
            x_8 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_8);
            lungo_dec_ref(x_1);
            x_9 = lungo_apply_1(x_3, x_8);
            return x_9;
        }
        case 2: {
            lungo_dec(x_5);
            lungo_dec(x_3);
            lungo_dec(x_2);
            x_10 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_10);
            lungo_dec_ref(x_1);
            x_11 = lungo_apply_1(x_4, x_10);
            return x_11;
        }
        default: {
            lungo_dec(x_4);
            lungo_dec(x_3);
            lungo_dec(x_2);
            x_12 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_12);
            lungo_dec_ref(x_1);
            x_13 = lungo_apply_1(x_5, x_12);
            return x_13;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.selectStep.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dselectStep_dmatch__1_dsplitter(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec(x_4);
            x_5 = lungo_box(0);
            x_6 = lungo_apply_1(x_3, x_5);
            return x_6;
        }
        default: {
            lungo_dec(x_3);
            x_7 = lungo_ctor_get(x_2, 0);
            lungo_inc(x_7);
            lungo_dec_ref(x_2);
            x_8 = lungo_apply_1(x_4, x_7);
            return x_8;
        }
    }
}

/* Lean: _private.CapDAG.Exec.0.CapDAG.selectStep.match_1.splitter._redArg */
/* Compiled from: _private.CapDAG.Exec.0.CapDAG.selectStep.match_1.splitter */
/* Source: ../../../../formal/CapDAG/Exec.lean */
lungo_obj capdagFormal__l___private_dCapDAG_dExec_d0_dCapDAG_dselectStep_dmatch__1_dsplitter_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            lungo_dec(x_3);
            x_4 = lungo_box(0);
            x_5 = lungo_apply_1(x_2, x_4);
            return x_5;
        }
        default: {
            lungo_dec(x_2);
            x_6 = lungo_ctor_get(x_1, 0);
            lungo_inc(x_6);
            lungo_dec_ref(x_1);
            x_7 = lungo_apply_1(x_3, x_6);
            return x_7;
        }
    }
}

