/* Generated by lungo 1.83.79 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.Option.Basic. */
#include "capdagFormal_program.h"

/* Lean: Option.instDecidableEq._redArg */
/* Compiled from: Option.instDecidableEq */
/* Source: <lean>/Init/Data/Option/Basic.lean:18:1 */
uint8_t capdagFormal__l_Option_dinstDecidableEq_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    uint8_t x_4;
    uint8_t x_5;
    uint8_t x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    uint8_t x_10;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec_ref(x_1);
            switch (lungo_obj_tag(x_3)) {
                case 0: {
                    x_4 = (uint8_t)1u;
                    return x_4;
                }
                default: {
                    lungo_dec_ref(x_3);
                    x_5 = (uint8_t)0u;
                    return x_5;
                }
            }
        }
        default: {
            switch (lungo_obj_tag(x_3)) {
                case 0: {
                    lungo_dec_ref(x_2);
                    lungo_dec_ref(x_1);
                    x_6 = (uint8_t)0u;
                    return x_6;
                }
                default: {
                    x_7 = lungo_ctor_get(x_2, 0);
                    lungo_inc(x_7);
                    lungo_dec_ref(x_2);
                    x_8 = lungo_ctor_get(x_3, 0);
                    lungo_inc(x_8);
                    lungo_dec_ref(x_3);
                    x_9 = lungo_apply_2(x_1, x_7, x_8);
                    x_10 = (uint8_t)lungo_unbox(x_9);
                    return x_10;
                }
            }
        }
    }
}

