/* Generated by lungo 1.81.24 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.Format.Basic. */
#include "capdagFormal_program.h"

/* Lean: Std.Format.fill */
/* Source: <lean>/Init/Data/Format/Basic.lean:122:1 */
lungo_obj capdagFormal__l_Std_dFormat_dfill(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    x_2 = (uint8_t)1u;
    x_3 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_3, 0, x_1);
    lungo_ctor_set_uint8(x_3, 1 * sizeof(size_t), x_2);
    return x_3;
}

