/* Generated by lungo 1.77.3244 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.String.Defs. */
#include "capdagFormal_program.h"

/* Lean: String.Internal.isEmptyImpl */
/* Source: <lean>/Init/Data/String/Defs.lean:239:1 */
uint8_t capdagFormal__l_String_dInternal_disEmptyImpl(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    uint8_t x_4;
    x_2 = capdagFormal__l_String_dutf8ByteSize(x_1);
    lungo_dec_ref(x_1);
    x_3 = lungo_usize_to_nat(0u);
    x_4 = capdagFormal__l_Nat_ddecEq(x_2, x_3);
    return x_4;
}

/* Lean: String.append */
/* Source: <lean>/Init/Data/String/Defs.lean:83:1 */
lungo_obj capdagFormal__l_String_dappend(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj r = lungo_lean_string_append(x_1, x_2);
    return r;
}

