/* Generated by lungo 1.83.79 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Meta.Defs. */
#include "capdagFormal_program.h"

/* Lean: Lean.Option.hasQuote._redArg._lam_0._closed_1 */
/* Compiled from: Lean.Option.hasQuote */
/* Source: <lean>/Init/Meta/Defs.lean:1468:1 */
static lungo_obj capdagFormal__l_Lean_dOption_dhasQuote_d__redArg_d__lam__0_d__closed__1__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"none", 4, 4);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_Lean_dOption_dhasQuote_d__redArg_d__lam__0_d__closed__1__cell;
lungo_obj capdagFormal__l_Lean_dOption_dhasQuote_d__redArg_d__lam__0_d__closed__1(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_Lean_dOption_dhasQuote_d__redArg_d__lam__0_d__closed__1__cell, capdagFormal__l_Lean_dOption_dhasQuote_d__redArg_d__lam__0_d__closed__1__init);
}

/* Lean: List.elem._at_.Lean.Meta.Occurrences.contains.spec_0 */
/* Compiled from: List.elem */
/* Source: <lean>/Init/Data/List/Basic.lean:783:1 */
uint8_t capdagFormal__l_List_delem_d__at___dLean_dMeta_dOccurrences_dcontains_dspec__0(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    uint8_t x_6;
    _start:
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            x_3 = (uint8_t)0u;
            return x_3;
        }
        default: {
            x_4 = lungo_ctor_get(x_2, 0);
            x_5 = lungo_ctor_get(x_2, 1);
            x_6 = capdagFormal__l_Nat_ddecEq(x_1, x_4);
            switch (x_6) {
                case 0: {
                    {
                        lungo_obj t_0 = x_1;
                        lungo_obj t_1 = x_5;
                        x_1 = t_0;
                        x_2 = t_1;
                        goto _start;
                    }
                }
                default: {
                    return x_6;
                }
            }
        }
    }
}

/* Lean: List.foldl._at_.List.foldl._at_.Std.Format.joinSep._at_.List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0.spec_0.spec_1.spec_3 */
/* Compiled from: List.foldl */
/* Source: <lean>/Init/Prelude.lean:3102:1 */
lungo_obj capdagFormal__l_List_dfoldl_d__at___dList_dfoldl_d__at___dStd_dFormat_djoinSep_d__at___dList_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_dspec__0_dspec__1_dspec__3(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_7;
    uint8_t x_8;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_15;
    uint8_t x_16;
    _start:
    switch (lungo_obj_tag(x_3)) {
        case 0: {
            lungo_dec(x_1);
            return x_2;
        }
        default: {
            x_4 = lungo_ctor_get(x_3, 0);
            x_5 = lungo_ctor_get(x_3, 1);
            x_16 = !lungo_is_exclusive(x_3);
            switch (x_16) {
                case 0: {
                    x_7 = x_3;
                    x_8 = x_16;
                    goto block_6;
                }
                default: {
                    lungo_inc(x_5);
                    lungo_inc(x_4);
                    lungo_dec(x_3);
                    x_7 = lungo_box(0);
                    x_8 = x_16;
                    goto block_6;
                }
            }
            block_6:;
            lungo_inc(x_1);
            switch (x_8) {
                case 0: {
                    lungo_ctor_set_tag(x_7, 5);
                    lungo_ctor_set(x_7, 1, x_1);
                    lungo_ctor_set(x_7, 0, x_2);
                    x_10 = x_7;
                    goto block_9;
                }
                default: {
                    x_15 = lungo_alloc_ctor(5, 2, 0);
                    lungo_ctor_set(x_15, 0, x_2);
                    lungo_ctor_set(x_15, 1, x_1);
                    x_10 = x_15;
                    goto block_9;
                }
            }
            block_9:;
            x_11 = capdagFormal__l_String_dquote(x_4);
            x_12 = lungo_alloc_ctor(3, 1, 0);
            lungo_ctor_set(x_12, 0, x_11);
            x_13 = lungo_alloc_ctor(5, 2, 0);
            lungo_ctor_set(x_13, 0, x_10);
            lungo_ctor_set(x_13, 1, x_12);
            {
                lungo_obj t_0 = x_1;
                lungo_obj t_1 = x_13;
                lungo_obj t_2 = x_5;
                x_1 = t_0;
                x_2 = t_1;
                x_3 = t_2;
                goto _start;
            }
        }
    }
}

/* Lean: List.foldl._at_.Std.Format.joinSep._at_.List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0.spec_0.spec_1 */
/* Compiled from: List.foldl */
/* Source: <lean>/Init/Prelude.lean:3102:1 */
lungo_obj capdagFormal__l_List_dfoldl_d__at___dStd_dFormat_djoinSep_d__at___dList_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_dspec__0_dspec__1(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_7;
    uint8_t x_8;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    lungo_obj x_15;
    uint8_t x_16;
    switch (lungo_obj_tag(x_3)) {
        case 0: {
            lungo_dec(x_1);
            return x_2;
        }
        default: {
            x_4 = lungo_ctor_get(x_3, 0);
            x_5 = lungo_ctor_get(x_3, 1);
            x_16 = !lungo_is_exclusive(x_3);
            switch (x_16) {
                case 0: {
                    x_7 = x_3;
                    x_8 = x_16;
                    goto block_6;
                }
                default: {
                    lungo_inc(x_5);
                    lungo_inc(x_4);
                    lungo_dec(x_3);
                    x_7 = lungo_box(0);
                    x_8 = x_16;
                    goto block_6;
                }
            }
            block_6:;
            lungo_inc(x_1);
            switch (x_8) {
                case 0: {
                    lungo_ctor_set_tag(x_7, 5);
                    lungo_ctor_set(x_7, 1, x_1);
                    lungo_ctor_set(x_7, 0, x_2);
                    x_10 = x_7;
                    goto block_9;
                }
                default: {
                    x_15 = lungo_alloc_ctor(5, 2, 0);
                    lungo_ctor_set(x_15, 0, x_2);
                    lungo_ctor_set(x_15, 1, x_1);
                    x_10 = x_15;
                    goto block_9;
                }
            }
            block_9:;
            x_11 = capdagFormal__l_String_dquote(x_4);
            x_12 = lungo_alloc_ctor(3, 1, 0);
            lungo_ctor_set(x_12, 0, x_11);
            x_13 = lungo_alloc_ctor(5, 2, 0);
            lungo_ctor_set(x_13, 0, x_10);
            lungo_ctor_set(x_13, 1, x_12);
            x_14 = capdagFormal__l_List_dfoldl_d__at___dList_dfoldl_d__at___dStd_dFormat_djoinSep_d__at___dList_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_dspec__0_dspec__1_dspec__3(x_1, x_13, x_5);
            return x_14;
        }
    }
}

/* Lean: List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0._redArg */
/* Compiled from: List.repr' */
/* Source: <lean>/Init/Data/Repr.lean:440:1 */
lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_2 = capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__1();
            return x_2;
        }
        default: {
            x_3 = capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__5();
            x_4 = capdagFormal__l_Std_dFormat_djoinSep_d__at___dList_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_dspec__0(x_1, x_3);
            x_5 = capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__8();
            x_6 = capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__9();
            x_7 = lungo_alloc_ctor(5, 2, 0);
            lungo_ctor_set(x_7, 0, x_6);
            lungo_ctor_set(x_7, 1, x_4);
            x_8 = capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__10();
            x_9 = lungo_alloc_ctor(5, 2, 0);
            lungo_ctor_set(x_9, 0, x_7);
            lungo_ctor_set(x_9, 1, x_8);
            x_10 = lungo_alloc_ctor(4, 2, 0);
            lungo_ctor_set(x_10, 0, x_5);
            lungo_ctor_set(x_10, 1, x_9);
            x_11 = capdagFormal__l_Std_dFormat_dfill(x_10);
            return x_11;
        }
    }
}

/* Lean: List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0._redArg._closed_0 */
/* Compiled from: List.repr' */
/* Source: <lean>/Init/Data/Repr.lean:440:1 */
static lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"[]", 2, 2);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__0__cell;
lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__0__cell, capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__0__init);
}

/* Lean: List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0._redArg._closed_1 */
/* Compiled from: List.repr' */
/* Source: <lean>/Init/Data/Repr.lean:440:1 */
static lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__1__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__0();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__1__cell;
lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__1(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__1__cell, capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__1__init);
}

/* Lean: List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0._redArg._closed_10 */
/* Compiled from: List.repr' */
/* Source: <lean>/Init/Data/Repr.lean:440:1 */
static lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__10__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__6();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__10__cell;
lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__10(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__10__cell, capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__10__init);
}

/* Lean: List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0._redArg._closed_2 */
/* Compiled from: List.repr' */
/* Source: <lean>/Init/Data/Repr.lean:440:1 */
static lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__2__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"[", 1, 1);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__2__cell;
lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__2(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__2__cell, capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__2__init);
}

/* Lean: List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0._redArg._closed_3 */
/* Compiled from: List.repr' */
/* Source: <lean>/Init/Data/Repr.lean:440:1 */
static lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__3__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)",", 1, 1);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__3__cell;
lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__3(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__3__cell, capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__3__init);
}

/* Lean: List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0._redArg._closed_4 */
/* Compiled from: List.repr' */
/* Source: <lean>/Init/Data/Repr.lean:440:1 */
static lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__4__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__3();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__4__cell;
lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__4(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__4__cell, capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__4__init);
}

/* Lean: List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0._redArg._closed_5 */
/* Compiled from: List.repr' */
/* Source: <lean>/Init/Data/Repr.lean:440:1 */
static lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__5__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    lungo_obj x_3;
    x_1 = lungo_box(1);
    x_2 = capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__4();
    x_3 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set(x_3, 1, x_1);
    return x_3;
}
static lungo_lazy_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__5__cell;
lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__5(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__5__cell, capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__5__init);
}

/* Lean: List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0._redArg._closed_6 */
/* Compiled from: List.repr' */
/* Source: <lean>/Init/Data/Repr.lean:440:1 */
static lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__6__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"]", 1, 1);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__6__cell;
lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__6(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__6__cell, capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__6__init);
}

/* Lean: List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0._redArg._closed_7 */
/* Compiled from: List.repr' */
/* Source: <lean>/Init/Data/Repr.lean:440:1 */
static lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__7__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__2();
    x_2 = capdagFormal__l_String_dInternal_dlength(x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__7__cell;
lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__7(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__7__cell, capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__7__init);
}

/* Lean: List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0._redArg._closed_8 */
/* Compiled from: List.repr' */
/* Source: <lean>/Init/Data/Repr.lean:440:1 */
static lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__8__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__7();
    x_2 = capdagFormal__l_Int_dofNat(x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__8__cell;
lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__8(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__8__cell, capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__8__init);
}

/* Lean: List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0._redArg._closed_9 */
/* Compiled from: List.repr' */
/* Source: <lean>/Init/Data/Repr.lean:440:1 */
static lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__9__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__2();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__9__cell;
lungo_obj capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__9(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__9__cell, capdagFormal__l_List_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_d__redArg_d__closed__9__init);
}

/* Lean: Option.repr._at_.Lean.Meta.instReprConfig_1.repr.spec_0 */
/* Compiled from: Option.repr */
/* Source: <lean>/Init/Data/Repr.lean:113:1 */
lungo_obj capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_6;
    uint8_t x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    uint8_t x_15;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_3 = capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__0();
            return x_3;
        }
        default: {
            x_4 = lungo_ctor_get(x_1, 0);
            x_15 = !lungo_is_exclusive(x_1);
            switch (x_15) {
                case 0: {
                    x_6 = x_1;
                    x_7 = x_15;
                    goto block_5;
                }
                default: {
                    lungo_inc(x_4);
                    lungo_dec(x_1);
                    x_6 = lungo_box(0);
                    x_7 = x_15;
                    goto block_5;
                }
            }
            block_5:;
            x_8 = capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__2();
            x_9 = capdagFormal__l_Nat_dreprFast(x_4);
            switch (x_7) {
                case 0: {
                    lungo_ctor_set_tag(x_6, 3);
                    lungo_ctor_set(x_6, 0, x_9);
                    x_11 = x_6;
                    goto block_10;
                }
                default: {
                    x_14 = lungo_alloc_ctor(3, 1, 0);
                    lungo_ctor_set(x_14, 0, x_9);
                    x_11 = x_14;
                    goto block_10;
                }
            }
            block_10:;
            x_12 = lungo_alloc_ctor(5, 2, 0);
            lungo_ctor_set(x_12, 0, x_8);
            lungo_ctor_set(x_12, 1, x_11);
            x_13 = capdagFormal__l_Repr_daddAppParen(x_12, x_2);
            return x_13;
        }
    }
}

/* Lean: Option.repr._at_.Lean.Meta.instReprConfig_1.repr.spec_0._closed_0 */
/* Compiled from: Option.repr */
/* Source: <lean>/Init/Data/Repr.lean:113:1 */
static lungo_obj capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__0__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_Lean_dOption_dhasQuote_d__redArg_d__lam__0_d__closed__1();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__0__cell;
lungo_obj capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__0__cell, capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__0__init);
}

/* Lean: Option.repr._at_.Lean.Meta.instReprConfig_1.repr.spec_0._closed_1 */
/* Compiled from: Option.repr */
/* Source: <lean>/Init/Data/Repr.lean:113:1 */
static lungo_obj capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__1__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"some ", 5, 5);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__1__cell;
lungo_obj capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__1(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__1__cell, capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__1__init);
}

/* Lean: Option.repr._at_.Lean.Meta.instReprConfig_1.repr.spec_0._closed_2 */
/* Compiled from: Option.repr */
/* Source: <lean>/Init/Data/Repr.lean:113:1 */
static lungo_obj capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__2__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__1();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__2__cell;
lungo_obj capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__2(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__2__cell, capdagFormal__l_Option_drepr_d__at___dLean_dMeta_dinstReprConfig__1_drepr_dspec__0_d__closed__2__init);
}

/* Lean: Std.Format.joinSep._at_.List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0.spec_0 */
/* Compiled from: Std.Format.joinSep */
/* Source: <lean>/Init/Data/Format/Basic.lean:443:1 */
lungo_obj capdagFormal__l_Std_dFormat_djoinSep_d__at___dList_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_dspec__0(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            lungo_dec(x_2);
            x_3 = lungo_box(0);
            return x_3;
        }
        default: {
            x_4 = lungo_ctor_get(x_1, 1);
            switch (lungo_obj_tag(x_4)) {
                case 0: {
                    lungo_dec(x_2);
                    x_5 = lungo_ctor_get(x_1, 0);
                    lungo_inc(x_5);
                    lungo_dec_ref(x_1);
                    x_6 = capdagFormal__l_Std_dFormat_djoinSep_d__at___dList_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_dspec__0_d__lam__0(x_5);
                    return x_6;
                }
                default: {
                    lungo_inc(x_4);
                    x_7 = lungo_ctor_get(x_1, 0);
                    lungo_inc(x_7);
                    lungo_dec_ref(x_1);
                    x_8 = capdagFormal__l_Std_dFormat_djoinSep_d__at___dList_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_dspec__0_d__lam__0(x_7);
                    x_9 = capdagFormal__l_List_dfoldl_d__at___dStd_dFormat_djoinSep_d__at___dList_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_dspec__0_dspec__1(x_2, x_8, x_4);
                    return x_9;
                }
            }
        }
    }
}

/* Lean: Std.Format.joinSep._at_.List.repr'._at_.Lean.Syntax.instReprPreresolved.repr.spec_0.spec_0._lam_0 */
/* Compiled from: Std.Format.joinSep */
/* Source: <lean>/Init/Data/Format/Basic.lean:443:1 */
lungo_obj capdagFormal__l_Std_dFormat_djoinSep_d__at___dList_drepr_x27__d__at___dLean_dSyntax_dinstReprPreresolved_drepr_dspec__0_dspec__0_d__lam__0(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    x_2 = capdagFormal__l_String_dquote(x_1);
    x_3 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_3, 0, x_2);
    return x_3;
}

