/* Generated by lungo 1.87.175 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Prelude. */
#include "capdagFormal_program.h"

/* Lean: Array.getInternalBorrowed */
/* Source: <lean>/Init/Prelude.lean:3272:1 */
lungo_obj capdagFormal__l_Array_dgetInternalBorrowed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    (void)x_4;
    lungo_obj r = lungo_lean_array_fget_borrowed(x_2, x_3);
    return r;
}

/* Lean: Array.mk */
/* Source: <lean>/Init/Prelude.lean:3210:3 */
lungo_obj capdagFormal__l_Array_dmk(lungo_obj x_1, lungo_obj x_2) {
    (void)x_1;
    lungo_obj r = lungo_lean_array_mk(x_2);
    return r;
}

/* Lean: Array.mkEmpty */
/* Source: <lean>/Init/Prelude.lean:3235:1 */
lungo_obj capdagFormal__l_Array_dmkEmpty(lungo_obj x_1, lungo_obj x_2) {
    (void)x_1;
    lungo_obj r = lungo_lean_mk_empty_array_with_capacity(x_2);
    return r;
}

/* Lean: Array.push */
/* Source: <lean>/Init/Prelude.lean:3327:1 */
lungo_obj capdagFormal__l_Array_dpush(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    (void)x_1;
    lungo_obj r = lungo_lean_array_push(x_2, x_3);
    return r;
}

/* Lean: Array.size */
/* Source: <lean>/Init/Prelude.lean:3259:1 */
lungo_obj capdagFormal__l_Array_dsize(lungo_obj x_1, lungo_obj x_2) {
    (void)x_1;
    lungo_obj r = lungo_lean_array_get_size(x_2);
    return r;
}

/* Lean: Array.toList */
/* Source: <lean>/Init/Prelude.lean:3217:3 */
lungo_obj capdagFormal__l_Array_dtoList(lungo_obj x_1, lungo_obj x_2) {
    (void)x_1;
    lungo_obj r = lungo_lean_array_to_list(x_2);
    return r;
}

/* Lean: ByteArray.size */
/* Source: <lean>/Init/Prelude.lean:3472:1 */
lungo_obj capdagFormal__l_ByteArray_dsize(lungo_obj x_1) {
    lungo_obj r = lungo_lean_byte_array_size(x_1);
    return r;
}

/* Lean: List.hasDecEq._redArg */
/* Compiled from: List.hasDecEq */
/* Source: <lean>/Init/Prelude.lean:2993:1 */
uint8_t capdagFormal__l_List_dhasDecEq_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    uint8_t x_4;
    uint8_t x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    uint8_t x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    uint8_t x_11;
    lungo_obj x_12;
    uint8_t x_13;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec_ref(x_1);
            switch (lungo_obj_tag(x_3)) {
                case 0: {
                    x_4 = (uint8_t)1u;
                    return x_4;
                }
                default: {
                    lungo_dec_ref(x_3);
                    x_5 = (uint8_t)0u;
                    return x_5;
                }
            }
        }
        default: {
            x_6 = lungo_ctor_get(x_2, 0);
            lungo_inc(x_6);
            x_7 = lungo_ctor_get(x_2, 1);
            lungo_inc(x_7);
            lungo_dec_ref(x_2);
            x_8 = (uint8_t)0u;
            switch (lungo_obj_tag(x_3)) {
                case 0: {
                    lungo_dec(x_7);
                    lungo_dec(x_6);
                    lungo_dec_ref(x_1);
                    return x_8;
                }
                default: {
                    x_9 = lungo_ctor_get(x_3, 0);
                    lungo_inc(x_9);
                    x_10 = lungo_ctor_get(x_3, 1);
                    lungo_inc(x_10);
                    lungo_dec_ref(x_3);
                    lungo_inc_ref(x_1);
                    x_11 = capdagFormal__l_List_dhasDecEq_d__redArg(x_1, x_7, x_10);
                    x_12 = lungo_apply_2(x_1, x_6, x_9);
                    x_13 = (uint8_t)lungo_unbox(x_12);
                    switch (x_13) {
                        case 0: {
                            return x_8;
                        }
                        default: {
                            switch (x_11) {
                                case 0: {
                                    return x_8;
                                }
                                default: {
                                    return x_11;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

/* Lean: List.instDecidableEqNil._redArg */
/* Compiled from: List.instDecidableEqNil */
/* Source: <lean>/Init/Prelude.lean:3033:1 */
uint8_t capdagFormal__l_List_dinstDecidableEqNil_d__redArg(lungo_obj x_1) {
    uint8_t x_2;
    uint8_t x_3;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_2 = (uint8_t)1u;
            return x_2;
        }
        default: {
            x_3 = (uint8_t)0u;
            return x_3;
        }
    }
}

/* Lean: List.lengthTR._redArg */
/* Compiled from: List.lengthTR */
/* Source: <lean>/Init/Prelude.lean:3061:1 */
lungo_obj capdagFormal__l_List_dlengthTR_d__redArg(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    x_2 = lungo_usize_to_nat(0u);
    x_3 = capdagFormal__l_List_dlengthTRAux_d__redArg(x_1, x_2);
    return x_3;
}

/* Lean: List.lengthTRAux._redArg */
/* Compiled from: List.lengthTRAux */
/* Source: <lean>/Init/Prelude.lean:3056:1 */
lungo_obj capdagFormal__l_List_dlengthTRAux_d__redArg(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    _start:
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            return x_2;
        }
        default: {
            x_3 = lungo_ctor_get(x_1, 1);
            x_4 = lungo_usize_to_nat(1u);
            x_5 = capdagFormal__l_Nat_dadd(x_2, x_4);
            lungo_dec(x_2);
            {
                lungo_obj t_0 = x_3;
                lungo_obj t_1 = x_5;
                x_1 = t_0;
                x_2 = t_1;
                goto _start;
            }
        }
    }
}

/* Lean: Nat.add */
/* Source: <lean>/Init/Prelude.lean:1764:1 */
lungo_obj capdagFormal__l_Nat_dadd(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj r = lungo_lean_nat_add(x_1, x_2);
    return r;
}

/* Lean: Nat.ble */
/* Source: <lean>/Init/Prelude.lean:1881:1 */
uint8_t capdagFormal__l_Nat_dble(lungo_obj x_1, lungo_obj x_2) {
    uint8_t r = lungo_lean_nat_dec_le(x_1, x_2);
    return r;
}

/* Lean: Nat.decEq */
/* Source: <lean>/Init/Prelude.lean:1860:1 */
uint8_t capdagFormal__l_Nat_ddecEq(lungo_obj x_1, lungo_obj x_2) {
    uint8_t r = lungo_lean_nat_dec_eq(x_1, x_2);
    return r;
}

/* Lean: Nat.decLe */
/* Source: <lean>/Init/Prelude.lean:2079:1 */
uint8_t capdagFormal__l_Nat_ddecLe(lungo_obj x_1, lungo_obj x_2) {
    uint8_t r = lungo_lean_nat_dec_le(x_1, x_2);
    return r;
}

/* Lean: Nat.decLt */
/* Source: <lean>/Init/Prelude.lean:2093:1 */
uint8_t capdagFormal__l_Nat_ddecLt(lungo_obj x_1, lungo_obj x_2) {
    uint8_t r = lungo_lean_nat_dec_lt(x_1, x_2);
    return r;
}

/* Lean: Nat.div */
/* Source: <lean>/Init/Prelude.lean:2170:1 */
lungo_obj capdagFormal__l_Nat_ddiv(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj r = lungo_lean_nat_div(x_1, x_2);
    return r;
}

/* Lean: Nat.mod */
/* Source: <lean>/Init/Prelude.lean:2248:1 */
lungo_obj capdagFormal__l_Nat_dmod(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj r = lungo_lean_nat_mod(x_1, x_2);
    return r;
}

/* Lean: Nat.mul */
/* Source: <lean>/Init/Prelude.lean:1785:1 */
lungo_obj capdagFormal__l_Nat_dmul(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj r = lungo_lean_nat_mul(x_1, x_2);
    return r;
}

/* Lean: Nat.pow */
/* Source: <lean>/Init/Prelude.lean:1802:1 */
lungo_obj capdagFormal__l_Nat_dpow(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj r = lungo_lean_nat_pow(x_1, x_2);
    return r;
}

/* Lean: Nat.sub */
/* Source: <lean>/Init/Prelude.lean:2110:1 */
lungo_obj capdagFormal__l_Nat_dsub(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj r = lungo_lean_nat_sub(x_1, x_2);
    return r;
}

/* Lean: String.decEq */
/* Source: <lean>/Init/Prelude.lean:3563:1 */
uint8_t capdagFormal__l_String_ddecEq(lungo_obj x_1, lungo_obj x_2) {
    uint8_t r = lungo_lean_string_dec_eq(x_1, x_2);
    return r;
}

/* Lean: String.ofList */
/* Source: <lean>/Init/Prelude.lean:3551:1 */
lungo_obj capdagFormal__l_String_dofList(lungo_obj x_1) {
    lungo_obj r = lungo_lean_string_mk(x_1);
    return r;
}

/* Lean: String.utf8ByteSize */
/* Source: <lean>/Init/Prelude.lean:3634:1 */
lungo_obj capdagFormal__l_String_dutf8ByteSize(lungo_obj x_1) {
    lungo_obj r = lungo_lean_string_utf8_byte_size(x_1);
    return r;
}

/* Lean: System.Platform.getNumBits */
/* Source: <lean>/Init/Prelude.lean:2297:1 */
lungo_obj capdagFormal__l_System_dPlatform_dgetNumBits(lungo_obj x_1) {
    lungo_obj r = lungo_lean_system_platform_nbits(x_1);
    return r;
}

/* Lean: System.Platform.numBits */
/* Source: <lean>/Init/Prelude.lean:2308:1 */
static lungo_obj capdagFormal__l_System_dPlatform_dnumBits__init(void) {
    lungo_obj x_1;
    x_1 = capdagFormal__l_System_dPlatform_dnumBits_d__closed__0();
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_System_dPlatform_dnumBits__cell;
lungo_obj capdagFormal__l_System_dPlatform_dnumBits(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_System_dPlatform_dnumBits__cell, capdagFormal__l_System_dPlatform_dnumBits__init);
}

/* Lean: System.Platform.numBits._closed_0 */
/* Compiled from: System.Platform.numBits */
/* Source: <lean>/Init/Prelude.lean:2308:1 */
static lungo_obj capdagFormal__l_System_dPlatform_dnumBits_d__closed__0__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = lungo_box(0);
    x_2 = capdagFormal__l_System_dPlatform_dgetNumBits(x_1);
    return x_2;
}
static lungo_lazy_obj capdagFormal__l_System_dPlatform_dnumBits_d__closed__0__cell;
lungo_obj capdagFormal__l_System_dPlatform_dnumBits_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_System_dPlatform_dnumBits_d__closed__0__cell, capdagFormal__l_System_dPlatform_dnumBits_d__closed__0__init);
}

/* Lean: UInt32.decEq */
/* Source: <lean>/Init/Prelude.lean:2650:1 */
uint8_t capdagFormal__l_UInt32_ddecEq(uint32_t x_1, uint32_t x_2) {
    uint8_t r = lungo_lean_uint32_dec_eq(x_1, x_2);
    return r;
}

/* Lean: UInt32.decLe */
/* Source: <lean>/Init/Prelude.lean:2693:1 */
uint8_t capdagFormal__l_UInt32_ddecLe(uint32_t x_1, uint32_t x_2) {
    uint8_t r = lungo_lean_uint32_dec_le(x_1, x_2);
    return r;
}

/* Lean: UInt32.toNat */
/* Source: <lean>/Init/Prelude.lean:2641:1 */
lungo_obj capdagFormal__l_UInt32_dtoNat(uint32_t x_1) {
    lungo_obj r = lungo_lean_uint32_to_nat(x_1);
    return r;
}

/* Lean: USize.ofNatLT */
/* Source: <lean>/Init/Prelude.lean:2807:1 */
size_t capdagFormal__l_USize_dofNatLT(lungo_obj x_1, lungo_obj x_2) {
    (void)x_2;
    size_t r = lungo_lean_usize_of_nat(x_1);
    return r;
}

/* Lean: instDecidableEqList._redArg */
/* Compiled from: instDecidableEqList */
/* Source: <lean>/Init/Prelude.lean:3006:1 */
uint8_t capdagFormal__l_instDecidableEqList_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    uint8_t x_4;
    uint8_t x_5;
    uint8_t x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    uint8_t x_11;
    lungo_obj x_12;
    uint8_t x_13;
    uint8_t x_14;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec_ref(x_1);
            switch (lungo_obj_tag(x_3)) {
                case 0: {
                    x_4 = (uint8_t)1u;
                    return x_4;
                }
                default: {
                    lungo_dec_ref(x_3);
                    x_5 = (uint8_t)0u;
                    return x_5;
                }
            }
        }
        default: {
            switch (lungo_obj_tag(x_3)) {
                case 0: {
                    lungo_dec_ref(x_2);
                    lungo_dec_ref(x_1);
                    x_6 = (uint8_t)0u;
                    return x_6;
                }
                default: {
                    x_7 = lungo_ctor_get(x_2, 0);
                    lungo_inc(x_7);
                    x_8 = lungo_ctor_get(x_2, 1);
                    lungo_inc(x_8);
                    lungo_dec_ref(x_2);
                    x_9 = lungo_ctor_get(x_3, 0);
                    lungo_inc(x_9);
                    x_10 = lungo_ctor_get(x_3, 1);
                    lungo_inc(x_10);
                    lungo_dec_ref(x_3);
                    lungo_inc_ref(x_1);
                    x_11 = capdagFormal__l_List_dhasDecEq_d__redArg(x_1, x_8, x_10);
                    x_12 = lungo_apply_2(x_1, x_7, x_9);
                    x_13 = (uint8_t)lungo_unbox(x_12);
                    switch (x_13) {
                        case 0: {
                            x_14 = (uint8_t)lungo_unbox(x_12);
                            return x_14;
                        }
                        default: {
                            return x_11;
                        }
                    }
                }
            }
        }
    }
}

/* Lean: instDecidableEqNat */
/* Source: <lean>/Init/Prelude.lean:1878:1 */
uint8_t capdagFormal__l_instDecidableEqNat(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    x_3 = capdagFormal__l_Nat_ddecEq(x_1, x_2);
    return x_3;
}

/* Lean: instDecidableEqNat._boxed */
/* Compiled from: instDecidableEqNat */
/* Source: <lean>/Init/Prelude.lean:1878:1 */
lungo_obj capdagFormal__l_instDecidableEqNat_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_instDecidableEqNat(x_1, x_2);
    lungo_dec(x_2);
    lungo_dec(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: instDecidableEqString */
/* Source: <lean>/Init/Prelude.lean:3577:1 */
uint8_t capdagFormal__l_instDecidableEqString(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    x_3 = capdagFormal__l_String_ddecEq(x_1, x_2);
    return x_3;
}

/* Lean: instDecidableEqString._boxed */
/* Compiled from: instDecidableEqString */
/* Source: <lean>/Init/Prelude.lean:3577:1 */
lungo_obj capdagFormal__l_instDecidableEqString_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_instDecidableEqString(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: panicCore */
/* Source: <lean>/Init/Prelude.lean:3696:1 */
lungo_obj capdagFormal__l_panicCore(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    (void)x_1;
    lungo_obj r = lungo_lean_panic_fn_borrowed(x_2, x_3);
    return r;
}

