/* Generated by lungo 1.87.175 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.Int.Basic. */
#include "capdagFormal_program.h"

/* Lean: Int.add */
/* Source: <lean>/Init/Data/Int/Basic.lean:152:1 */
lungo_obj capdagFormal__l_Int_dadd(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj r = lungo_lean_int_add(x_1, x_2);
    return r;
}

/* Lean: Int.decLt */
/* Source: <lean>/Init/Data/Int/Basic.lean:303:1 */
uint8_t capdagFormal__l_Int_ddecLt(lungo_obj x_1, lungo_obj x_2) {
    uint8_t r = lungo_lean_int_dec_lt(x_1, x_2);
    return r;
}

/* Lean: Int.natAbs */
/* Source: <lean>/Init/Data/Int/Basic.lean:317:1 */
lungo_obj capdagFormal__l_Int_dnatAbs(lungo_obj x_1) {
    lungo_obj r = lungo_lean_nat_abs(x_1);
    return r;
}

/* Lean: Int.ofNat */
/* Source: <lean>/Init/Data/Int/Basic.lean:47:3 */
lungo_obj capdagFormal__l_Int_dofNat(lungo_obj x_1) {
    lungo_obj r = lungo_lean_nat_to_int(x_1);
    return r;
}

/* Lean: Int.sub */
/* Source: <lean>/Init/Data/Int/Basic.lean:197:1 */
lungo_obj capdagFormal__l_Int_dsub(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj r = lungo_lean_int_sub(x_1, x_2);
    return r;
}

