/* Generated by lungo 1.77.3244 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module TaggedUrn.Sorted. */
#include "capdagFormal_program.h"

/* Lean: List.all._at_.TaggedUrn.mergeTags.spec_0 */
/* Compiled from: List.all */
/* Source: <lean>/Init/Data/List/Basic.lean:1915:1 */
uint8_t capdagFormal__l_List_dall_d__at___dTaggedUrn_dmergeTags_dspec__0(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    _start:
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_2 = (uint8_t)1u;
            return x_2;
        }
        default: {
            x_3 = lungo_ctor_get(x_1, 0);
            x_4 = lungo_ctor_get(x_1, 1);
            x_5 = lungo_ctor_get(x_3, 1);
            x_6 = lungo_box(0);
            x_7 = capdagFormal__l_TaggedUrn_dtagMatch(x_6, x_5);
            switch (x_7) {
                case 0: {
                    return x_7;
                }
                default: {
                    {
                        lungo_obj t_0 = x_4;
                        x_1 = t_0;
                        goto _start;
                    }
                }
            }
        }
    }
}

/* Lean: List.all._at_.TaggedUrn.mergeTags.spec_1 */
/* Compiled from: List.all */
/* Source: <lean>/Init/Data/List/Basic.lean:1915:1 */
uint8_t capdagFormal__l_List_dall_d__at___dTaggedUrn_dmergeTags_dspec__1(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    _start:
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_2 = (uint8_t)1u;
            return x_2;
        }
        default: {
            x_3 = lungo_ctor_get(x_1, 0);
            x_4 = lungo_ctor_get(x_1, 1);
            x_5 = lungo_ctor_get(x_3, 1);
            x_6 = lungo_box(0);
            x_7 = capdagFormal__l_TaggedUrn_dtagMatch(x_5, x_6);
            switch (x_7) {
                case 0: {
                    return x_7;
                }
                default: {
                    {
                        lungo_obj t_0 = x_4;
                        x_1 = t_0;
                        goto _start;
                    }
                }
            }
        }
    }
}

/* Lean: TaggedUrn.instDecidableSorted */
/* Source: ../../../../formal/../../tagged-urn/formal/TaggedUrn/Sorted.lean:29:1 */
uint8_t capdagFormal__l_TaggedUrn_dinstDecidableSorted(lungo_obj x_1) {
    lungo_obj x_2;
    uint8_t x_3;
    x_2 = capdagFormal__l_TaggedUrn_dinstDecidableSorted_d__closed__0();
    x_3 = capdagFormal__l_List_dinstDecidablePairwise_d__redArg(x_2, x_1);
    return x_3;
}

/* Lean: TaggedUrn.instDecidableSorted._closed_0 */
/* Compiled from: TaggedUrn.instDecidableSorted */
/* Source: ../../../../formal/../../tagged-urn/formal/TaggedUrn/Sorted.lean:29:1 */
static lungo_obj capdagFormal__l_TaggedUrn_dinstDecidableSorted_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_alloc_closure((void *)capdagFormal__l_TaggedUrn_dinstDecidableSorted_d__lam__0_d__boxed, 2, 0);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_TaggedUrn_dinstDecidableSorted_d__closed__0__cell;
lungo_obj capdagFormal__l_TaggedUrn_dinstDecidableSorted_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_TaggedUrn_dinstDecidableSorted_d__closed__0__cell, capdagFormal__l_TaggedUrn_dinstDecidableSorted_d__closed__0__init);
}

/* Lean: TaggedUrn.instDecidableSorted._lam_0 */
/* Compiled from: TaggedUrn.instDecidableSorted */
/* Source: ../../../../formal/../../tagged-urn/formal/TaggedUrn/Sorted.lean:29:1 */
uint8_t capdagFormal__l_TaggedUrn_dinstDecidableSorted_d__lam__0(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    x_3 = lungo_ctor_get(x_1, 0);
    x_4 = lungo_ctor_get(x_2, 0);
    x_5 = capdagFormal__l_String_ddecidableLT(x_3, x_4);
    return x_5;
}

/* Lean: TaggedUrn.instDecidableSorted._lam_0._boxed */
/* Compiled from: TaggedUrn.instDecidableSorted */
/* Source: ../../../../formal/../../tagged-urn/formal/TaggedUrn/Sorted.lean:29:1 */
lungo_obj capdagFormal__l_TaggedUrn_dinstDecidableSorted_d__lam__0_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = capdagFormal__l_TaggedUrn_dinstDecidableSorted_d__lam__0(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.mergeTags */
/* Source: ../../../../formal/../../tagged-urn/formal/TaggedUrn/Sorted.lean:81:1 */
uint8_t capdagFormal__l_TaggedUrn_dmergeTags(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    uint8_t x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    uint8_t x_13;
    uint8_t x_14;
    uint8_t x_15;
    lungo_obj x_17;
    uint8_t x_18;
    lungo_obj x_20;
    uint8_t x_21;
    _start:
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_3 = capdagFormal__l_List_dall_d__at___dTaggedUrn_dmergeTags_dspec__0(x_2);
            return x_3;
        }
        default: {
            switch (lungo_obj_tag(x_2)) {
                case 0: {
                    x_4 = capdagFormal__l_List_dall_d__at___dTaggedUrn_dmergeTags_dspec__1(x_1);
                    return x_4;
                }
                default: {
                    x_5 = lungo_ctor_get(x_2, 0);
                    x_6 = lungo_ctor_get(x_1, 0);
                    x_7 = lungo_ctor_get(x_1, 1);
                    x_8 = lungo_ctor_get(x_2, 1);
                    x_9 = lungo_ctor_get(x_5, 0);
                    x_10 = lungo_ctor_get(x_5, 1);
                    x_11 = lungo_ctor_get(x_6, 0);
                    x_12 = lungo_ctor_get(x_6, 1);
                    x_13 = capdagFormal__l_String_ddecidableLT(x_11, x_9);
                    switch (x_13) {
                        case 0: {
                            x_14 = capdagFormal__l_String_ddecidableLT(x_9, x_11);
                            switch (x_14) {
                                case 0: {
                                    x_15 = capdagFormal__l_TaggedUrn_dtagMatch(x_12, x_10);
                                    switch (x_15) {
                                        case 0: {
                                            return x_15;
                                        }
                                        default: {
                                            {
                                                lungo_obj t_0 = x_7;
                                                lungo_obj t_1 = x_8;
                                                x_1 = t_0;
                                                x_2 = t_1;
                                                goto _start;
                                            }
                                        }
                                    }
                                }
                                default: {
                                    x_17 = lungo_box(0);
                                    x_18 = capdagFormal__l_TaggedUrn_dtagMatch(x_17, x_10);
                                    switch (x_18) {
                                        case 0: {
                                            return x_18;
                                        }
                                        default: {
                                            {
                                                lungo_obj t_0 = x_1;
                                                lungo_obj t_1 = x_8;
                                                x_1 = t_0;
                                                x_2 = t_1;
                                                goto _start;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        default: {
                            x_20 = lungo_box(0);
                            x_21 = capdagFormal__l_TaggedUrn_dtagMatch(x_12, x_20);
                            switch (x_21) {
                                case 0: {
                                    return x_21;
                                }
                                default: {
                                    {
                                        lungo_obj t_0 = x_7;
                                        lungo_obj t_1 = x_2;
                                        x_1 = t_0;
                                        x_2 = t_1;
                                        goto _start;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

