/* Generated by lungo 1.87.0 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module TaggedUrn.Exec. */
#include "capdagFormal_program.h"

/* Lean: TaggedUrn.Exec.make */
/* Source: ../../../../formal/../../tagged-urn/formal/TaggedUrn/Exec.lean:26:1 */
lungo_obj capdagFormal__l_TaggedUrn_dExec_dmake(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_inc(x_2);
    x_3 = capdagFormal__l_TaggedUrn_dinstDecidableSorted(x_2);
    switch (x_3) {
        case 0: {
            lungo_dec(x_2);
            lungo_dec_ref(x_1);
            x_4 = lungo_box(0);
            return x_4;
        }
        default: {
            x_5 = lungo_alloc_ctor(0, 2, 0);
            lungo_ctor_set(x_5, 0, x_1);
            lungo_ctor_set(x_5, 1, x_2);
            x_6 = lungo_alloc_ctor(1, 1, 0);
            lungo_ctor_set(x_6, 0, x_5);
            return x_6;
        }
    }
}

/* Lean: TaggedUrn.Exec.meets */
/* Source: ../../../../formal/../../tagged-urn/formal/TaggedUrn/Exec.lean:66:1 */
uint8_t capdagFormal__l_TaggedUrn_dExec_dmeets(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    lungo_obj x_8;
    uint8_t x_9;
    x_3 = lungo_ctor_get(x_1, 0);
    lungo_inc_ref(x_3);
    x_4 = lungo_ctor_get(x_1, 1);
    lungo_inc(x_4);
    lungo_dec_ref(x_1);
    x_5 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_5);
    x_6 = lungo_ctor_get(x_2, 1);
    lungo_inc(x_6);
    lungo_dec_ref(x_2);
    x_7 = capdagFormal__l_String_ddecEq(x_3, x_5);
    lungo_dec_ref(x_5);
    lungo_dec_ref(x_3);
    switch (x_7) {
        case 0: {
            lungo_dec(x_6);
            lungo_dec(x_4);
            return x_7;
        }
        default: {
            x_8 = capdagFormal__l_TaggedUrn_dExec_dmeets_d__closed__0();
            x_9 = capdagFormal__l_TaggedUrn_dmergeWith(x_8, x_4, x_6);
            return x_9;
        }
    }
}

/* Lean: TaggedUrn.Exec.meets._closed_0 */
/* Compiled from: TaggedUrn.Exec.meets */
/* Source: ../../../../formal/../../tagged-urn/formal/TaggedUrn/Exec.lean:66:1 */
static lungo_obj capdagFormal__l_TaggedUrn_dExec_dmeets_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_alloc_closure((void *)capdagFormal__l_TaggedUrn_dtagMeets_d__boxed, 2, 0);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_TaggedUrn_dExec_dmeets_d__closed__0__cell;
lungo_obj capdagFormal__l_TaggedUrn_dExec_dmeets_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_TaggedUrn_dExec_dmeets_d__closed__0__cell, capdagFormal__l_TaggedUrn_dExec_dmeets_d__closed__0__init);
}

/* Lean: TaggedUrn.Exec.meetsClosed */
/* Source: ../../../../formal/../../tagged-urn/formal/TaggedUrn/Exec.lean:89:1 */
uint8_t capdagFormal__l_TaggedUrn_dExec_dmeetsClosed(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    lungo_obj x_8;
    uint8_t x_9;
    x_3 = lungo_ctor_get(x_1, 0);
    lungo_inc_ref(x_3);
    x_4 = lungo_ctor_get(x_1, 1);
    lungo_inc(x_4);
    lungo_dec_ref(x_1);
    x_5 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_5);
    x_6 = lungo_ctor_get(x_2, 1);
    lungo_inc(x_6);
    lungo_dec_ref(x_2);
    x_7 = capdagFormal__l_String_ddecEq(x_3, x_5);
    lungo_dec_ref(x_5);
    lungo_dec_ref(x_3);
    switch (x_7) {
        case 0: {
            lungo_dec(x_6);
            lungo_dec(x_4);
            return x_7;
        }
        default: {
            x_8 = capdagFormal__l_TaggedUrn_dExec_dmeetsClosed_d__closed__0();
            x_9 = capdagFormal__l_TaggedUrn_dmergeWith(x_8, x_4, x_6);
            return x_9;
        }
    }
}

/* Lean: TaggedUrn.Exec.meetsClosed._closed_0 */
/* Compiled from: TaggedUrn.Exec.meetsClosed */
/* Source: ../../../../formal/../../tagged-urn/formal/TaggedUrn/Exec.lean:89:1 */
static lungo_obj capdagFormal__l_TaggedUrn_dExec_dmeetsClosed_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_alloc_closure((void *)capdagFormal__l_TaggedUrn_dtagMeetsClosed_d__boxed, 2, 0);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_TaggedUrn_dExec_dmeetsClosed_d__closed__0__cell;
lungo_obj capdagFormal__l_TaggedUrn_dExec_dmeetsClosed_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_TaggedUrn_dExec_dmeetsClosed_d__closed__0__cell, capdagFormal__l_TaggedUrn_dExec_dmeetsClosed_d__closed__0__init);
}

/* Lean: TaggedUrn.Exec.refines */
/* Source: ../../../../formal/../../tagged-urn/formal/TaggedUrn/Exec.lean:38:1 */
uint8_t capdagFormal__l_TaggedUrn_dExec_drefines(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    uint8_t x_8;
    x_3 = lungo_ctor_get(x_1, 0);
    x_4 = lungo_ctor_get(x_1, 1);
    x_5 = lungo_ctor_get(x_2, 0);
    x_6 = lungo_ctor_get(x_2, 1);
    x_7 = capdagFormal__l_String_ddecEq(x_3, x_5);
    switch (x_7) {
        case 0: {
            return x_7;
        }
        default: {
            x_8 = capdagFormal__l_TaggedUrn_dmergeTags(x_4, x_6);
            return x_8;
        }
    }
}

/* Lean: TaggedUrn.Exec.refinesClosed */
/* Source: ../../../../formal/../../tagged-urn/formal/TaggedUrn/Exec.lean:79:1 */
uint8_t capdagFormal__l_TaggedUrn_dExec_drefinesClosed(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    lungo_obj x_8;
    uint8_t x_9;
    x_3 = lungo_ctor_get(x_1, 0);
    lungo_inc_ref(x_3);
    x_4 = lungo_ctor_get(x_1, 1);
    lungo_inc(x_4);
    lungo_dec_ref(x_1);
    x_5 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_5);
    x_6 = lungo_ctor_get(x_2, 1);
    lungo_inc(x_6);
    lungo_dec_ref(x_2);
    x_7 = capdagFormal__l_String_ddecEq(x_3, x_5);
    lungo_dec_ref(x_5);
    lungo_dec_ref(x_3);
    switch (x_7) {
        case 0: {
            lungo_dec(x_6);
            lungo_dec(x_4);
            return x_7;
        }
        default: {
            x_8 = capdagFormal__l_TaggedUrn_dExec_drefinesClosed_d__closed__0();
            x_9 = capdagFormal__l_TaggedUrn_dmergeWith(x_8, x_4, x_6);
            return x_9;
        }
    }
}

/* Lean: TaggedUrn.Exec.refinesClosed._closed_0 */
/* Compiled from: TaggedUrn.Exec.refinesClosed */
/* Source: ../../../../formal/../../tagged-urn/formal/TaggedUrn/Exec.lean:79:1 */
static lungo_obj capdagFormal__l_TaggedUrn_dExec_drefinesClosed_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_alloc_closure((void *)capdagFormal__l_TaggedUrn_dtagMatchClosed_d__boxed, 2, 0);
    return x_1;
}
static lungo_lazy_obj capdagFormal__l_TaggedUrn_dExec_drefinesClosed_d__closed__0__cell;
lungo_obj capdagFormal__l_TaggedUrn_dExec_drefinesClosed_d__closed__0(void) {
    return lungo_lazy_obj_get(&capdagFormal__l_TaggedUrn_dExec_drefinesClosed_d__closed__0__cell, capdagFormal__l_TaggedUrn_dExec_drefinesClosed_d__closed__0__init);
}

