"""Standard capability definitions and helpers"""

from capdag.standard.caps import (
    model_availability_urn,
    model_path_urn,
    llm_conversation_urn,
    llm_multiplechoice_urn,
    llm_codegeneration_urn,
    llm_creative_urn,
    llm_summarization_urn,
    embeddings_dimensions_urn,
    embeddings_generation_urn,
    image_embeddings_generation_urn,
    model_download_urn,
    model_list_urn,
    model_status_urn,
    model_contents_urn,
    generate_thumbnail_urn,
    disbind_urn,
    extract_metadata_urn,
    extract_outline_urn,
    frontmatter_summarization_urn,
    structured_query_urn,
    bit_choice_urn,
    make_multiple_decisions_urn,
)

__all__ = [
    "model_availability_urn",
    "model_path_urn",
    "llm_conversation_urn",
    "llm_multiplechoice_urn",
    "llm_codegeneration_urn",
    "llm_creative_urn",
    "llm_summarization_urn",
    "embeddings_dimensions_urn",
    "embeddings_generation_urn",
    "image_embeddings_generation_urn",
    "model_download_urn",
    "model_list_urn",
    "model_status_urn",
    "model_contents_urn",
    "generate_thumbnail_urn",
    "disbind_urn",
    "extract_metadata_urn",
    "extract_outline_urn",
    "frontmatter_summarization_urn",
    "structured_query_urn",
    "bit_choice_urn",
    "make_multiple_decisions_urn",
]
